### ISSUE TITLE
version of the Cruise Control

### ISSUE THREAD

**Issue by quangvuptit** [linkedin/cruise-control#1045]
I don't understand what does this mean

`Copy ./cruise-control-metrics-reporter/build/libs/cruise-control-metrics-reporter-A.B.C.jar (Where A.B.C is the version of the Cruise Control) to your Kafka server dependency jar folder. For Apache Kafka, the folder would be core/build/dependant-libs-SCALA_VERSION/`

**Comment by efeg** [comment]
Hi @quangvuptit 
This quote seems to be copied from a step of the [Quick Start](https://github.com/linkedin/cruise-control#quick-start). This documentation explains how to setup your Cruise Control instance to manage your Kafka cluster.

The previous step of this excerpt, explains which folder you should be in (e.g. `cd cruise-control-0.1.10/`). This step assumes that you followed the previous step. Hence, `./cruise-control-metrics-reporter/build/libs/cruise-control-metrics-reporter-A.B.C.jar` is a path to the jar file, whose name depends on your specific version of Cruise Control. The `A.B.C` corresponds to the version of Cruise Control you decided to fetch from Cruise Control repository. For example, if you decided to get `2.0.79` from https://github.com/linkedin/cruise-control/releases, it will be `2.0.79`.

Hope it helps!
