### ISSUE TITLE
Recommended goals thresholds 

### ISSUE THREAD

**Issue by OuesFa** [linkedin/cruise-control#1047]
Hello, 

What thresholds for the default goals do you recommend for a medium size cluster with throughput of ~30k msg/s and ~1kb/msg.
Are there any docs on the topic ?  

Sorry if it's not the place to ask such recommendations.

Thanks for your help !

**Comment by kidkun** [comment]
By default, the capacity threshold is set to 0.8(resource utilization should not exceed 0.8 of broker capacity) and the balance threshold is set to 1.1(resource utilization should in [0.9, 1,1] of average utilization of cluster), Which I think it is a reasonable value to try in the first place.
you may want to try to increase the balance threshold if you think it is too strict for certain resource type.

**Comment by OuesFa** [comment]
Thanks for your answer !
