### ISSUE TITLE
Partition leader rebalance does not happen

### ISSUE THREAD

**Issue by OuesFa** [linkedin/cruise-control#1048]
I've created a topic with 4 partitions on a cluster of 3 brokers.
So I naturally ended up with a broker containing two partition leaders.
When adding a new broker to the cluster, I was expecting that CC would put the fourth partition leader on the new broker (when calling add a broker) but it did not. 
So as a result I get an imbalanced cluster load status when I start a producer on that topic.
leader to follower is too imbalanced on the new broker as it only contains replicas of the loaded topic.
I tried to execute rebalance manually using CC UI but the leader replicas still lives on one broker.
Is it the normal behaviour ?
Thank you guys
<img width="1384" alt="Capture d’écran 2019-12-20 à 19 07 46" src="https://user-images.githubusercontent.com/10348298/71280845-a5921880-235c-11ea-8b56-77ab55815065.png">
It moved other leaders for idle topics but not the one that is receiving traffic.

**Comment by kidkun** [comment]
can you try to run the following curl command and paste the response here?

curl -X POST -c cookie "hostname:2540/kafkacruisecontrol/rebalance"

if a in-progress response is return, try 
curl -X POST -b cookie "hostname:2540/kafkacruisecontrol/rebalance"
until you get a rebalance result.

**Comment by efeg** [comment]
Closing the issue. @OuesFa please feel free to reopen if you have further questions.
