### ISSUE TITLE
DiskPct doesn’t update

### ISSUE THREAD

**Issue by danielsinai** [linkedin/cruise-control#1050]
Hi, 
I increased my Kafka cluster brokers log.dir.
I let it run for like 2 weeks and untill now the diskpct attribute is still relative to the previous disk
I tried to refresh the cruise control server but that didn’t help.
It says 115% of the broker mount is taken.

Would love to get some help thx :)

**Comment by efeg** [comment]
Hi @danielsinai 
After increasing your Kafka cluster brokers log.dir capacity, have you 
1. updated the contents of the corresponding capacity file configured by `capacity.config.file=` in `config/cruisecontrol.properties` to reflect these changes (see https://github.com/linkedin/cruise-control/blob/master/config/cruisecontrol.properties#L91)?
2. After updating the `capacity.config.file`, have you bounced your Cruise Control instance?

After the 2 steps above, the capacity changes should be instantaneously captured by Cruise Control.

**Comment by danielsinai** [comment]
Thanks!
sorry about tagging that as an issue.
I was sure cruise-control figures out the storage automatically
I will try that and close that issue if it works

**Comment by efeg** [comment]
@danielsinai Please feel free to reopen if the issue is not resolved.
