### ISSUE TITLE
Irrelevant DiskCapacityGoal error ? 

### ISSUE THREAD

**Issue by OuesFa** [linkedin/cruise-control#1052]
Hello,

I'm getting the following error when trying to add a broker using CC UI.
`ERROR: Error processing POST request '/add_broker' due to: 'com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [DiskCapacityGoal] Insufficient healthy cluster capacity for resource: disk existing cluster utilization 177247.171875 allowed capacity 30000.000000 (capacity threshold: 0.500000).'.`

Though here is the disk capacity of my cluster
<img width="679" alt="Capture d’écran 2019-12-26 à 15 19 50" src="https://user-images.githubusercontent.com/10348298/71479070-36e90b00-27f3-11ea-9ff2-e5b7c936be5d.png">

It would be helpful if someone  could explain how CC is calculating the disk utilization of 177247.171875 and the capacity of 30000.000000
Thank you !

**Comment by OuesFa** [comment]
I found out it's the capacity.json file
I m using the default one 
```
      {
        "brokerCapacities":[
          {
            "brokerId": "-1",
            "capacity": {
              "DISK": "10000",
              "CPU": "100",
              "NW_IN": "10000",
              "NW_OUT": "10000"
            },
            "doc": "This is the default capacity. Capacity unit used for disk is in MB, cpu is in percentage, network throughput is in KB."
          }
        ]
      }
```
Is it possible to make CC recognize broker disk  capacity (and other properties) dynamically ?
And if not how to tune _NW_OUT & NW_OUT_ correctly for each broker please ?

**Comment by efeg** [comment]
Hi @OuesFa 
#### Populating the Capacity Config File
`Option-1`: The following steps allow users to set the initial broker capacities or update capacities upon addition of 
new brokers out-of-the-box:
1. Check `cruisecontrol.properties` file to verify that the `capacity.config.file=` config points to the file you are modifying.
By default, this config is set to use `config/capacityJBOD.json`. If you have 
    * a non-JBOD deployment, where each broker has the same number of cores, you may use `config/capacity.json`, or
    * a non-JBOD deployment, where brokers may have varying number of cores, you may use `config/capacityCores.json`
 and modify this file.
2. Ensure that the capacity file picked in `step-1` contains either a default capacity for missing broker ids, or 
explicitly specifies capacities for brokers with specific ids provided by user.
3. Finally, bounce your Cruise Control instance.

`Option-2`: `BrokerCapacityConfigResolver` is a pluggable component. Hence, you can write your own pluggable capacity 
resolver to dynamically resolve the broker capacities if you have a source to provide the capacity information. 
Using this approach, you may avoid restarting your CC instance upon a (1) capacity change or (2) addition of a broker 
with a non-default capacity. See:
1. [The relevant interface](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigResolver.java),
2. Its default implementation by [BrokerCapacityConfigFileResolver](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/BrokerCapacityConfigFileResolver.java), and 
3. The [relevant configuration](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java#L294) to set the config resolver to be used.


Hope it helps!
