### ISSUE TITLE
Can't run latest version of CC on Kafka 1.1.1

### ISSUE THREAD

**Issue by OItsMAK** [linkedin/cruise-control#1056]
I'm currently trying CruiseControl; To do so, I've set up two brokers on `localhost:9092` and `localhost:9093`. And a ZooKeeper node on `localhost:2181`.

I tried running the latest code on a Kafka 1.1.1 cluster, And all I got was a bunch of these:
```
 WARN Failed to send Cruise Control metric ... # (Some metric)
```

But did the same thing on a Kafka 2.4.0 cluster, and it all worked.

From what I understood from the [Quick Start docs](https://github.com/linkedin/cruise-control#quick-start), it should have worked with 1.1.1, but it didn't.
Am I understanding this wrong or doing something wrong?

Btw, I ran `./gradlew jar copyDependantLibs`, copied the jar to `<kafka-dir>/libs/`, and put these at the bottom of the `server.properties` config file:
```Properties
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.reporter.bootstrap.servers=localhost:9092
cruise.control.metrics.reporter.metrics.reporting.interval.ms=5000 # Don't judge, just testing! :)
```
Also, the default CC config points to localhost and so no changes were necessary. I added the `localhost:9093` to the bootstrap.servers tho.

**Comment by OItsMAK** [comment]
Btw, I tried CC version 0.1.69 and it worked.
Same configurations.

**Comment by efeg** [comment]
Hi @OItsMAK 
Thanks for reporting this and glad to hear that the issue is resolved :)
Metrics reporter producer of `CC master` branch seems to be the culprit on `Kafka 1.1.1`.
-- updated the [Environment Requirements](https://github.com/linkedin/cruise-control#environment-requirements) to reflect this change.

**Comment by OItsMAK** [comment]
Cool. :)

Cheers.
