### ISSUE TITLE
How to configure Email Notification for Kakfa node health.

### ISSUE THREAD

**Issue by suren-pratap** [linkedin/cruise-control#1059]
Hi,

Please suggest, how to configure Email Notification for Kakfa node health.

**Comment by efeg** [comment]
Hi @suren-pratap,

To send/receive email notifications for anomalies, e.g. `broker failures`, you can 
1. implement your own anomaly notifier class,
2. ensure that `anomaly.notifier.class` config points to your new class, and
3. restart Cruise Control.

For an example implementation that sends notifications to a `Slack` channel, you can check its PR (see https://github.com/linkedin/cruise-control/pull/629), and follow its documentation (see [wiki](https://github.com/linkedin/cruise-control/wiki/Configure-Slack-notifications)).

Hope it helps!
