### ISSUE TITLE
Json Web Token based authentication

### ISSUE THREAD

**Issue by viktorsomogyi** [linkedin/cruise-control#1065]
As a continuation of the authentication work in #988 it would be useful to create JWT based authentication as in an integrated environment it easy, reliable and practical to pass around tokens for access control purposes.

For instance a 3rd party service, such as Apache Knox could front Cruise Control and log in users. In this case Cruise Control just checks the incoming requests for Json Web Tokens in the Authorization header or in a cookie and validates their signature and performs the requested action or redirects the user if the validation fails.

The proposed implementation however would be independent of any specific token provider (Knox was just as an example that we would use) and would provide a generic implementation for validating requests according to the JWT specifications.

**Comment by viktorsomogyi** [comment]
@efeg are you interested in JWT authentication for Cruise Control? We plan to use it with Apache Knox and I currently have a solution in progress for this (a generic one which doesn't depend on Knox specifically) and I'd be happy to contribute it if it's useful from your point of view.

**Comment by efeg** [comment]
@viktorsomogyi Absolutely! We would appreciate your contribution on this.
