### ISSUE TITLE
Cruise Control proposal calculation too slow

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#1086]
In production environment we observed that for some large cluster, it takes Cruise Control 30 minutes to calculate the proposal to fix certain resource distribution goal.  It looks that [PER_BROKER_SWAP_TIMEOUT_MS](https://github.com/linkedin/cruise-control/blob/b92b76e60df234d442f0ca6c829d419ef9cc1d53/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/ResourceDistributionGoal.java#L53) does not work.

**Comment by 3286360470** [comment]
Hi, I also enchountered the same problem, so ,what did you do afterwards?

**Comment by efeg** [comment]
This issue has been addressed in https://github.com/linkedin/cruise-control/pull/1589 and https://github.com/linkedin/cruise-control/pull/1593.
