### ISSUE TITLE
Cruise Control does not publish test package

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#1098]
Test package contains many good util class (e.g. [`DeterministicClusterTest`](https://github.com/linkedin/cruise-control/blob/fa28efe7207c3447bca4a55447f42e120e5acd66/cruise-control/src/test/java/com/linkedin/kafka/cruisecontrol/analyzer/DeterministicClusterTest.java#L60) to generate various cluster model to test optimizer) to build new tests for project which depends on it, it is nice to push it in release.

**Comment by efeg** [comment]
We decided not to publish test package -- i.e. it is better practice to create a separate module for keeping relevant util classes rather than using the test jar. Closing this issue.
