### ISSUE TITLE
Cruise Control not collecting metrics

### ISSUE THREAD

**Issue by mlukowicz** [linkedin/cruise-control#1103]
Hello Team!

I am testing CC with 3 brokers running in containers (not k8s - just plain docker on 3 VM's, version 1.1.1).

- cloned repo
- did 'gradlew jar' + copied metrics reporter lib to Kafka lib dir
- did 'gradlew jar copyDependantLibs'
- added appropriate config: 

`metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.reporter.bootstrap.servers=0.0.0.0:9092`

Metrics are not being collected at all(upon pressing bootstrap metrics):

INFO Collected 0 partition metric samples for 0 partitions. Total partition assigned: 1156.

I have no error neither on Kafka nor on CC side.
CC metrics topics are about 20MB in size.

Anywhere else I can take a look?

**Comment by mlukowicz** [comment]
NIC issue - problem solved.

**Comment by mlukowicz** [comment]
After NIC issue solved problem returned back.

**Comment by efeg** [comment]
@mlukowicz Did updating `cruise.control.metrics.reporter.bootstrap.servers` resolve the issue?

**Comment by mlukowicz-fx** [comment]
Hi @efeg - sorry i missed email notification - yes, this solved the issue.

**Comment by efeg** [comment]
Closing this -- @mlukowicz please feel free to reopen if the issue is not resolved.
