### ISSUE TITLE
DryRun flag is not correctly used on creating composite replica movement strategy 

### ISSUE THREAD

**Issue by daniyar-kulakhmetov-liftoff** [linkedin/cruise-control#1126]
The [getReplicaMovementStrategy](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java#L618) method of `ParameterUtils` class checks the dryrun mode incorrectly.

Instead of creating a composite strategy if it is not a dryrun mode, it does vice versa:
```
    if (!getDryRun(request)) {
      return null;
    }
```

Should be:
```
    if (getDryRun(request)) {
      return null;
    }
```

That's for both branches: master and kafka_0_11_and_1_0.

**Comment by efeg** [comment]
Closing this issue as it has been resolved on the linked PR.
