### ISSUE TITLE
Chaining the replica movement strategies doesn't work correctly

### ISSUE THREAD

**Issue by daniyar-kulakhmetov-liftoff** [linkedin/cruise-control#1127]
The [chained replica movement strategies class](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/strategy/AbstractReplicaMovementStrategy.java#L27) is a composite class. When applying strategy, it calls [applyStrategy](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/strategy/AbstractReplicaMovementStrategy.java#L30) of its internal variable named `current`.  Since the `current` is a separate object, it doesn't use an overridden `taskComparator` method of the chained strategies class (parent object).

**Comment by efeg** [comment]
Looks like this issue was addressed in https://github.com/linkedin/cruise-control/pull/1184.
