### ISSUE TITLE
DISK, CPU and NW_OUT low utilization thresholds are not used

### ISSUE THREAD

**Issue by amuraru** [linkedin/cruise-control#1147]
I am setting `{cpu,disk,network.inbound,network.outbound}.low.utilization.threshold` parameters to avoid self-healing of Goal violations under low load but I noticed that `cpu,disk,network.outbound` are actually never used in the code.

The only reference is to `lowUtilizationThreshold` is in `LeaderBytesInDistributionGoal` to check  `network.inbound` threshold.

https://github.com/linkedin/cruise-control/blob/da27f36297d240978c1067da303e67d812d5f922/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/LeaderBytesInDistributionGoal.java#L252

Am I missing something? Thanks

**Comment by efeg** [comment]
@amuraru Thanks for reporting, that is indeed the case.

I agree that support for these configs on resource distribution goals would be useful to reduce redundant goal violation self-healing actions on low utilization clusters.

**Comment by amuraru** [comment]
@Lincong @efeg thanks for implementing this!

Are these low usage thresholds are apply to:
https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java
?

**Comment by Lincong** [comment]
> @Lincong @efeg thanks for implementing this!
> 
> Are these low usage thresholds also apply to:
> https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/goals/IntraBrokerDiskUsageDistributionGoal.java
> ?

Hi @amuraru , this implementation does not apply the low utilization threshold to the `IntraBrokerDiskUsageDistributionGoal` goal. I will discuss with @efeg whether we need to do that as well. Thanks.
