### ISSUE TITLE
Add HTTPS support to the webserver

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#115]
Make the jetty listen on the same/different port with https with user supplied certificates

**Comment by KarstenSchnitter** [comment]
I would appreciate support for user supplied certificates as well. Has there been any progress in the mean time?

**Comment by jitendra-gojek** [comment]
Do we have any plans to fix this issue ?

**Comment by mhratson** [comment]
- closed by https://github.com/linkedin/cruise-control/pull/988
- docs: https://github.com/linkedin/cruise-control/wiki/Security#https
