### ISSUE TITLE
Add HTTP Basic Auth to the webserver to protect admin resources

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#116]
This is a start, we can have a BASIC auth support (along with HTTPS) to protect the admin resources in the cruise control. In future we can add more fine grained access controls by leveraging LDAP, MySQL, etc.

**Comment by KarstenSchnitter** [comment]
I would appreciate support for authentication. Has there been any progress in the mean time?

**Comment by viktorsomogyi** [comment]
@efeg I'd like to take up this task. Do you have any direction in mind where I should go with the implementation? I was thinking about creating an interface which abstracts the setting up of `ConstraintMapping` and `LoginService` with a default implementation of basic authentication and `HashLoginService`. What do you think?

**Comment by efeg** [comment]
@viktorsomogyi Adding Basic Authentication support with `HTTPS` would be a great addition.
The high-level design sounds good to me, I am looking forward to the patch!
