### ISSUE TITLE
Execution hangs

### ISSUE THREAD

**Issue by mlukowicz-fx** [linkedin/cruise-control#1208]
Hello Team!

Found strange issue: i am executing rebalance, it starts to move data among brokers and then after some time of working it stops - i was able to wait a day for testing - nothing happend.
After i force controller reelection all execution continues without any issues.
I did research in logs both CC and Kafka but found nothing - all looks clean.
Any ideas?

Kafka 2.5.0
CC - 2.0.102 

Same things happens with 1.1.1 + 0.1.69

EDIT: yes, i know it is not with 2.5.0 yet - but same observed on 2.4.1, 2.4.0, 1.1.1 with appropriate CC version.

Michał

**Comment by efeg** [comment]
Hi Michał, would you please give it a try with CC version https://github.com/linkedin/cruise-control/releases/tag/2.4.0 on Kafka `2.5.0`? I suspect that this might be related to https://github.com/linkedin/cruise-control/issues/1167.

**Comment by mlukowicz-fx** [comment]
@efeg - looks exactly like that. Will give it a try tomorrow.

**Comment by mlukowicz-fx** [comment]
@efeg did couple of checks - looks like this fixes the issue - i will have more balancing in action today however first test looks just perfect.

**Comment by efeg** [comment]
@mlukowicz-fx happy to hear that -- please let us know in case of any followup issues.
