### ISSUE TITLE
Metrics reporter Admin Client gives up too early on metrics topic creation

### ISSUE THREAD

**Issue by ppatierno** [linkedin/cruise-control#1216]
We are facing the following problem ...

When the `cruise.control.metrics.topic.auto.create` is set to `true`, the cruise control metrics reporter uses the Admin Client API to create the metrics topic but it has a fixed timeout of 10 seconds (`CLIENT_REQUEST_TIMEOUT_MS`) waiting that the topic is actually created.
After this timeout, it just gives up on creation. At this point, if the Kafka cluster has the auto topic creation enabled (`auto.create.topics.enable`), the metrics topic is still created when the metrics reporter starts to produce messages otherwise (Kafka auto topic creation disabled) it fails to send metrics message because of the topic doesn't exist and wasn't created. It will fail until "someone" will create the topic explicitly.

This scenario can happen when the bootstrap server list for the metrics reporter is filled with some brokers which are not online at the moment of metrics topic creation or for network issues they don't reply in 10 seconds.
Because we are using cruise control in our Strimzi project, it actually happens when a new Kafka cluster is created. During the startup, not all the brokers behind the bootstrap Kubernetes service (used by the metrics reporter) are ready to serve the request and they won't be in 10 seconds.

It would be really useful having the possibility to configure this timeout on metrics topic creation (instead of the hardcoded `CLIENT_REQUEST_TIMEOUT_MS`) with even some retries and maybe a backoff mechanism, in order to allow the metrics reporter to try more times to create the metrics topic before giving up.

I would like to work and propose a PR for this change. In normal conditions, when all the brokers are ready and immediately reachable by the admin client in the metrics reporter, nothing will change in terms of behavior.

**Comment by efeg** [comment]
> I would like to work and propose a PR for this change. 

@ppatierno Making `CLIENT_REQUEST_TIMEOUT_MS` configurable would be a valuable contribution -- we would be happy to see your contribution.

**Comment by ppatierno** [comment]
Thanks! I am on it!
