### ISSUE TITLE
Stopping proposal execution may increase the replication factor for a topic

### ISSUE THREAD

**Issue by ccciudatu** [linkedin/cruise-control#1226]
After playing with rebalance for a few times and stopping the execution more than once, I noticed that the replication factor for two of my topics (as reported by `kafka-topics.sh --describe`) has increased from 3 to 4. At a closer look, only a subset of the partitions (e.g. 3 out of 12) actually have 4 replicas.

My assumption is that stopping the rebalance executions in progress is the cause for this, although I wasn't able to reproduce it "on demand".
Is this the intended behaviour or should the partition movement be done "atomically"? i.e. on "stop",  should the source replica be removed if successfully copied to target, before cancelling the execution?

**Comment by efeg** [comment]
@ccciudatu Stopping an execution does not cause an increase in replication factor (RF) if it is stopped gracefully (e.g. `POST /kafkacruisecontrol/stop_proposal_execution`). However, _explicitly force stopping an execution can cause an increase in RF_ (e.g. `POST /kafkacruisecontrol/stop_proposal_execution?force_stop=true`).

You can fix such inconsistencies in RF using `topic_configuration` endpoint. For example, the following command sets the replication factor of all topics to 3.

```
POST /kafkacruisecontrol/topic_configuration?&topic=.%2A&replication_factor=3
```

Note that `.%2A` is the url encoded version of regex `.*`. You can change the regex for your specific use-case.

**Comment by ccciudatu** [comment]
Thanks, @efeg. I'm pretty sure I never used force_stop myself, but I'm not as confident anymore that I was the only one playing with that particular CC instance and Kafka cluster. So I just wanted to confirm that my reading of the code is accurate.
If I manage to reproduce this with graceful stop, I'll report it as a bug.
