### ISSUE TITLE
outdated Configuration page for wiki

### ISSUE THREAD

**Issue by d1egoaz** [linkedin/cruise-control#1261]
according to this
https://github.com/linkedin/cruise-control/blob/2.0.114/config/cruisecontrol.properties#L76-L77

```
# The number of partition metric windows to keep in memory
num.partition.metrics.windows=1
```
it defaults to `1`, however wiki says it's 5
<img src="https://screenshot.click/2020-07-09_09-19-55_sr41l.png" width="50%" />

it might be more out of sync defaults 🤷

**Comment by efeg** [comment]
Hi @d1egoaz 
The "default config value" refers to the value assigned to a config if it is not explicitly assigned a value in `cruisecontrol.properties` file. In your example, a value of `1` is explicitly assigned to `num.partition.metrics.windows` in `cruisecontrol.properties`. For the default value of this config, please see:
* https://github.com/linkedin/cruise-control/blob/2.0.114/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java#L103

```
  /**
   * <code>num.partition.metrics.windows</code>
   */
  public static final String NUM_PARTITION_METRICS_WINDOWS_CONFIG = "num.partition.metrics.windows";
  public static final int DEFAULT_NUM_PARTITION_METRICS_WINDOWS = 5;
  public static final String NUM_PARTITION_METRICS_WINDOWS_DOC = "The total number of windows to keep for partition "
      + "metric samples";
```

**Comment by d1egoaz** [comment]
got it, I wonder what would most people do, I think they will copy over the `cruisecontrol.properties` file and use the values that are there, overriding the (sane?) defaults from https://github.com/linkedin/cruise-control/blob/2.0.114/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/constants/MonitorConfig.java
