### ISSUE TITLE
Why DiskRebalance throws java.lang.IllegalStateException?

### ISSUE THREAD

**Issue by PavloLobachov** [linkedin/cruise-control#1280]
I'm currently playing around with cruise-control. I was following this instructions https://github.com/linkedin/cruise-control#quick-start. Preferred Leader Election and Rebalance Cluster works perfect. But to day I decided to try Rebalance Broker Disks operation and faced issue with it, when I tried to perform rebalance cruise-control raised exception

**java.util.concurrent.ExecutionException: Operation 'Rebalance' received exception. com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.IllegalStateException: Missing disk information for disk /var/lib/kafka/data on broker ClusterModel[brokerCount=3,partitionCount=0,aliveBrokerCount=3]**

And I can't understand what I'm doing wrong. 

My setup is:
- 3 confluent cp-kafka:5.5.0 docker instances
- 3 cp-zookeeper:5.5.0 docker instances
Cruise-control run on my host machine

I've tried with attached volumes and without, but no luck.

Is there any configurations I'm missing?

**Comment by efeg** [comment]
Hi @PavloLobachov 

It seems like you might be explicitly setting `rebalance_disk=true` in your `rebalance` request, which asks CC to `balance load between disks within each broker`. However, this parameter applies to JBOD deployments, but your cluster seems to be configured as a non-JBOD deployment -- i.e. has just 1 logDir per broker. Hence, as expected, you are getting this exception.

-- As a side note, if you use the default goals, you are already balancing the disk usage across your brokers in the cluster. The [current description](https://github.com/linkedin/cruise-control/wiki/REST-APIs) of `rebalance_disk` seems vague -- I will create a PR to update that.

Please let me know if you'd have other questions.

**Comment by PavloLobachov** [comment]
Thank you very much for a quick reply
