### ISSUE TITLE
User Message: cruise-control ongoing execution exception

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#1285]
# Background
The `cruise-control` [Executor](https://github.com/linkedin/cruise-control/blob/88cd1ec3c2c69add1c56617e5ab21b92d80f26e1/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java) maintains an internal boolean `_hasOngoingExecution` to help it fail fast when it's asked to perform an execution, but it's already performing one.

This helps `cruise-control` not to spend time calculating a proposal that it will be unable to start.

The Executor's `startExecution` helper method [eagerly sets](https://github.com/linkedin/cruise-control/blob/88cd1ec3c2c69add1c56617e5ab21b92d80f26e1/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java#L564) `_hasOngoingExecution` to true when it is invoked, but before it starts to calculate the proposal.  
This is the correct behavior in order to prevent two simultaneous non-dryrun proposal calculations.

# Issue
In some cases, proposal calculation can take several minutes.  
During this time, from the user's perspective (i.e. the `state` endpoint), there is no ongoing execution.  
However, from `cruise-control`'s perspective, `_hasOngoingExecution` is true, and it is calculating the execution.

This leads to a confusing message where, when a new proposal is requested, `cruise-control` [responds](https://github.com/linkedin/cruise-control/blob/88cd1ec3c2c69add1c56617e5ab21b92d80f26e1/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java#L239) with  
```text
java.lang.IllegalStateException: Cannot start a new execution while there is an ongoing execution. Please use stop_ongoing_execution=true to stop ongoing execution and start a new one
```

# Proposal
The best outcome here is that the user is aware that `cruise-control` is legitimately busy, and that new executions are not allowed right now.

Whether this is achieved by maintaining and exposing a "calculating" state through the `state` endpoint, or by changing the text of the `IllegalStateException`, there are some options.

**Comment by efeg** [comment]
This request has been addressed in https://github.com/linkedin/cruise-control/pull/1282.
