### ISSUE TITLE
Current metrics reporter does not work with Kafka 2.6.0

### ISSUE THREAD

**Issue by tomncooper** [linkedin/cruise-control#1309]
The current `CruiseControlMetricsReporter` does not work on Kafka 2.6.0 clusters. The issue seems to be linked to recent changes in Kafka that changed where the `MetricsRegistry` is obtained from. The default registry now needs to be pulled from the `kafka.metrics.KafkaYammerMetrics` class instead of the `com.yammer.metrics.Metrics` class.

I have a working fix but I was wondering if I should open a PR against the `migrate_to_kafka_2_5` branch or wether it would be better for a committer to create a `migrate_to_kafka_2_6` branch that I can open it against?

**Comment by efeg** [comment]
@tomncooper Thanks for bringing this up and experimenting with a fix.
This would seem to require a new branch -- I created `migrate_to_kafka_2_6` for you to create the PR against.
