### ISSUE TITLE
Error while building project(unable to find valid certification path to requested target)

### ISSUE THREAD

**Issue by atulrenapurkar** [linkedin/cruise-control#1310]
Steps to reproduce.
Step 1: 
git clone https://github.com/linkedin/cruise-control.git && cd cruise-control/
Step 2:
./gradlew jar

 I am facing below error. 
11:33:03.507 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':buildSrc:compileGroovy'.
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not resolve all files for configuration ':buildSrc:compileClasspath'.
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download gradle-git.jar (org.ajoberstar:gradle-git:1.7.2)
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/org/ajoberstar/gradle-git/1.7.2/gradle-git-1.7.2.jar'.
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/682723f5bae1138f0e369d9de00a705de3d77428795dde136dd7fd1acbc29a9c?response-content-disposition=attachment%3Bfilename%3D%22gradle-git-1.7.2.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNjgyNzIzZjViYWUxMTM4ZjBlMzY5ZDlkZTAwYTcwNWRlM2Q3NzQyODc5NWRkZTEzNmRkN2ZkMWFjYmMyOWE5Yz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdyYWRsZS1naXQtMS43LjIuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk3MDczODg3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=hP0VtVeboQO92KbaZOxsfNg0YImfX-VoK6TWjvoarglq-B4xXpogN50xAwhBRw4bflRvrLLd2T-hVkLzFAvM5Dd2x2GJneCDSA-vM2zZbPLmhjwXxdmkebK6~IDSzpUV0mUVH1mp11OrxkTLeK73~eOis87YjYbINzge3y0aXVeaaUOJXttlCl6mfHLV8Q8C7K7kyO26niQXYfOAhZn4wolZGUL3kZHSjpIE6a9Cldcj7BOgy1Z-nBpY-5un~fEFdU9at64MMYXr1xXmsQ7XakXCWsRAcTuxOgCO0a-VutJdXEM7e3fAAJWIpWtpCwTEn~62c016Vhj-hibcYDIspA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.5.8)
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.jar'.
11:33:03.508 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/bebc085fc7675c75111e98295b830565cf040dd118029d2c0bbfd0779cf685a4?response-content-disposition=attachment%3Bfilename%3D%22httpclient-4.5.8.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYmViYzA4NWZjNzY3NWM3NTExMWU5ODI5NWI4MzA1NjVjZjA0MGRkMTE4MDI5ZDJjMGJiZmQwNzc5Y2Y2ODVhND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmh0dHBjbGllbnQtNC41LjguamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk3MDc0MTg0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=BuyxOtl-x0oE0J62pWWvLfQSbn65J2AOwK6aUimmal6FiEfNeoxvERnptRhLtCW07lvOTh-cKNgfEv6L~j6R6SR72-2FGmLva~~b8i4wE1Up9urUHVisgq0fw97t~CktnySoQC3yhAygVWIcGaqGwvS190SrLExY6ZaaK9mp1oM1kCY444xndDjIpzK9ND1bctmqqS5jcETA3UTauXVu2FUqPI0-Sxtfdxmo2~Vl9SQmAbgpgmwRvU0vecsUd6ABLrq0xijFpVafCUymixD44GqBHO~k5DGCyhJVpjhkiBowceatobp1ydBqyPbDH3rEQe00t0-qAIxHxHAekNZZDw__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download commons-lang.jar (commons-lang:commons-lang:2.4)
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/commons-lang/commons-lang/2.4/commons-lang-2.4.jar'.
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/16313e02a793435009f1e458fa4af5d879f6fb11?response-content-disposition=attachment%3Bfilename%3D%22commons-lang-2.4.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMTYzMTNlMDJhNzkzNDM1MDA5ZjFlNDU4ZmE0YWY1ZDg3OWY2ZmIxMT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmNvbW1vbnMtbGFuZy0yLjQuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk3MDc0MTU5fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=N-BRyOYc6l33s-1GbJxoKX51D5nWwCxjxxn0w2x4TNlnApia88EnMz0zgNmL3jgnr6UVIoZP8Elfg7g5fp6QtXAS70KdcKwGLjoJus9ykwFK3-h7CWaY2DJUqs-uX1gb9PLAcw9K41BB1ak-a6tq0eMw70J0ud8Y9hsp4W4i1C07UGVI8cxKb-ezpSlZKUpmi4huL4BSgIqKGE1O6EcoamWYTFP6bx8ZHq4HVsmCgL5Qpc4IK~t8eykXKROPdDb3lDKkyH6HBmoL77zXmCvu6DnU1vX-vzwR3nqTtRhKQc6S6tRDU52TNLUDcS3-kLPQRmT6i93im0ZzBm0EEUqF~A__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download ivy.jar (org.apache.ivy:ivy:2.2.0)
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/org/apache/ivy/ivy/2.2.0/ivy-2.2.0.jar'.
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/f9d1e83e82fc085093510f7d2e77d81d52bc2081?response-content-disposition=attachment%3Bfilename%3D%22ivy-2.2.0.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZjlkMWU4M2U4MmZjMDg1MDkzNTEwZjdkMmU3N2Q4MWQ1MmJjMjA4MT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMml2eS0yLjIuMC5qYXIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTcwNzM3MTF9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=LRw8VQIDp5cOLQO1e0uqR6AFKmkc0C8YzLeedf4G51yyf5ajT6ysH-U5hhRNjzh-cxqxVjFYVD9NedHiOB~Us4cWwjgDJW-AHsh113av7xPymszgqbyDBeKBOnCZMjMpu6YvEut0hSlOx44ebQKokc7Zcj43eheB86xNrNUd2J1YYdtrxQUe6Fer3AKlr15CyrXy46iI9a~QrKO5u3C6X486QF8SH9rl7cf~bXhFeMh1hmAUkHKOYozruW3nbopIg3-RpK1LHad0nemSWx87RTaYYHPnLQl98lIa0V5h~siNbrPVzkIHjSHU-lf8teOjaSaCMfMbJ~Osef4aKWPVmw__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
11:33:03.509 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not download guava.jar (com.google.guava:guava:27.0.1-jre)
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar'.
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]          > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/e1c814fd04492a27c38e0317eabeaa1b3e950ec8010239e400fe90ad6c9107b4?response-content-disposition=attachment%3Bfilename%3D%22guava-27.0.1-jre.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZTFjODE0ZmQwNDQ5MmEyN2MzOGUwMzE3ZWFiZWFhMWIzZTk1MGVjODAxMDIzOWU0MDBmZTkwYWQ2YzkxMDdiND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmd1YXZhLTI3LjAuMS1qcmUuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk3MDc0MDMxfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=CHhp0-vNCxq1x2xuHXD95Fko8dSgGljsG38Iur73TlGtGF04olQd1S0i6slWQfyEdV6XQktwBV9MgUynVn6WcgBhJVK8TisHo9aMNLEwFHcTvSSV-KJourRvQFhGZXPnv8VhIWe8SGDkZ7tUGmw1JqtVn-PbjN6LrxBd1cpRlM~uGYSxfFZfnMhiujE911i8z-AVxvcKM30baNJUYzTcgPTSfiPKYdrvMkEo4Gvh1oa5vIqREIeYOzROdAFdjDycl9CWj2ftiyXgw8Sw-JgOBe8kTUoy5IRf~ji3TBEFyC-ORc~BBMiUZasgyIqlf59jg1IskOiO5AvYlo-poUoLQg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
11:33:03.510 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
11:33:03.511 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:33:03.511 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
11:33:03.511 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
11:33:03.511 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 7s
11:33:03.512 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
11:33:03.512 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
11:33:03.561 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
11:33:03.562 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
11:33:03.563 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.003 secs
11:33:03.567 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
11:33:03.567 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
11:33:03.567 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/Users/xxxxxx/Desktop/tools/cruise-control-master/.gradle/5.6.4/fileHashes)
11:33:03.568 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/Users/xxxxxxx/Desktop/tools/cruise-control-master/.gradle/5.6.4/fileHashes).
11:33:03.569 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (/Users/xxxxxxx/Desktop/tools/cruise-control-master/.gradle/vcs-1) was closed 0 times.
11:33:03.569 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS metadata (/Users/xxxxxx/Desktop/tools/cruise-control-master/.gradle/5.6.4/vcsMetadata-1) was closed 0 times.
11:33:03.584 [DEBUG] [org.gradle.cache.internal.VersionSpecificCacheCleanupAction] Processed version-specific caches at /Users/xxxxxxx/Desktop/tools/cruise-control-master/.gradle for cleanup in 0.013 secs
11:33:03.595 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
11:33:03.648 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@50ad4737
11:33:03.648 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 19: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
11:33:03.649 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Success[value=org.gradle.launcher.exec.BuildActionResult@7205765b] from daemon DaemonInfo{pid=36836, address=[c1f49564-2964-4a58-a514-f8ed120d0f7a port:55399, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Busy, lastBusy=1597073577898, context=DefaultDaemonContext[uid=db774d34-5891-4dfc-86da-fb59e58b839e,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home,daemonRegistryDir=/Users/XXXXXX/.gradle/daemon,pid=36836,idleTimeout=120000,priority=NORMAL,daemonOpts=-Xms512m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
11:33:03.649 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished

Could you please suggest a solution.

Thanks in Advance,
Atul

**Comment by efeg** [comment]
@atulrenapurkar The logs seem to indicate failure to download dependencies -- are you behind a firewall? Would you verify that you have an active internet connection to get the dependencies?

**Comment by efeg** [comment]
@atulrenapurkar Closing the issue -- feel free to reopen if that is not an issue with your internet connection.
