### ISSUE TITLE
The follower.replication.throttled.replicas written can be messed up if previous value was '*'

### ISSUE THREAD

**Issue by robinp-tw** [linkedin/cruise-control#1322]
In the `setThrottledReplicas` function (https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L182) we suspect that the joining of the old list and new list with commas can lead to a situation where, if the old value is a single '*' which is allowed, then the result is something like `follower.replication.throttled.replicas: "*,11:1,11:2....."` which is not a valid value.

Normally Kafka's helper would validate this, but due a bug (https://issues.apache.org/jira/browse/KAFKA-10460) it didn't catch this case.

**Comment by MatthewBerk** [comment]
Hello is a fix still needed for this issue?

Also is it just * you are concerned with or are there other characters also?

**Comment by Lincong** [comment]
> Hello, is a fix still needed for this issue?
> 
> Also is it just * you are concerned with or are there other characters also?

Hi Matt, I think a fix is still needed. According to the below Kafka ticket, the value must be either `*` or a list of `k:v pairs`. In other words, the value cannot be a list of `k:v pairs` + `*`.

https://issues.apache.org/jira/browse/KAFKA-10460

I created a PR to fix this issue. https://github.com/linkedin/cruise-control/pull/1381

Feel free to comment on it. Thanks!
