### ISSUE TITLE
Does the REST API have a health endpoint?

### ISSUE THREAD

**Issue by bluebob** [linkedin/cruise-control#1335]
Hopefully this is a simple question - I'm running the CC agent (not the reporter) on Kubernetes. Now I'd like to have a 'readiness probe' but that needs something like a "health" endpoint.
I tried using the raw "state" endpoint - but it looks like if the agent has just started (so it's still getting data) then the state endpoint is returning something Kubernetes sees as a failure.

**Comment by efeg** [comment]
@bluebob would `kafka_cluster_state` endpoint help? It should be ready to respond as soon as CC is up.

**Comment by bluebob** [comment]
Thanks - that's ideal (I've done some testing now)
