### ISSUE TITLE
`webserver.api.urlprefix` configuration invalid

### ISSUE THREAD

**Issue by claudio-benfatto** [linkedin/cruise-control#1336]
Hi,

## Problem description

I noticed that even though the `webserver.api.urlprefix` is documented and configurable, anything different from the default `/kafkacruisecontrol/*` is as a matter of fact producing an error, eg:

with the configuration:
```
webserver.api.urlprefix=/mycluster/kafkacruisecontrol/*
```
```
curl  http://cruisecontrol.example:9090/mycluster/kafkacruisecontrol/state
```
will result in:
```
unrecognized endpoint in request '/state'
* Connection #0 to host 10.231.3.123 left intact
Supported GET endpoints: [BOOTSTRAP, TRAIN, LOAD, PARTITION_LOAD, PROPOSALS, STATE, KAFKA_CLUSTER_STATE, USER_TASKS, REVIEW_BOARD]
```

I looked a bit into the code and it seems that the culprit for this behaviour is to be found in this code: https://github.com/linkedin/cruise-control/blob/5ed774eb5c64f6e57a6a001c1306c520170416c5/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServletUtils.java#L38-L39

and in the following validation attempt: https://github.com/linkedin/cruise-control/blob/fbc1b1dfac27768193d046ce852a7deaad7f7bd9/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/parameters/ParameterUtils.java#L179-L186

## Expected behaviour

I would expect this configuration to behave as documented

Thank you!

**Comment by Lincong** [comment]
Hi @claudio-benfatto, I just merged a PR that resolves this issue. Let me know if it works. Thanks!
