### ISSUE TITLE
Unable to find setting for Goal Violation detection supression

### ISSUE THREAD

**Issue by amaendeepm** [linkedin/cruise-control#1339]
My single broker (Confluent Kafka 6.0) is swamped with following message in log which I want to avoid/supress but cant find a way so far. Any help would be appreciated

WARN Skipped goal violation detection for goals [ReplicaPlacementGoal, RackAwareGoal, SequentialReplicaMovementGoal, ReplicaCapacityGoal, DiskCapacityGoal, NetworkInboundCapacityGoal, NetworkOutboundCapacityGoal, ReplicaDistributionGoal, DiskUsageDistributionGoal] because load completeness requirement were not met. (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)

**Comment by efeg** [comment]
Hi @amaendeepm 

> My single broker (Confluent Kafka 6.0) is swamped with following message in log ...

I assume these logs are not in the broker logs, but are in the Cruise Control logs. Would you please share the version of Cruise Control you are using?

**Comment by amaendeepm** [comment]
Was able to resolve with confluent support
