### ISSUE TITLE
How to ignore a sudden peak in metrics and not consider it as goal violation

### ISSUE THREAD

**Issue by KSI47** [linkedin/cruise-control#1344]
How can we use load monitor and anomaly detector configurations to ignore sudden variations in metrics (e.g: CPU utilization), because we don't want to consider peaks in short time period as a goal violation ?

**Comment by efeg** [comment]
@KSI47 We can achieve this by keeping a longer load history with more windows:
* Increase the value of `num.partition.metrics.windows`, and
* Increase the value of `partition.metrics.window.ms`,

As a relevant note, please also see the documentation on `metric.sampling.interval.ms` and `min.samples.per.partition.metrics.window` (see [Configurations](https://github.com/linkedin/cruise-control/wiki/Configurations))

The discussion in https://github.com/linkedin/cruise-control/issues/1149 would be helpful in understanding the impact of having more windows and/or larger window size.

**Comment by efeg** [comment]
@KSI47  Closing the issue -- please feel free to reopen if you have further questions.
