### ISSUE TITLE
Add a sensor to identify a cluster containing partitions with replication factor > number of racks

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1365]
To enhance the fault tolerance of clusters with insufficient number of racks to provide a full rack-awareness (i.e. each replica of each partition resides on a different rack), we added a new hard goal, called `RackAwareDistributionGoal` (see https://github.com/linkedin/cruise-control/pull/1345). This goal is a relaxed version of `RackAwareGoal`, and evenly distributes replicas over racks. Contrary to `RackAwareGoal`, if replicas of each partition can be evenly distributed across the racks, this goal lets placement of multiple replicas of a partition into a single rack. 

To help identification of clusters containing partitions with RF > number of racks, add a sensor that monitoring systems can alert on if needed.

**Comment by mgrubent** [comment]
I may be mistaken, but doesn't RF (or rather, the replica set) temporarily increase during partition movements?  
If so, would this sensor fire when the replica set temporarily increases?

**Comment by efeg** [comment]
@mgrubent Good point! This sensor can emit a special value to indicate that there is an ongoing execution; hence, the outcome is undecided.

**Comment by mgrubent** [comment]
I'm not sure what the downstream monitoring / alerting frameworks look like, but I imagine that the majority of them would need to re-implement the filter-out-ongoing-execution signal.

Is the envisioned `RF > number of racks` signal a boolean?

**Comment by efeg** [comment]
@mgrubent Other than the _special value_ (see https://github.com/linkedin/cruise-control/issues/1365#issuecomment-717438456), it would probably be similar to the sensor that signals whether the cluster has unfixable goals -- i.e. `0`: no unfixable goal, `1`: has unfixable goal.

I would be happy to discuss suggestions that intend to provide a universal solution applicable to all downstream monitoring / alerting frameworks.

**Comment by mgrubent** [comment]
For our own purposes, I think the boolean datatype (or its `0/1` integer representation) is sufficient.

I would prefer not to have to de-noise this sensor by comparison to whether there is an ongoing partition reassignment.

The ideal monitoring-ready sensor for me would be:
- `0`: No _static_ partitions have RF > the number of racks in the kafka cluster
- `1`: At least one _static_ partition has RF > the number of racks in the kafka cluster

Where a "static" partition is one for which there is not an ongoing partition reassignment.  
Ideally, this would include partition reassignments from non-`cruise-control` sources as well, but that may be infeasible to provide in kafka 2.4+
