### ISSUE TITLE
Migrate to Java 11

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1374]
With https://github.com/linkedin/cruise-control/issues/1262, Cruise Control rolled back from `JDK 11` to `JDK 8`. However, we found out that this bug was introduced by [Azul](https://www.azul.com/downloads/zulu-community) in `11.0.5` and they fixed it in `11.0.7`. Vanilla `OpenJDK 11` does not have this issue.

Hence, Cruise Control can safely migrate away from Java 8, whose support will end by early 2022.

**Comment by hinchliff** [comment]
Are there specific releases that are still on Java 8?

**Comment by efeg** [comment]
@hinchliff All versions on and after (1) `2.5.21` , (2) `2.4.30`, and (3) `2.0.137` are in `Java 11`.
