### ISSUE TITLE
[cloud] scaling kafka clusters with CC

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#1389]
While CC is pretty helpful to (re-)balance the kafka cluster to meet several goals. Sometimes brokers go down/taken down permanently. I would need some ideas on how CC can be used to scale (up/down) the clusters (add/remove brokers). 

Here, there would be an integration needed with external cloud providers api (azure/aws/gcp, etc) for sure. Assuming this can be taken care of.

**Comment by efeg** [comment]
@nareshv Just a quick note -- this is indeed in our radar.
We will provide more updates soon.

**Comment by efeg** [comment]
@nareshv Cruise Control will support _right-sizing_ Kafka clusters.
As part of this process, we will work on the following issues: https://github.com/linkedin/cruise-control/issues/1434, https://github.com/linkedin/cruise-control/issues/1435, https://github.com/linkedin/cruise-control/issues/1436.

Closing this issue -- please feel free to comment on the relevant issue for further discussion.
