### ISSUE TITLE
"asJavaList()" was no longer used in Scala 2.11 and was deprecated in 2.10

### ISSUE THREAD

**Issue by jadylc** [linkedin/cruise-control#14]
/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/BrokerFailureDetector.java:120: error: cannot find symbol
 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler]     return JavaConversions.asJavaList(_zkUtils.getAllBrokersInCluster())

**Comment by jadylc** [comment]
BUILD SUCCESSFUL with seqAsJavaList()
But still can't connect Bootstarp broker. So sad

**Comment by becketqin** [comment]
@jadylc #26 has been checked in to resolve the issue. What error did you see when trying to connect to the broker?
