### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException exception when kv.kength=1

### ISSUE THREAD

**Issue by jingxuancao** [linkedin/cruise-control#1404]
https://github.com/linkedin/cruise-control/blob/6d7978e8a2d9bcfd602ad7e6cedbdd9e7b2fcd6e/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java#L219

**Comment by efeg** [comment]
Hi @jingxuancao, Can you share the version of Cruise Control and Kafka are you running?

**Comment by jingxuancao** [comment]
Hi @efeg I'm using Kafka version 1.1.1 and Cruise Control 2.0.72

**Comment by efeg** [comment]
Closing this issue as it has been resolved in Cruise Control version [2.0.129](https://github.com/linkedin/cruise-control/releases/tag/2.0.129) -- see https://github.com/linkedin/cruise-control/issues/1296#issuecomment-694497440.
