### ISSUE TITLE
can cc alone support static resources ?

### ISSUE THREAD

**Issue by Justinwins** [linkedin/cruise-control#1411]
I noticed that there are some servlet configurations for cc, like :    webserver.http.address ;
yet ,cannot find details about static delpoyment  .

Then ,i went for cc_ui project in github maintained by Linkedin as well,
But cc_ui just asks users to delploy  static resources in Nginx or Apache.

really  confused.

**Comment by nareshv** [comment]
these are primarily targeted for cc-ui as it provides an admin interface to manage cruise-control.

**Comment by efeg** [comment]
Closing this issue. As indicated by Naresh, these configs are targeted for https://github.com/linkedin/cruise-control-ui.
