### ISSUE TITLE
ACLs

### ISSUE THREAD

**Issue by dblooman** [linkedin/cruise-control#1413]
Are there a list of required topics and permissions for actions on resources in kafka that CC will use?

**Comment by efeg** [comment]
Hi @dblooman 
If you are using the default configurations, CC creates 3 internal topics that needs the following permissions:
* `__CruiseControlMetrics` (see `metric.reporter.topic` config) -- CC requires read access
* `__KafkaCruiseControlPartitionMetricSamples` (see `partition.metric.sample.store.topic`) -- CC requires read/write access
* `__KafkaCruiseControlModelTrainingSamples` (see `broker.metric.sample.store.topic`) -- CC requires read/write access

If you configure `maintenance.event.reader.class` to use `MaintenanceEventTopicReader` class, then
* `__MaintenanceEvent` (see `maintenance.event.topic`) -- CC requires read access.

Hope it helps!

**Comment by dblooman** [comment]
Cool, thanks

**Comment by yasminhaque** [comment]
I've got some follow up questions based on this thread. 

Are these the same ACLs used if we are using ```PrometheusMetricSampler```?

It seems like from the source code that if we are using Prometheus to sample then ```__CruiseControlMetrics``` does not get written to - is this correct? Also is there any documentation specifically around how Cruise Control works using the Prometheus sampler as opposed to the default Cruise Control one?

**Comment by efeg** [comment]
Hi @yasminhaque 

> It seems like from the source code that if we are using Prometheus to sample then __CruiseControlMetrics does not get written to - is this correct?

That is correct. `PrometheusMetricSampler` users do not need ACLs for `__CruiseControlMetrics`. The response above is relevant only _"If you are using the default configurations"_.

> Also is there any documentation specifically around how Cruise Control works using the Prometheus sampler as opposed to the default Cruise Control one?

The PrometheusMetricSampler can be configured as the metric sampler of Cruise Control using `metric.sampler.class` (see [Load Monitor Configurations](https://github.com/linkedin/cruise-control/wiki/Configurations#load-monitor-configurations)). The [configuration page for PrometheusMetricSampler](https://github.com/linkedin/cruise-control/wiki/Configurations#prometheusmetricsampler-configurations) lists the relevant configs to further customize for `PrometheusMetricSampler`.
