### ISSUE TITLE
Replace AdminZkClient with AdminClient

### ISSUE THREAD

**Issue by Lincong** [linkedin/cruise-control#1415]
Motivations:

1. `AdminZkClient` gets information from Zookeeper which will be removed from Kafka as a dependency ([KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum)).

2. Java doc of `AdminZkClient` class says `This is an internal class and no compatibility guarantees are provided, see org.apache.kafka.clients.admin.AdminClient for publicly supported APIs.`

**Comment by jakehell** [comment]
@Lincong  can I take this one on? Or did you mean to assign it to yourself?

**Comment by Lincong** [comment]
> @Lincong can I take this one on? Or did you mean to assign it to yourself?

Hi Jacob, I am glad that you want to take on this issue, and of course, you can. Just want to share some of my opinions regarding the implementation to resolve this issue.

1. In the codebase, find all places where `AdminZkClient` is used and replace them all since the goal is to completely migrate to `AdminClient`.

2. Note that there is an API-level semantics difference in `AdminZkClient` vs `AdminClient` regarding topic config changes. In `AdminClient`, the topic config change is incremental (diff-based) whereas `AdminZkClient` overrides topic config.

Let me know if you have any questions or have any things you want to discuss with me while you are implementing it. Thanks!

**Comment by jakehell** [comment]
Will do. Thank you for the info.

**Comment by tomncooper** [comment]
@jacobhell Did you manage to complete this work?

**Comment by jacobhell** [comment]
@tomncooper no, it can be reassigned. Apologies.

**Comment by tomncooper** [comment]
I would be happy to give this issue a try, if no one else is working on it currently?

**Comment by efeg** [comment]
Thanks for working on this @tomncooper -- I reassigned the issue to you.

**Comment by efeg** [comment]
@tomncooper After https://github.com/linkedin/cruise-control/pull/1644 is merged, the only key remaining item will be the use of `AdminZkClient` for replication throttle. Can I assume that you will be working on that part?

**Comment by tomncooper** [comment]
Hi @efeg, yes I will take that on.

**Comment by tmcgrath** [comment]
Question to confirm my understanding of this work.  Once complete, this will remove the need to configure ZK access.  If so, great!

**Comment by erikgb** [comment]
This issue seems to be fixed, ref. https://github.com/linkedin/cruise-control/wiki/Run-without-ZooKeeper. Close issue?
