### ISSUE TITLE
Please add a release tag

### ISSUE THREAD

**Issue by fmunteanu** [linkedin/cruise-control#142]
Please add a release tag. It will be easier to provide links to binary files, as well as release notes describing your changes. Thank you.

**Comment by fmunteanu** [comment]
@becketqin @efeg, I was wondering if you could look into this when you have a chance, much appreciated.

**Comment by becketqin** [comment]
@fmunteanu Thanks for firing this issue. Very valid point. We will add the versioning to the project shortly.

**Comment by jocelyndrean** [comment]
A release tag would be perfect <3

**Comment by fmunteanu** [comment]
@becketqin @efeg any updated on this?

**Comment by fmunteanu** [comment]
@becketqin @efeg I dare you to have a release tagged in one week. 😃

**Comment by becketqin** [comment]
@fmunteanu Really sorry for late response. We were waiting for the LinkedIn official jfrog repository to be created so we can put the artifact there. It is now created, we will add release tag and publish artifacts in shortly.

**Comment by efeg** [comment]
The patch is available at PRhttps://github.com/linkedin/cruise-control/pull/211

**Comment by fmunteanu** [comment]
@efeg @becketqin any updates on the versioning?

**Comment by efeg** [comment]
@fmunteanu @jocelyndrean 
Sorry for the delay! We have our first release available at:
https://github.com/linkedin/cruise-control/releases
