### ISSUE TITLE
Stop execution before shutting down Cruise Control

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1425]
If Cruise Control (CC) is requested to be shutdown when it has an ongoing execution, it does not stop/cancel the ongoing execution before it shuts down. As a result, the next time CC come back up (e.g. due to a deployment of a new CC version), the new CC instance may reject starting a new execution with an exception message such as the following:

```
Cannot execute new proposals while there are ongoing partition reassignments initiated by external agent.
```

This leads to (1) confusion on what the external agent could be and (2) inability to start a new execution until the ongoing execution completes.

**Proposal**: With Kafka 2.4, the relevant CC versions use the Admin client based replica reassignment API. This allows CC to quickly stop / cancel ongoing replica reassignments. Hence, before shutting down, if CC has an ongoing execution, it should stop the ongoing execution.

`Reminder`: The PR should be created against `migrate_to_kafka_2_4` branch.

**Comment by zornhsu** [comment]
First draft committed to https://github.com/zornhsu/cruise-control/commit/4b2a80a534f4fa5c2dcdd7a7437e77ee5c75f992. Next step: manual testing to see this works as expected.

**Comment by zornhsu** [comment]
Second draft: Added binary semaphore to unsure stop ongoing execution complete before full shutdown. https://github.com/zornhsu/cruise-control/commit/f745b5d19ac82da4670f22a2c2bc9780c58a4e0c
