### ISSUE TITLE
Report ongoing replica reassignments started by an external agent

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1426]
If there is an ongoing execution not started by the current Cruise Control instance (e.g. started by an earlier CC deployment, but the execution is still ongoing), then Cruise Control would say that there are partition movements started by an external source, but it does not show what these partition movements are.

Ideally, if the ongoing reassignment is due to replica moves, Cruise Control should
1. Return the set of partitions that are being reassigned in response to the user requests, and
2. Log the the set of partitions that are being reassigned.

**Comment by zornhsu** [comment]
I just committed source code change in https://github.com/zornhsu/cruise-control/commit/210c1a563c5719854d76cabc14947696c6bfa278
I will then look at the tests to see if any modification is needed.
