### ISSUE TITLE
Getting "Connection to node -1 could not be established. Broker may not be available." on all brokers

### ISSUE THREAD

**Issue by jmarkan** [linkedin/cruise-control#143]
Hi,
I'm new to setting up CruiseControl. I have set it up against an 8 broker kafka cluster and followed the steps you guys documented to set the cruise control. However, as soon as I started my brokers, I started seeing these logs constantly on all of them:

[2018-02-27 19:44:34,952] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

Previously I did edit the config/capacity.json file to include all 8 brokers (ofcourse with respective IDs), so not sure from where it's picking up broker -1.

Could someone please help?

Thanks a lot in advance.

**Comment by chandradeepak** [comment]
i got the same . Do you have SSL enabled ? By default cruise control connects to localhost:9092 on PLAINTEXT. if it cant connect then you get these errors. 

if so you need to give the following parameters for ssl to make it work in server.properties of kafka nodes. 

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
security.protocol=SSL
cruise.control.metrics.reporter.security.protocol=SSL
cruise.control.metrics.reporter.ssl.truststore.location=truststorelocation
cruise.control.metrics.reporter.ssl.truststore.password=password
cruise.control.metrics.reporter.bootstrap.servers=kafkaaddrs


once you give these it should work if you had SSL enabled betweeen brokers. 

If that is not the case then you are not able to write to your localkafka at port 9092. you have to configure that correctly by providing the above properties

**Comment by jmarkan** [comment]
Thanks and 👍 @chandradeepak for your reply. Unfortunately no, we don't have SSL enabled on Kafka brokers. Will it be a blocker for us to run cruise control? 

We're running cruise control on a separate machine which isn't a Kafka broker. I also mentioned bootstrap servers in config/cruisecontrol.properties, so I expecte it to connect to those brokers:9092. Am I wrong in thinking that?

**Comment by chandradeepak** [comment]
1) did you do that part where in read me they specified to copy the jar 
Copy ./cruise-control-metrics-reporter/build/libs/cruise-control-metrics-reporter.jar in libs.

Cruise control right the metric values to a kafka topic. so it should be able to talk to itself . For that you need to set the normal kafka client properties also in server.properties .

if nothing is given for cruise.control.metrics.reporter.bootstrap.servers it writes to itself on localhost:9092 which is default in PLAINTEXT protocol .

see the port on which your kafka listens is indeed 9092. 
also some times localhost wont be exposed outside for writing. it would be exposed as advertilised.listeners . in that case you might have to give the
cruise.control.metrics.reporter.bootstrap.servers as that  with out PLAINTEXT:// in it . 
 
Also check if 

 is auto.create.topics.enable=true 
 is the topic __CruiseControlMetrics created

these are after the connection is successful . 

Also the cruisse control can be run outside kafka cluster which is what i am also doing . In that you just have to make sure connectivity is there between that nodes to kafka cluster  .


try these and see if that works ?

**Comment by jmarkan** [comment]
@chandradeepak 
Yep, I did copy the jar like its documented in the readme. I just added cruise.control.metrics.reporter.bootstrap.servers=<broker IP>:9092 on all brokers and did a rolling restart, and then boom - the errors went away and now I see normal output on the GET /kafkacruisecontrol/state

{MonitorState: {state: RUNNING(4.800% trained), NumValidWindows: (0/1) (0.000%), NumValidPartitions: 3/738 (0.407%), flawedPartitions: 22}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: false, ReadyGoals: [ReplicaDistributionGoal, TopicReplicaDistributionGoal, ReplicaCapacityGoal]}}

Thanks a lot for pointing me in a correct direction, +1 for that.

Yep, auto.create.topics.enable=true on all brokers and the topic __CruiseControlMetrics is created.

As of now I'm just waiting for it to be 100% trained.

Last question though - is it normal for it to take a lot many hours to train itself initially?

**Comment by chandradeepak** [comment]
@jmarkan , i am not sure about that .  Mine is also not done .

**Comment by jmarkan** [comment]
@chandradeepak oh ok. I'll update this issue once mine gets done. Though I tried to tune some properties in the cruise control config and restarted it this morning. It went from 0 to 20% in about 20ish mins and hasn't moved since.

**Comment by efeg** [comment]
@jmarkan Here are the answers to some of your questions:
1. It is okay to run Cruise Control on a separate machine which isn't a Kafka broker.
2. Cruise Control supports both SSL and Plaintext -- as long as they are configured correctly, you can use either.
3. This warning `WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)` indicates that the Cruise Control metrics reporter is up and it is trying to communicate with the broker(s) defined in `cruise.control.metrics.reporter.bootstrap.servers`, but those broker(s) are currently down.
Note that for each broker, there is also a metrics reporter running locally with that broker.
If `cruise.control.metrics.reporter.bootstrap.servers` is not specified in `server.properties` of the Kafka node, the metrics reporter for that node will try to use `localhost:9092` by default.
If the bootstrap server is just the localhost, this warning message will be repeatedly generated until the local broker is up, and the metrics reporter can start communicating with it. When this communication starts, this warning message will disappear. Hence, in this case you can ignore this message. I would recommend listing multiple brokers in `cruise.control.metrics.reporter.bootstrap.servers` to minimize these warnings.

@jmarkan @chandradeepak regarding the training issue, can you confirm that the `__CruiseControlMetrics` topic is generated and metrics reporter is producing data to it -- i.e. the topic is growing in size? Does cruise control log show any error / warning messages? Does Kafka log show any errors / warnings?

**Comment by chandradeepak** [comment]
@efeg  In my case we had little data that was coming to cluster . But i have the __CruiseControlMetrics was created and had some data in it .  It was not updating much 

all of them are this size and not growing . 
 10485756 Mar  1 22:08 00000000000000000000.timeindex
10485760 Mar  1 22:08 00000000000000000000.index
10186408 Mar  1 22:09 00000000000000000000.log

do we need the cluster to actively get data for cruise control to work ?

**Comment by efeg** [comment]
@chandradeepak 
It is not required for the cluster to actively get data for cruise control to work.

My guess is that since `__CruiseControlMetrics ` shows that metrics collector was able to collect some data before, and logs don't indicate a problem, if you check the `kafkacruisecontrol/state`, the current `MonitorState` should be `PAUSED`. Is my assumption correct?

**Comment by chandradeepak** [comment]
@efeg yeah it went to PAUSED state.

**Comment by jmarkan** [comment]
@efeg In my case, the training pct get to 20% pretty quickly and then gets stuck. 
![image](https://user-images.githubusercontent.com/14930180/36879025-b329e650-1d8f-11e8-82e5-14d2b7c47300.png)

**Comment by efeg** [comment]
@jmarkan The `RUNNING` state indicates that the metrics reporter continues data sampling. However, `monitoringCoveragePct` of 0.039% seems quite low. The other goals are not ready because of this low value. You can check the model completeness requirements of all goals via `/kafkacruisecontrol/state?verbose=true`. `monitoringCoveragePct` should be larger than `minMonitoredPartitionPercentage` for the remaining goals to be ready. 
The following config changes in `config/cruisecontrol.properties` might help in your case:
1. Increasing the `num.load.snapshots` from `1` to `10`. (This collects 10 windows rather than 1).
2. Increasing the `load.snapshot.window.ms`  from `300000` to `600000`.
3. Increasing the `metric.sampling.interval.ms` from `120000` to `240000`

Also, I suspect that there might be some logs in Kafka logs indicating some warning / error regarding metrics reporter sampling the Kafka raw metrics on the broker.

Training is relevant only if you opt-in to use the linear regression model to estimate the CPU utilization of partitions. Hence, unless you explicitly set the `use.linear.regression.model=true` (default: false), `trainingPct` does not really have any impact.

**Comment by jmarkan** [comment]
Thanks a lot @efeg for your inputs. I'll do the suggested config changes and will let you know the feedback.

**Comment by jmarkan** [comment]
Hey @efeg So I made the suggested config changes and restarted cruise control. Well, the performance this time looks better than before in terms of more monitored windows (that was expected after we increased num.load.snapshots from 1 to 10 like you suggested). However, training pct is still stuck at 20%. Although I did see the number of readyGoals to be more than 3 goals a while ago and then it went back to 3. I think its because of the last window's monitored % being 0.9897959183673469, satisfying the set config of 0.95. But now its back to 0.007%. Is this expected? Also, do you suggest to let this run over the weekend and see if it gets trained from 20% to 100%?

Here are the logs that keep appearing in cruise control:

`[2018-03-02 15:55:21,806] ERROR Uncaught exception in anomaly handler. (com.linkedin.kafka.cruisecontrol.detector.AnomalyDetector)
java.lang.IllegalStateException: Cannot get proposal because model completeness is not met.
	at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:235)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.getOptimizationProposals(KafkaCruiseControl.java:321)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.getOptimizationProposals(KafkaCruiseControl.java:363)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.rebalance(KafkaCruiseControl.java:198)
	at com.linkedin.kafka.cruisecontrol.detector.GoalViolations.fix(GoalViolations.java:38)
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetector$AnomalyHandlerTask.fixAnomaly(AnomalyDetector.java:199)
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetector$AnomalyHandlerTask.run(AnomalyDetector.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Here is the screenshot of the /kafkacruisecontrol/state:

![image](https://user-images.githubusercontent.com/14930180/36918164-f012b028-1e26-11e8-81c8-2b56f7eb5026.png)

**Comment by efeg** [comment]
Unless you explicitly set the `use.linear.regression.model=true` (default: false), `trainingPct` is irrelevant. Actually due to the confusion it causes, this should probably be removed from the state endpoint, or at least should only be visible when the CC is configured to use linear regression.

Such a significant drop in `monitoringCoveragePct` is not expected -- ideally it should be close to 100% all the time. In Kafka logs (not in CC logs), are there any error / warning messages related to metrics reporter being unable to collect data?

**Comment by jmarkan** [comment]
In Kafka logs, I didn't see any errors or warning. However, I went ahead and did a rolling bounce of the cluster. Once I did that, apart from the below warning and info message, I really dont see any other warning or error:

`[2018-03-03 02:47:01,724] WARN retention.ms for topic __KafkaCruiseControlModelTrainingSamples is set to 12000000. It is smaller than message.timestamp.difference.max.ms's value 9223372036854775807. This may result in frequent log rolling. (kafka.server.TopicConfigHandler)`

`[2018-03-03 02:49:35,405] INFO Updated PartitionLeaderEpoch. New: {epoch:14, offset:155324}, Current: {epoch:-1, offset-1} for Partition: __consumer_offsets-16. Cache now contains 0 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-03-03 02:50:30,894] INFO Updated PartitionLeaderEpoch. New: {epoch:16, offset:30646}, Current: {epoch:15, offset30612} for Partition: __KafkaCruiseControlPartitionMetricSamples-1. Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-03-03 02:50:30,897] INFO Updated PartitionLeaderEpoch. New: {epoch:16, offset:30646}, Current: {epoch:15, offset30612} for Partition: __KafkaCruiseControlPartitionMetricSamples-25. Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)
[2018-03-03 02:50:30,899] INFO Updated PartitionLeaderEpoch. New: {epoch:16, offset:30646}, Current: {epoch:15, offset30612} for Partition: __KafkaCruiseControlPartitionMetricSamples-9. Cache now contains 1 entries. (kafka.server.epoch.LeaderEpochFileCache)`

Another change I did was that in CC config, I changed "bootstrap.servers=" to point to individual broker's IP:9092 instead of the ELB kafka endpoint. I restarted CC after this. Here is the current state/: 

`{MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (0/10) (0.000%), NumValidPartitions: 0/784 (0.000%), flawedPartitions: 30}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: false, ReadyGoals: [ReplicaDistributionGoal, TopicReplicaDistributionGoal, ReplicaCapacityGoal]}}

Monitored Windows [Window End_Time=Data_Completeness]:
{1520046600000=0.510%, 1520046000000=1.403%, 1520044800000=100.000%, 1520044200000=0.000%, 1520043600000=0.000%, 1520041200000=0.000%, 1520039400000=0.000%, 1520035200000=0.000%, 1520034600000=0.000%, 1520029800000=0.000%}

Goal Readiness:
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
                                PotentialNwOutGoal, (requiredNumWindows=10, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.950, includedAllTopics=true), NotReady
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=10, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=10, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                          CpuUsageDistributionGoal, (requiredNumWindows=10, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                     LeaderBytesInDistributionGoal, (requiredNumWindows=10, minMonitoredPartitionPercentage=0.950, includedAllTopics=false), NotReady
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready`

**Comment by jmarkan** [comment]
@efeg or @becketqin any ideas?^^

**Comment by efeg** [comment]
Closing the old issue.
