### ISSUE TITLE
Remove REPLICA_ADDITION and REPLICA_DELETION

### ISSUE THREAD

**Issue by Lincong** [linkedin/cruise-control#1431]
`REPLICA_ADDITION` and `REPLICA_ADDITION` are not and will not be supported. So, we need to remove it completely from the codebase.

**Comment by agarwalsarthak121** [comment]
Hi, 
I am new to open source contributions.
Can I take up this ?

**Comment by Lincong** [comment]
Hi @agarwalsarthak121 , yes, absolutely, feel free to assign this issue to yourself and create a PR when you are ready! Thanks!

**Comment by agarwalsarthak121** [comment]
Already created a pull request.
