### ISSUE TITLE
Incorrect variable? (in PercentileMetricAnomalyFinderConfig)

### ISSUE THREAD

**Issue by runom** [linkedin/cruise-control#1438]
Hi, 
I have a question.

I want to use metric anomaly detection, so I'm reading the relevant code.

https://github.com/linkedin/cruise-control/blob/1bff713ebbfb449b0f7a0425663d6b7c93576a13/cruise-control-core/src/main/java/com/linkedin/cruisecontrol/detector/metricanomaly/PercentileMetricAnomalyFinderConfig.java#L65-L70

At line 70, is `METRIC_ANOMALY_PERCENTILE_LOWER_THRESHOLD_DOC` correct?
I think it should be used `METRIC_ANOMALY_LOWER_MARGIN_DOC` instead.

**Comment by efeg** [comment]
@runom Thanks for reporting this issue!
This is absolutely a bug -- I will create a PR to fix it.
-- Please let us know if you would encounter other issues or have questions.

**Comment by runom** [comment]
I've confirmed it. Thanks!
