### ISSUE TITLE
Bump jetty dependency to 9.4.35

### ISSUE THREAD

**Issue by samuel-hawker** [linkedin/cruise-control#1439]
CVE raised for versions<=9.4.33 in relation to https://github.com/advisories/GHSA-86wm-rrjm-8wh8
I propose the version be bumped to stay up to date and avoid risks of data injection.
Happy to do this work myself.

**Comment by efeg** [comment]
@samuel-hawker Thanks for reporting this issue!
I created a PR to update stale dependencies, including this one.
