### ISSUE TITLE
How to speed up rebalance executor task?

### ISSUE THREAD

**Issue by qz-fordham** [linkedin/cruise-control#1440]
Hi,

I executed a rebalance on 6 hard goals + disk + replica goal, which need to move about 25K partitions and 6 TB data. A rough estimation after a 2-hour execution, moving speed is at about 180 GB/hr and 1150 partitions/hr. I was wondering if there is any way to speed this up or what's the bottleneck of this rebalance process? 

Our cluster has a read & write speed of 200-300 MB/s (720-1080 GB/hr), the rebalance speed is obviously slower than the hardware bottle neck.

Thank you in advance.

**Comment by efeg** [comment]
@qz-fordham 

I assume your CC instance is not configured to use byte-based replication throttling -- i.e. not used by default. Following manual configs may help speeding up a rebalance:
1. Increase the value of `num.concurrent.partition.movements.per.broker`
2. Increase the value of `max.num.cluster.movements`
3. Increase the value of `num.concurrent.intra.broker.partition.movements` (relevant to JBOD Kafka clusters)
4. Decrease the value of `execution.progress.check.interval.ms`

Source: https://github.com/linkedin/cruise-control/wiki/Configurations#executor-configurations

* That being said, a high rebalance speed tends to yield metadata pressure on the cluster. Thus I would recommend you to enable concurrency adjuster (i.e. `concurrency.adjuster.enabled=true`), which automatically adjusts the speed of execution to ensure that the cluster is not overloaded as a side effect of the rebalance. Please see `concurrency.adjuster.*` configs for more detail ([wiki](https://github.com/linkedin/cruise-control/wiki/Configurations#executor-configurations))

**Comment by qz-fordham** [comment]
@efeg Thanks for the tips. 

A follow up question, when you say 
> your CC instance is not configured to use byte-based replication throttling -- i.e. not used by default

what's the correct way to enable **byte-based replication throttling**? 
Is it simply following the 4 points you mentioned, or there is a different config I need to enable? Unfortunately, I couldn't find anything related to these keywords (byte-based, throttling) from the config documentation.

**Comment by efeg** [comment]
@qz-fordham byte-based throttling (this is based on [KIP-73 Replication Quotas](https://cwiki.apache.org/confluence/display/KAFKA/KIP-73+Replication+Quotas)) can be enabled either (1) via `default.replication.throttle` config (see [executor-configurations](https://github.com/linkedin/cruise-control/wiki/Configurations#executor-configurations)) or dynamically via (2) `replication_throttle=[bytes_per_second]` parameter of goal-based execution requests (e.g. rebalance, add/remove/demote brokers) (see [REST API](https://github.com/linkedin/cruise-control/wiki/REST-APIs)).

**Comment by efeg** [comment]
@qz-fordham I assume this issue is resolved -- please feel free to reopen if you have followup questions.
