### ISSUE TITLE
EXECUTION_TASK_FUTURE_ERROR_VERIFICATION_TIMEOUT_MS is not necessary

### ISSUE THREAD

**Issue by Lincong** [linkedin/cruise-control#1449]
In CC 2.4, the `processAlterPartitionReassignmentsResult` method waits on a collection of futures to get results of the partition reassignment request of a set of topic partitions. This method waits on futures with a timeout hard-coded as `EXECUTION_TASK_FUTURE_ERROR_VERIFICATION_TIMEOUT_MS`. However, this timeout is not necessary and should be removed.

Firstly, let's clarify the behavior of the `KafkaAdminClient` and `KafkaController` regarding how the `alterPartitionReassignments` request was sent and processed.

- **Behavior of the KafkaAdminClient**
   1. The [`alterPartitionReassignments`](https://github.com/apache/kafka/blob/3ebd32b2a563440645de45ecb578d8a8dccbee95/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L3519) method sends the request to a Kafka broker which may forward the request to the active Kafka controller if it itself is not the controller. A set of futures are created and each future represents a waiting state for each topic partition which has an ongoing partition reassignment.
   2. This [`handleResponse`](https://github.com/apache/kafka/blob/3ebd32b2a563440645de45ecb578d8a8dccbee95/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L3585) method receives a response from the Kafka controller and this response **must** contain results to all topic partitions' reassignment execution. Otherwise, an exception gets thrown ([code](https://github.com/apache/kafka/blob/3ebd32b2a563440645de45ecb578d8a8dccbee95/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L3612)). Then this method completes all futures either with the exception received from the Kafka controller or successfully with no error/exception.
   3. If the Kafka server does not respond with any result after some timeout ([code](https://github.com/apache/kafka/blob/3ebd32b2a563440645de45ecb578d8a8dccbee95/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java#L1293)). This timeout exception is used to complete all futures and it is defined by [`request.timeout.ms`](REQUEST_TIMEOUT_MS_CONFIG).

- **Behavior of the KafkaController**
   After receiving the request, the Kafka controller tries to reassign replicas for each topic partition in the request. When all topic partitions have been handled, it returns a map from the topic partition to its replica reassignment result. ([code](https://github.com/apache/kafka/blob/4e7c789118fed28ee99275e3e84a626fe912c79a/core/src/main/scala/kafka/controller/KafkaController.scala#L816)). Then the controller sends by this map of results for all topic partitions back to the client to complete the request ([code](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/controller/KafkaController.scala#L1815))

**It is important to note 2 things:**
1. All futures are always completed together since the controller always processes all topic partition reassignments and then replies with one response or the admin client times out all requested topic partition reassignments in the request.
2. There is **only one** timeout that could happen. That is when the admin client has not heard any response back from the Kafka server for an excessive amount of time.

**Therefore, I propose the following changes.**
1. Remove `EXECUTION_TASK_FUTURE_ERROR_VERIFICATION_TIMEOUT_MS` (future level timeout) and let users specify the admin client level request timeout explicitly.
2. Let the `processAlterPartitionReassignmentsResult` method throws the `org.apache.kafka.common.errors.TimeoutException` explicitly and make the caller handles this exception. Since this timeout exception is due to the Kafka server not responding to the admin client request, it might indicate Kafka server unavailability in some degrees. This method should not silently swallow this exception and move on as if nothing happened. Instead, it should notify its caller since the whole executor component (or even the whole CC instance) needs to make a decision regarding how to handle this situation (unavailable or extremely slow Kafka server/controller), fail? re-try? etc

**Comment by efeg** [comment]
Thanks for the detailed analysis! Proposal sounds good to me -- i.e. 
1. Remove `EXECUTION_TASK_FUTURE_ERROR_VERIFICATION_TIMEOUT_MS` (future level timeout)
2. Let users specify the admin client level request timeout explicitly -- i.e. make it configurable.
3. Let the `processAlterPartitionReassignmentsResult` method throw the `org.apache.kafka.common.errors.TimeoutException` explicitly. The relevant exception message should ideally indicate the user how to handle the issue -- i.e. e.g. increase the value of timeout config introduced in step-2.
