### ISSUE TITLE
Close the session in CC client once the response is received

### ISSUE THREAD

**Issue by malikmanisha** [linkedin/cruise-control#1464]
Today in CC client we create a session for a given request. But the session is never closed. Closing this session will help to free up CC resources.

**Comment by mgrubent** [comment]
@malikmanisha I think the session is closed once the request completes, usually in 10 seconds or less.

Of course, the current implementation of `cruise-control-client` is to _renew_ the session unless the response that it gets is final, so there can be ~minutes of sequential 10-second sessions from a single client.

Is this issue that these sessions are monotonically increasing on the `cruise-control` instance, or that there are too many open sessions at one time?

I suspect that the signature of `CruiseControlResponder.retrieve_response` is insufficient to accommodate interrupting the session renewal.  
I would suggest that there should be a new method created that allows the caller to specify the max number of times to renew the session upon receiving non-final responses.
`CruiseControlResponder.retrieve_response` would then be refactored to call the new method with some value that indicates no max; maybe `None`, and most of the existing `CruiseControlResponder.retrieve_response` code would move into the new method (with, of course, a new check to return a non-final response if it's out of retries).
