### ISSUE TITLE
What is the THROTTLE_REMOVED_BROKER_PARAM's value?

### ISSUE THREAD

**Issue by huoarter** [linkedin/cruise-control#1465]
When kafka broker is about to  run  a balance task, I see the param: Throttle Removed Broker, Throttle Removed Broker? Is The throttle value of kafka-reassign-partitions --throttle ?

**Comment by efeg** [comment]
@huoarter This is different from the throttle value of `kafka-reassign-partitions --throttle`.

When there is an ongoing replica reassignment started by CC (e.g. via `rebalance`, `remove_broker`, `add_broker`), to throttle the execution speed, CC uses a configurable limit on the number of replicas that are concurrently moving in or out of any broker (see `num.concurrent.partition.movements.per.broker` in https://github.com/linkedin/cruise-control/wiki/Configurations#executor-configurations).

In case of a broker removal operation, removed alive brokers would have the majority of replicas for replica reassignments; hence, they would be the bottleneck for the overall replica reassignment concurrency.

`throttle_removed_broker` is a boolean parameter that allows CC to skip this per-broker concurrency limit for brokers that are being removed (default: `true`).

Hope it helps!
