### ISSUE TITLE
Cruise Control is not refreshing partition leader and replicas during and after partition migration task

### ISSUE THREAD

**Issue by bpux** [linkedin/cruise-control#1466]
I triggered 'remove broker' task to move partitions from existing brokers to other brokers. During the execution(like a day or two), I think some partitions are created and moved to the 'remove' brokers. 
What I found out is, after the operation is completed, CC still doesn't have the correct partition count of brokers, until.. I restart cruise-control.

is it a known issue or something i have wrong config? thanks!

**Comment by efeg** [comment]
@bpux Sorry for the late response!
Do you still have this issue? If so, could you share more details including (1) version of CC, (2) logs showing the execution, (3) the response of `kafka_cluster_state` endpoint?

**Comment by efeg** [comment]
@bpux Closing this issue -- feel free to reopen with the requested details above if you still have this issue.
