### ISSUE TITLE
Enhance Concurrency Adjuster to take Number of AtMinISR partitions w/o offline replicas into account

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1467]
Cruise Control's Concurrency Adjuster automatically sets up the inter-broker replica reassignment and leadership concurrency for executions (see https://github.com/linkedin/cruise-control/issues/1288 and https://github.com/linkedin/cruise-control/issues/1298).

The current automation is based on a feedback loop that uses selected broker metrics -- i.e. it uses the relevant broker metrics to decide whether to increase, decrease, or maintain the current pace of reassignment. However, we observed that under certain cases while broker metrics are within an acceptable range, the cluster might still have UnderMinISR partitions. This makes such partitions read-only for partitions configured with _acks=all_ -- i.e. consumers can get data from them, but such producers cannot produce to them.

Take the number of AtMinISR partitions w/o offline replicas into account while making decisions to increase, decrease, or maintain the current pace of reassignment -- e.g. if there are such partitions, recommend decreasing the concurrency multiplicatively.

**Comment by indrajeetkm** [comment]
I will take this up
