### ISSUE TITLE
Cruise Control Unusable if __CruiseControlMetrics is Offline

### ISSUE THREAD

**Issue by mhaseebmlk** [linkedin/cruise-control#1472]
I was recently migrating data from one Kafka cluster to another in order to remove the older cluster. I have been following the recommended way of doing this as mentioned in https://github.com/linkedin/cruise-control/issues/593#issuecomment-475116287 by @efeg. The cluster being migrated is a 3-broker cluster so I launched another 3 brokers with the same configurations as the older one and then generated a broker removal task using the API: `/remove_broker?brokerid=cluster_A_broker_1,...,cluster_A_broker_3&destination_broker_ids=cluster_B_broker_1,...,cluster_B_broker_3`

Midway during the migration, one of our target cluster's brokers crashed which resulted in several partitions becoming offline. It turned out that partition 0 of the `__CruiseControlMetrics` topic was also offline and there was only 1 partition for this topic in the cluster. Along with this, I also saw a couple of partitions from the `__KafkaCruiseControlPartitionMetricSamples` topic offline:
```
CRITICAL: 5001 offline partitions.
Partitions:
__CruiseControlMetrics:0
__KafkaCruiseControlPartitionMetricSamples:28
__KafkaCruiseControlPartitionMetricSamples:7
... 4998 more lines
```
During this time, the pod hosting our Cruise Control container was also restarted, which resulted in Cruise Control trying to regenerate its cluster model using data in `__CruiseControlMetrics`. However, we saw the following error in CC's logs and CC could not make any progress in the training phase.
```
[2021-02-12 04:37:09,424] INFO Kicking off partition metric sampling for time range [1613104599482, 1613104629424], duration 29942 ms with timeout 120000 ms. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)
[2021-02-12 04:37:09,489] ERROR Received exception. (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcher)
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 30000 ms
```
This makes sense because no new broker metrics were being written to `__CruiseControlMetrics` because it was offline.

We intend to use Cruise Control for our production Kafka clusters as well, so I wanted to know if there were any best-practices and recommendations for lowering the risk of this happening again. We would need CC's self-healing and rebalancing when Kafka is down, but it seems like CC relies on Kafka to be working as well. 

Thank you for developing such a useful service!

**Comment by efeg** [comment]
@mhaseebmlk Thanks for the detailed explanation of the issue.

(1) `Metric Sampler` and (2) `Sample Store` are [pluggable components ](https://github.com/linkedin/cruise-control/wiki/Pluggable-Components) that come with default implementations, which use Kafka topics (e.g. `__CruiseControlMetrics`, `__KafkaCruiseControlPartitionMetricSamples`, `__KafkaCruiseControlPartitionMetricSamples`). You may consider using (1) a metric sampler that fetches metrics from a `Prometheus` server (if you have one) and (2) sample store that uses an external store.

That being said, 
1. when Cruise Control (CC) is unable to collect metrics from the cluster for a short period of time, it would still be functional for self-healing with all its goal. This period of time depends on how long your partition history is configured to (please see `num.partition.metrics.windows`, `partition.metrics.window.ms`, and `metric.sampling.interval.ms`). In production clusters, I would recommend having a history of at least a couple days. An example recommended config that collects 1-week history for partitions would be (1) `metric.sampling.interval.ms=300000`, (2) `partition.metrics.window.ms=3600000`, (3) `num.partition.metrics.windows=168`
2. when CC is unable to collect metrics from the cluster for an extended period of time, its goals that does not require cluster load information can still be used. For example, `ReplicaDistributionGoal` uses purely the "topology" information derived from Kafka metadata, and can be used.

Note that if there are offline partitions (i.e. not just offline replicas) in the system, then recovering failed partitions would not be possible with any system -- e.g. if brokers hosting all 3 replicas of a partition are destroyed, the data would be inaccessible.

Hope it helps!

**Comment by mhaseebmlk** [comment]
@efeg thanks for the response and those suggestions for running Cruise Control for production clusters!

The idea of fetching metrics from Prometheus sounds like it would add more resiliency to Cruise Control deployments. Do you think it would be a good idea to have a custom metric sampler implementation that first tries fetching the metrics from the Kafka topics and falls back to Prometheus in case the topics' partitions are offline?

I also noticed that more recent branches of Cruise Control have a [`PrometheusMetricSampler`](https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusMetricSampler.java) component which isn't available in the `kafka_0_11_and_1_0` branch that I am using. Do you know if the newer branches (i.e. [Releases](https://github.com/linkedin/cruise-control/releases) with `2.0.*`, `2.4.*`, and `2.5.*`) are compatible with Kafka `1.1` or if they are only compatible with the corresponding Kafka versions?

> Note that if there are offline partitions (i.e. not just offline replicas) in the system, then recovering failed partitions would not be possible with any system -- e.g. if brokers hosting all 3 replicas of a partition are destroyed, the data would be inaccessible.

That makes sense. Keeping this in mind, would it be fair to assume that the `fix_offline_replicas` [endpoint](https://github.com/linkedin/cruise-control/wiki/REST-APIs#fix-offline-replicas-in-kafka-cluster) would not work in case of offline partitions but would only work when there are offline replicas?

Finally, I had a general suggestion. While going through some of the previous issues, I noticed that there were some duplicates. I'm not sure if there already exists a wiki document or a runbook containing some of the common Cruise Control errors, what they mean and how they can be resolved; but would you be open to having such a thing in the [wiki section](https://github.com/linkedin/cruise-control/wiki)? I have been maintaining a list of some of the exceptions I have seen so far and how those were resolved and I'd be happy to contribute to it. For example, a `Troubleshooting` section in the wiki like so:

## Troubleshooting
### `ERROR _metricConsumer  returned null for _metricReporterTopic  __CruiseControlMetrics`
This normally means that CC could not find the metrics reporter topic which is configured via the `metric.reporter.topic` conifg and defaults to `__CruiseControlMetrics`  topic in the Kafka cluster. CC uses that topic to read metrics about the cluster to generate the cluster's load model and monitor it. Without the cluster model, CC will not be able to perform administrative tasks like partition rebalancing or broker removal.

#### Resolution

Ensure that this topic exists in the cluster and metrics are bring written to it.

You could either:

1. Create the topic manually, or
2. Enable auto topic creation
By setting `auto.create.topics.enable`  to  `"true"`  in the Kafka cluster's configs, Kafka will automatically create this topic.

### `NotEnoughValidWindowsException`  - Not Enough Windows Available in Range
#### Resolution
This could be happening due to three reasons:

1. Cruise Control instance has just been started upon a first time setup (i.e. a cold start), and it hasn't had enough time to collect samples to generate a cluster model. If this is the case, give the CC instance some time (e.g. 5 - 10 minutes),
2. A broker-side issue with producing metrics by Cruise Control metrics reporter to the relevant internal topic, or
3. A Cruise Control-side issue with consuming metrics from the relevant internal topic (e.g. __CruiseControlMetrics)

---

However, if you think that such a thing won't add much value and would be an overhead to maintain as the code base goes through changes then that's completely understandable too 🙂

**Comment by mhaseebmlk** [comment]
@efeg just following up with the results from increasing the duration of the partition history, we did that in the properties file:
```
# The metric sampling interval in milliseconds
- metric.sampling.interval.ms=120000
+ metric.sampling.interval.ms=300000

# The partition metrics window size in milliseconds
- partition.metrics.window.ms=300000
+ partition.metrics.window.ms=3600000

# The number of partition metric windows to keep in memory
- num.partition.metrics.windows=1
+ num.partition.metrics.windows=168
```

I am now noticing that the range of the windows is way in the future (i.e. `9223372036854775807` which translates to `Friday, April 11, 2262 4:47:16.854 PM PST`):
```
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 9223372036854775807] for aggregation options (minValidEntityRatio=0.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=6609, granularity=ENTITY)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.validateCompleteness(MetricSampleAggregator.java:540)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.aggregate(MetricSampleAggregator.java:212)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.aggregate(KafkaPartitionMetricSampleAggregator.java:151)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.aggregate(KafkaPartitionMetricSampleAggregator.java:117)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.state(LoadMonitor.java:224)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.state(KafkaCruiseControl.java:1077)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.async.GetStateRunnable.getResult(GetStateRunnable.java:28)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.async.GetStateRunnable.getResult(GetStateRunnable.java:16)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at com.linkedin.kafka.cruisecontrol.async.OperationRunnable.run(OperationRunnable.java:45)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-02-24 17:00:41 [stdout] [norcal-stageg] [dl-scribe-uswest1-stageg] - [debug] 10-114-53-90-uswest1astageg (54352c5839bb) 	at java.lang.Thread.run(Thread.java:748)
```

I wonder if the extended window is due to the change we made or because of something else? We are using v0.70.0 of Cruise Control.

**Comment by efeg** [comment]
@mhaseebmlk A metric sampler that fetches metrics from a `Prometheus` server endpoint has been added in https://github.com/linkedin/cruise-control/pull/1366. This support exists in  [Releases](https://github.com/linkedin/cruise-control/releases) with `2.0.*`, `2.4.*`, and `2.5.*`; however, as you correctly identified, it does not exist in `kafka_0_11_and_1_0`, which is not an actively maintained branch.

> Do you know if the newer branches (i.e. [Releases](https://github.com/linkedin/cruise-control/releases) with `2.0.*`, `2.4.*`, and `2.5.*`) are compatible with Kafka `1.1` or if they are only compatible with the corresponding Kafka versions?

Compatibility information is documented under [Environment Requirements](https://github.com/linkedin/cruise-control#environment-requirements) -- unfortunately, those versions are not compatible with Kafka `1.1`. If you'd be interested, feel free to cherry-pick the patch and create a PR based on `kafka_0_11_and_1_0` -- i.e. I don't expect much conflict . 

> would it be fair to assume that the `fix_offline_replicas` [endpoint](https://github.com/linkedin/cruise-control/wiki/REST-APIs#fix-offline-replicas-in-kafka-cluster) would not work in case of offline partitions but would only work when there are offline replicas?

That is correct.

> would you be open to having such a thing in the [wiki section](https://github.com/linkedin/cruise-control/wiki)? I have been maintaining a list of some of the exceptions I have seen so far and how those were resolved and I'd be happy to contribute to it. 

This would indeed be helpful -- please feel free to create a PR to add the `Troubleshooting.md` under [wiki](https://github.com/linkedin/cruise-control/tree/master/docs/wiki). We can polish the responses in the PR.

> I wonder if the extended window is due to the change we made or because of something else? We are using v0.70.0 of Cruise Control.

`9223372036854775807` is `Long.MAX_VALUE`, which is passed to `KafkaPartitionMetricSampleAggregator#aggregate` as the current time (see [code](https://github.com/linkedin/cruise-control/blob/kafka_0_11_and_1_0/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java#L224)) while handling a `state` request -- this issue has been fixed as part of https://github.com/linkedin/cruise-control/pull/1238 (i.e. `Eliminates the need for the costly on-demand aggregation of partition metric samples upon state requests`), but as `kafka_0_11_and_1_0` is not maintained, it was not cherry-picked to that branch. As CC collects more samples, `NotEnoughValidWindowsException` exception should be resolved by itself -- so this incorrect log message is not a blocker. That being said, I would strongly recommend moving away from `kafka_0_11_and_1_0` as this branch is not maintained and there has been many changes and performance improvements in other branches that supports higher versions of Kafka.
