### ISSUE TITLE
documentation For add_broker has to be edited

### ISSUE THREAD

**Issue by chandradeepak** [linkedin/cruise-control#148]
In the documentation of Add_broker it was mentioned that for throttling it should be "throttle_removed_broker" instead of throttle_added_broker 

I corrected it here 

https://github.com/chandradeepak/cruise-control/wiki/REST-API

POST /kafkacruisecontrol/add_broker?brokerid=[id1,id2...]&dryrun=[true/false]&throttle_added_broker=[true/false]&kafka_assigner=[true/false]&json=[true/false]

**Comment by efeg** [comment]
Absolutely! 
Thanks for reporting this. (Fixed in https://github.com/linkedin/cruise-control/wiki/REST-APIs).
