### ISSUE TITLE
Add TopicLeaderDistributionGoal to balance partition leaders of specified topics 

### ISSUE THREAD

**Issue by amuraru** [linkedin/cruise-control#1489]
the __consumer_offsets topic is one such example where the leaders should be evenly distributed across brokers ( when a consumer group is created in kafka the group coordinator is elected one of the leaders of this topic serving the randomly selected partition for that CG).

While "LeaderReplicaDistributionGoal" goal can be used to achieve this for all topics it is not easily configurable to target a specific set of topics.

As such a new soft goal should be added TopicLeaderDistributionGoal that requires a set of topics to be configured and balances evenly the leaders across all brokers

**Comment by efeg** [comment]
Thanks for creating the issue @amuraru !
Should we move this discussion under the relevant issue: https://github.com/linkedin/cruise-control/issues/1437?

**Comment by amuraru** [comment]
agree - we can close this as #1437 already proposes this
