### ISSUE TITLE
With Bintray Deprecation, where will Cruise Control jars be hosted?

### ISSUE THREAD

**Issue by kyguy** [linkedin/cruise-control#1493]
JFrog is shutting down their Bintray package service [1] and will stop taking submissions for new package versions after March 31st 2021. From what I understand, Bintray is the only place where the Cruise Control jars are hosted [2]. Do we know where the Cruise Control jars for future versions will be hosted?

[1] https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
[2] https://bintray.com/linkedin/maven/cruise-control

**Comment by efeg** [comment]
@kyguy Thanks for bringing this up! We are aware of the sunset of Bintray, and it is not the only place that Cruise Control jars have been hosted. Our artifacts (along with artifacts of other open source LinkedIn projects) have always been published to public [LinkedIn JFrog](https://linkedin.jfrog.io/), as well.

* I was notified that there is an ongoing maintenance in [LinkedIn JFrog](https://linkedin.jfrog.io/), which is expected to be done by end of the day today. Once the maintenance is over, you may access the artifacts here:
1. https://linkedin.jfrog.io/ui/repos/tree/General/cruise-control
2. https://linkedin.jfrog.io/ui/repos/tree/General/cruise-control-core
3. https://linkedin.jfrog.io/ui/repos/tree/General/cruise-control-metrics-reporter

Please let me know if you'd have further questions. I will keep the issue open until the maintenance is over and I get confirmation from you that you can access the jars.

**Comment by kyguy** [comment]
@efeg Thanks for the info, really appreciated it! We will point our project to LinkedIn JFrog for retrieving the Cruise Control jars

**Comment by efeg** [comment]
@kyguy Happy to hear that.
-- Looks like the maintenance is over and the public access is back. I will close the issue, but feel free to reopen if you'd have further questions or encounter issues.
