### ISSUE TITLE
cc can't auto rebalance disk 

### ISSUE THREAD

**Issue by microeastcowboy** [linkedin/cruise-control#1508]
we  can rebalance disk within each broker by setting   _rebalance?rebalance_disk=true_
does cc can **auto** balance disks utilization within each broker ?

**Comment by efeg** [comment]
@microeastcowboy the use of `intra.broker.goals` in anomaly detection / self healing is not yet supported -- i.e. cc cannot _auto_ balance disk utilization within each broker, yet.
Relevant issue: https://github.com/linkedin/cruise-control/issues/1264
