### ISSUE TITLE
ACLs and Prometheus Sampler

### ISSUE THREAD

**Issue by yasminhaque** [linkedin/cruise-control#1517]
I've got some follow up questions based on[ this thread. ](https://github.com/linkedin/cruise-control/issues/1413#issue-759742818)

Are these the same ACLs used if we are using ```PrometheusMetricSampler```?

It seems like from the source code that if we are using Prometheus to sample then ```__CruiseControlMetrics``` does not get written to - is this correct? Also is there any documentation specifically around how Cruise Control works using the Prometheus sampler as opposed to the default Cruise Control one?

_Originally posted by @yasminhaque in https://github.com/linkedin/cruise-control/issues/1413#issuecomment-820547257_

**Comment by efeg** [comment]
Hi @yasminhaque 

> It seems like from the source code that if we are using Prometheus to sample then __CruiseControlMetrics does not get written to - is this correct?

That is correct. `PrometheusMetricSampler` users do not need ACLs for `__CruiseControlMetrics`. The response above is relevant only _"If you are using the default configurations"_.

> Also is there any documentation specifically around how Cruise Control works using the Prometheus sampler as opposed to the default Cruise Control one?

The PrometheusMetricSampler can be configured as the metric sampler of Cruise Control using `metric.sampler.class` (see [Load Monitor Configurations](https://github.com/linkedin/cruise-control/wiki/Configurations#load-monitor-configurations)). The [configuration page for PrometheusMetricSampler](https://github.com/linkedin/cruise-control/wiki/Configurations#prometheusmetricsampler-configurations) lists the relevant configs to further customize for `PrometheusMetricSampler`.

_Originally replied by @efeg in https://github.com/linkedin/cruise-control/issues/1413#issuecomment-820600591_

**Comment by yasminhaque** [comment]
Thanks!
