### ISSUE TITLE
Cc failed to restart due to the number of kafka nodes being less than the number of sample topic replicas

### ISSUE THREAD

**Issue by wenbingshen** [linkedin/cruise-control#1535]
First, the sample topic has been created in Kafka, and the number of replicas is the number of kafka nodes. When one of the kafka nodes is stopped and cc is restarted, cc will report that the creation of the sample topic failed because the number of kafka nodes is less than the number of replicas, but the actual Above, the sample topic of cc has been created in kafka, so we should not block the startup of cc.

I analyzed the kafka code. This is because kafka will first assign replicas for the created topic, and then verify whether the topic exists. When the copy allocation cannot be completed, an InvalidReplicationFactorException will be thrown.

![image](https://user-images.githubusercontent.com/35599757/116347841-8ee8b500-a81f-11eb-89ec-3df313a8de2b.png)

![image](https://user-images.githubusercontent.com/35599757/116348545-de7bb080-a820-11eb-8640-21cfcf10a004.png)

**Comment by zornhsu** [comment]
Thanks for reporting this issue, Wenbing! Would you mind upgrading your Kafka version if it's prior to [KAFKA-8875](https://issues.apache.org/jira/browse/KAFKA-8875), then verify this issue again?

**Comment by wenbingshen** [comment]
> Thanks for reporting this issue, Wenbing! Would you mind upgrading your Kafka version if it's prior to [KAFKA-8875](https://issues.apache.org/jira/browse/KAFKA-8875), then verify this issue again?

@zornhsu  You are right, I did not notice this jiraId, thank you for your reminder, I am closing this issue now.
