### ISSUE TITLE
Support for reason parameter in GET and admin POST requests 

### ISSUE THREAD

**Issue by malikmanisha** [linkedin/cruise-control#1554]
As of today, reason parameter is supported by the following POST endpoints:
- pause_sampling
- resume_sampling
- add_broker
- demote_broker
- fix_offline_replicas
- rebalance
- remove_broker
- review
- topic_configuration

So currently, this parameter is missing from all GET endpoints and the following POST endpoints:
- admin
- stop_proposal_execution

Adding the parameter to the remaining requests will provide a robust way to audit all requests handled by CC

**Comment by shreelakshmijoshi** [comment]
Hello @malikmanisha !
I am a new open source contributor and would like to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?
