### ISSUE TITLE
Detect RF violations for topics having targetReplicationFactor with topicReplicationFactorMargin violation

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1565]
The current `TopicReplicationFactorAnomalyFinder` algorithm considers only the topics whose replication factor (RF) is different from the configured `targetReplicationFactor` (i.e. `self.healing.target.topic.replication.factor`) -- and while doing so, it honors minISR config (i.e. `min.insync.replicas`) of those topics to ensure an RF of `max(targetReplicationFactor, topicMinISR + topicReplicationFactorMargin)`.

As a result, it misses replication factor anomalies that may result in topics with RF = `targetReplicationFactor`, which do not satisfy `topicMinISR + topicReplicationFactorMargin`. For example, in a cluster with `targetReplicationFactor=3` and `topicReplicationFactorMargin=2` (i.e. `topic.replication.factor.margin`), if a topic with RF `3` is configured with `min.insync.replicas` of 2, then that topic will not cause detection of a topic anomaly.

**Comment by mgrubent** [comment]
I'll make an assertion here, that the desired behavior is for the topic `RF=3`, `minISR=2`, to be mutated so that it's `RF=(minISR + topicReplicationFactorMargin)`.

Is this a correct understanding of the desired behavior?

**Comment by efeg** [comment]
> I'll make an assertion here, that the desired behavior is for the topic `RF=3`, `minISR=2`, to be mutated so that it's `RF=(minISR + topicReplicationFactorMargin)`.
> 
> Is this a correct understanding of the desired behavior?

Yes, that should indeed be the desired behavior.
