### ISSUE TITLE
Admin Client does not pass through sasl.client.callback.handler.class

### ISSUE THREAD

**Issue by Sylvain-Royer** [linkedin/cruise-control#1570]
I'm currently running into an issue where I'm changing the SASL mechanism between our components in the kafka cluster. Unfortunately, the AdminClient created by cruise control does not pass in the sasl.client.callback.handler.class class, causing the calls to fail due to a `javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback` error.

After a good amount of investigating, I determined that the issue is that the issue is with KafkaCruiseControlUtils, specifically [parseAdminClientConfigs](https://github.com/linkedin/cruise-control/blob/22113c884e6fb13ab2aaf068b835cca666a52242/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java#L523). The parser never sets `SASL_CLIENT_CALLBACK_HANDLER_CLASS`, meaning we can never set the callback handler class to something other then the default `SaslClientCallbackHandler`. 

If possible, I would like to merge in a fix that simply adds 1 line to the parser and allows for `sasl.client.callback.handler.class` to be passed through to the AdminClient.

**Comment by mohitpali** [comment]
Hello Adem - When will this change be released ? I can see last release was in Mar, 2021 versioned 2.5.42.
Releasing this change would unblock SASL IAM users.

**Comment by efeg** [comment]
@mohitpali This change has already been merged on `Sat May 22 11:36:43 2021`. The oldest release that has this commit is [2.5.54](https://github.com/linkedin/cruise-control/releases/tag/2.5.54).

As indicated in https://github.com/linkedin/cruise-control#artifactory, Cruise Control artifacts are published at [Jfrog Artifactory](https://linkedin.jfrog.io/ui/repos/tree/General/cruise-control) and are publicly available there.
