### ISSUE TITLE
BOOTSTRAPPING state

### ISSUE THREAD

**Issue by gvajpeyi** [linkedin/cruise-control#1579]
ERROR: Error processing GET request '/proposals' due to: 'java.lang.IllegalStateException: Cannot get proposal because load monitor is in BOOTSTRAPPING state.'.

**Comment by efeg** [comment]
Hi @gvajpeyi 
Can you check if [this issue](https://github.com/linkedin/cruise-control/issues/1342) is relevant and let me know?

I suspect you are trying to use the bootstrap endpoint of Cruise Control (CC), which is used only for development purposes and is not really meant to be used for bootstrapping a CC instance.

**Comment by efeg** [comment]
To prevent the confusions with this endpoint, I created a PR to disable it unless the user explicitly indicates the intention to use it for the development purposes with an explicit parameter.

**Comment by gvajpeyi** [comment]
@efeg  thanks ..
My issue was fixed when i all the node have same config file means all node must send data to topic and this will take time as well to show in the top
