### ISSUE TITLE
NotEnoughValidWindowsException after confluent upgrade to 6.2.0 (kafka 2.8)  

### ISSUE THREAD

**Issue by avanakudre** [linkedin/cruise-control#1658]
I recently upgraded to confluent 6.2.0 and using CC version 2.0.95 (migrate_to_kafka_2.0 branch) and seeing below issues on CC :

1. Kafka cluster load, partition load and proposals tab are showing for a while now
ERROR: Error processing GET request '/partition_load' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: com.linkedin.cruisecontrol.exception.NotEnoughValidWindowsException: There are only 0 valid windows when aggregating in range [-1, 1629228515693] for aggregation options (minValidEntityRatio=1.00, minValidEntityGroupRatio=0.00, minValidWindows=1, numEntitiesToInclude=6877, granularity=ENTITY)'.

2.  Remove brokers execution through CC gets stuck at certain point and does not move at all without any errors in logs. 

Do I need to upgrade CC to latest version to fix above issues or is there any workaround on CC side to fix this issue. I want to avoid doing any changes on kafka side. 

I have upgraded around 50 clusters and the above issues are occurring only  on 10-12 clusters out of 50 so it is inconsistent.

**Comment by efeg** [comment]
Hi @avanakudre 
Kafka 2.8 is compatible with Cruise Control [releases with 2.5.66+](https://github.com/linkedin/cruise-control/releases) (source: https://github.com/linkedin/cruise-control#environment-requirements). So I would recommend using the supported CC version to manage Kafka 2.8 clusters.

Please let us know if the upgrade resolves the issue. If not, please look for stack traces (1) on Kafka side showing Cruise Control Metrics reporter exceptions and (2) on Cruise Control-side showing metric sampling errors / exceptions.

**Comment by avanakudre** [comment]
thanks @efeg. 

We migrated to migrafte_to_kafka_2_5 on CC server and also placed the latest cruise-control-metrics-reporter-2.5.68-SNAPSHOT.jar on brokers. Tested it on one of our clusters and it seems to have fixed all the issues. We will monitor for some more days and confirm.
