### ISSUE TITLE
Refactor KafkaAnomaly.hasProposalsToFix method

### ISSUE THREAD

**Issue by egyedt** [linkedin/cruise-control#1659]
The **_KafkaAnomaly_** class defines a method which called **_hasProposalsToFix_**. This function should get the _optimizationResult field as a parameter. Currently this is a method with a side effect. (Not readable from the caller side.)

**Comment by efeg** [comment]
Hi @egyedt Thanks for creating the issue.
Could you give more details on why you think `hasProposalsToFix` is a method with a side effect -- i.e. (1) what is the side effect and (2) what does `Not readable from the caller side` mean?

**Comment by egyedt** [comment]
Hi @efeg!

I mean the `hasProposalsToFix` is a method with side effect since its in the KafkaAnomaly class so the developers can think that there is Proposals object or something like that in the KafkaAnomaly but there isn't since the Proposals belongs to the OptimizationResult class. Furthermore the `hasProposalsToFix` function get the _optimazitionResult as a data field not as a parameter (or I can call it argument since there is a null check and an **IllegalArgumentException** line instead of NullPointerException) and what has proposals and what is proposals is not readable from outside the class. 

There are two possible solutions.

The first one when we get the _optimazitionResult as a param of the method which can be more understandable but this option is NOT increase the cohesion and NOT decrease the coupling. 
The other one when we introduce a new method in the OptimizationResult (which can be called `hasProposalsToFix`). In that case every call of the newly created `hasProposalsToFix` method should be placed after a null check of the OptimizationResult object which is also not so efficient (it raise the duplication of the source code). In contrast this solution increase the cohesion and decrease the coupling which is fine.

My conclusion is the following after thinking about the 2 solution above and the already existing one is that we should leave the source code in the current state since every solution has drawbacks beside the benefits.

If you are agree with me then we should close this issue!

**Comment by efeg** [comment]
Thanks for the clarification -- I agree with the drawbacks of those approaches, we can close the issue.
