### ISSUE TITLE
IAM MSK support

### ISSUE THREAD

**Issue by tooptoop4** [linkedin/cruise-control#1694]
Support for https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

**Comment by vipinvijay7793** [comment]
I have updated config/cruisecontrol.properties file with below properties
<img width="693" alt="cruisecontrol_setup" src="https://user-images.githubusercontent.com/67056867/133105048-70885972-a683-41be-a788-e188efbb3b8b.PNG">

I'm getting this error while I'm starting cruise control. Please help me on this.
<img width="945" alt="cruisecontrol_error" src="https://user-images.githubusercontent.com/67056867/133105415-d221a9fb-8006-4d9f-8810-5fb654c8d1e9.PNG">

is there build-in module for IAM authentication?
