### ISSUE TITLE
Meta data where not persist in webui

### ISSUE THREAD

**Issue by TheIdhem** [linkedin/cruise-control#1712]
I've got a trouble through working with this service. I've been working with web ui of cruise control and find out whenever I restart the service the meta data where be gone and I don't have any access to meta data. I wana know that how can I persist the meta data of this service in webui?
![Screen Shot 2021-10-11 at 12 25 23 pm](https://user-images.githubusercontent.com/31737620/136781831-50f1dfd7-647c-4d42-b1e8-8f537c7afd33.png)

![Screen Shot 2021-10-11 at 2 51 25 pm](https://user-images.githubusercontent.com/31737620/136781962-4dace1a2-947a-46b8-93ee-9fd07fa1af5c.png)

**Comment by nareshv** [comment]
Not sure if CC is planning to remember all the operations ? This would be a feature in the CC core.
