### ISSUE TITLE
TopicAnomalyIntegrationTest is unstable

### ISSUE THREAD

**Issue by zornhsu** [linkedin/cruise-control#1729]
After merging #1724, we started to experiencing unstable builds. Only 2 out of 4 build succeeded.
![Screen Shot 2021-11-15 at 2 59 49 PM](https://user-images.githubusercontent.com/18743174/141866377-2711a0c9-9875-4377-adf3-e8626e17b705.png)

**Comment by efeg** [comment]
The issue seems to be addressed after timeout bump and with the followup improvements on integration tests.
