### ISSUE TITLE
Add support for kafka 3.0 to CruiseControlMetricsCollector

### ISSUE THREAD

**Issue by chromy96** [linkedin/cruise-control#1740]
Hi,

CruiseControlMetricsCollector uses the configurations (e.g. [port](https://github.com/linkedin/cruise-control/blob/89d32b7b0f9c1ab347dacd1ca69afcbe6c329a8d/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java#L116)) that were deprecated in the previous version and are removed in [Kafka 3.0](https://github.com/apache/kafka/pull/10872).

My guess is that this issue should be a part of a larger 'support for kafka 3.0' issue, but I wasn't sure about the scope for that one so I started small :)

**Comment by TheIdhem** [comment]
same :((
help

**Comment by TheIdhem** [comment]
@chromy96 
I've made pull request for this problem.

https://github.com/linkedin/cruise-control/pull/1742

enjoy

**Comment by apellegr06** [comment]
Hi,

In which release is included this modification to be compliant with kafka 3.0 ?

**Comment by efeg** [comment]
@apellegr06 [Releases](https://github.com/linkedin/cruise-control/releases) with 2.5.85+ should be compliant with Kafka 3.0.
Source: https://github.com/linkedin/cruise-control#environment-requirements
