### ISSUE TITLE
Update dependencies to latest versions to inherit bug and security fixes

### ISSUE THREAD

**Issue by Boojapho** [linkedin/cruise-control#1770]
Update the dependencies in https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/gradle.properties to the latest versions.

scalaVersion=2.13.6 => 2.13.7
zookeeperVersion=3.5.9 = > 3.6.3
nettyVersion=4.1.68.Final => 4.1.72.Final
jettyVersion=9.4.43.v20210629 => 9.4.44.v20210927

**Comment by Boojapho** [comment]
Additionally,

Kafka 2.8.0 => 2.8.1
and check dependencies in build.gradle

**Comment by kalashjain23** [comment]
Hey!! I'm new to the open-source contributions. Can you guide me on why/how to check dependencies in build.gradle or maybe some good resources to understand it? Also would love to solve this issue with your help!!

**Comment by Boojapho** [comment]
@kalashjain23 I'm not a gradle expert.  I just noticed that there were dependency versions in both the gradle.properties and build.gradle files.  Build.gradle uses some of the values from gradle.properties, but it also has some that are hardcoded.  You might try `gradle build --refresh-dependencies` to see if it works on both.
