### ISSUE TITLE
Unused property

### ISSUE THREAD

**Issue by mohitpali** [linkedin/cruise-control#1804]
num.metric.fetchers property in [cruisecontrol.properties](https://github.com/linkedin/cruise-control/blob/f32dd14a32391018f4f3b469ee1d20b36023b81d/config/cruisecontrol.properties#L41) seems to be missing.

I understand that DefaultMetricSamplerPartitionAssignor just supports 1 metric fetcher that is hard coded. But since the property is not used as is, we should remove it.

**Comment by efeg** [comment]
Good catch! The deprecated config `num.metric.fetchers` was cleaned up in an earlier PR, https://github.com/linkedin/cruise-control/pull/1604, but looks like we forgot removing the corresponding property.

We should indeed remove it.
