### ISSUE TITLE
Improve repeated task reexecution for inter-broker replica reassignments

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#1824]
When partitions being reassigned (i.e. inter-broker replica reassignments) on Kafka are not a superset of `interBrokerReplicaTasksToReexecute`, CC reexecutes all the `interBrokerReplicaTasksToReexecute` regardless of whether there are some that are already being executed on Kafka-side:

https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_4/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/Executor.java#L1866

This results in logs like the following on Controller side due to redundant executions:

```
[KafkaController] [Controller id=XXX] Leader YYY for partition topic-1 being reassigned, is already in the new list of replicas 1,2,3 and is alive
```

1. CC can improve this execution logic by only resubmitting tasks that are not in execution on Kafka-side, and
2. CC can improve the logging by logging the result of `ExecutionUtils.partitionsBeingReassigned(_adminClient)` in addition to the existing `LOG.info("Reexecuting tasks {}", interBrokerReplicaTasksToReexecute);`. So that we know what exactly is going on at the Controller-side.

**Comment by CCisGG** [comment]
I think with the code change for 1, we may not need the logging change for 2.  I just feel it will add unnecessary logs that flush the log file. Does that make sense to you? @efeg

**Comment by efeg** [comment]
> I think with the code change for 1, we may not need the logging change for 2.
It would be valuable to see what is going on at Kafka controller. For example, if there is another replica reassignment request sent by a rogue user, this would let us identify what those reassignments are.

> I just feel it will add unnecessary logs that flush the log file. Does that make sense to you? @efeg
This is not expected to happen frequently -- actually it is not supposed to happen under normal circumstances. This log would let us identify what the issue is and may let us make CC more robust if this was due to some CC bug.
