### ISSUE TITLE
Webui 404 error

### ISSUE THREAD

**Issue by Linjianfengccc** [linkedin/cruise-control#1853]
![image](https://user-images.githubusercontent.com/49085765/177607262-4fa34021-be8e-4c38-961f-fe8718b7cb43.png)
seems my cc in running normally, but it gives me a 404 error when I try to access cc web ui
![image](https://user-images.githubusercontent.com/49085765/177608088-f75de8fb-784a-4eba-8865-c2c4d23e282d.png)
but i can call the apis such as /kafkacruisecontrol/kafka_cluster_state, and "./cruise-control-ui/dist/" is an empty folder

**Comment by nareshv** [comment]
Hello @Linjianfengccc , the UI doesn't come bundled with this. Please download it from https://github.com/linkedin/cruise-control-ui/wiki and put it within CC

**Comment by Linjianfengccc** [comment]
Thanks @nareshv ! it workd now
