### ISSUE TITLE
Docker Cruise Control Disk Pressure

### ISSUE THREAD

**Issue by heartTorres** [linkedin/cruise-control#1854]
I have created a docker container for my cruise control app  with control-ui and deployed in EKS (AWS K8)
But it gets evicted in 7 minutes, upon checking the log writes consumes most of the disk space.
The 20GB was became full in span of 7 minutes. This is quite fast I guess?

I have already set the log to "ERROR" instead of INFO. Sadly, it still consumes the disk space in span of minutes so disk pressure still happening. Is there any way to mitigate the log consumption?

**Comment by mohitpali** [comment]
It is possible that your logs are getting full with Exception messages and I have seen this happen in the past. Would you be able to paste the logs here ?

**Comment by heartTorres** [comment]
I have found the issue, the logs were filling up the container volume in span of 7 minutes due to the exception error that it couldn't reach the prometheus service. 

Closing this ticket.
