### ISSUE TITLE
Configurations page is not updated

### ISSUE THREAD

**Issue by mohitpali** [linkedin/cruise-control#1872]
I had made changes to configurations wiki in https://github.com/linkedin/cruise-control/pull/1809. However, the configurations page is not reflecting the changes - https://github.com/linkedin/cruise-control/wiki/Configurations.

Am i missing something ?

**Comment by wyuka** [comment]
We need to keep the wiki in sync - https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2

We can probably set up a github action to do it.

**Comment by mohitpali** [comment]
@CCisGG I have updated the wiki at my fork - https://github.com/mohitpali/cruise-control/wiki

Since there does not seem to be a way to create a way to create a PR for wiki, could you please pull my changes from my forked wiki ?


https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github

**Comment by CCisGG** [comment]
Hi @mohitpali I pulled your changes locally and looks like there are multiple changes. Could you explain why you were making those changes? 

E.g. looks like you:
- removed a lot of zk configurations
- change zk connect to false (I assume those are because cc is moving away from zk)
- removed broker failure detection config

**Comment by mohitpali** [comment]
@CCisGG did you pull the wiki repo only ?

**Comment by CCisGG** [comment]
Hi @mohitpali I pulled your migrate_to_2_4 branch and checkout to the "wiki" repo. Let me know if I misunderstood something here.

**Comment by mohitpali** [comment]
Wiki has its own branch and there is only **master** branch. The url should be <>.wiki.git

**Comment by CCisGG** [comment]
Wiki updated.
