### ISSUE TITLE
Compare exact member of ISR with RS when deciding whether the partition is  URP

### ISSUE THREAD

**Issue by CCisGG** [linkedin/cruise-control#1905]
Today, the way we determine a partition is an URP (Under Replicated Partition) based on the size of ISR and RS. E.g. if ISR = [A, B], and RS = [A, B, C], then the partition is treated as URP by CC.

However, in certain cases (usually because kafka is in a bad/inconsistent state), the ISR can be diverged from RS. E.g. ISR = [A, B, B], while RS = [D, E, F]. In this case, we still want CC to report this replica as URP, since the partition is not in a good state.

The proposal is, instead of comparing the size of ISR and RS, we should comparing the members in ISR and RS. If ISR != RS, CC should report it as URP.

**Comment by suyashtava** [comment]
Hi, @CCisGG , may I know if someone is working on it, if not? Can I pick this up

**Comment by suyashtava** [comment]
Btw, I am interested to know, when ISR = [A, B, B], while RS = [D, E, F] This condition will happen?

**Comment by CCisGG** [comment]
@suyashtava Sure! Please feel free to take it!

It happened recently in our kafka cluster, where there was a weird bug in ZooKeeper that different ZK host has different Data. Since Kafka relies on ZooKeeper, it messed up the replica set when it reads data from zookeeper. This should rarely happens, but just in case it happens, we should make this change.

**Comment by AnvarKhatik** [comment]
Hey @suyashtava You're Still Working On This Issue

**Comment by suyashtava** [comment]
Yup, yup. I was on Call last week, didn’t get a chance. Will fix it this
week.

Though I am trying to replicate the issue, but not able to replicate @CCisGG

**Comment by CCisGG** [comment]
@suyashtava this is a rare case and it's hard to reproduce. I think it's ok to just change the logic and add some unit test for it.

**Comment by suyashtava** [comment]
Raised a PR: https://github.com/linkedin/cruise-control/pull/1923
