### ISSUE TITLE
Ability to move all replicas from a disk to other disks of the same broker

### ISSUE THREAD

**Issue by ilievladiulian** [linkedin/cruise-control#1907]
Right now it is possible to move leader replicas from a list of disks but there is no way to move all replicas from a disk to other disks of the same broker. 
This would be useful when needing to remove a disk from a broker without the loss of data.

**Comment by CCisGG** [comment]
Hi @ilievladiulian , could you briefly explain what's the use case of this feature?

**Comment by ilievladiulian** [comment]
Hi @CCisGG! This feature is useful when the disk space usage increases and the user does not want to increase the number of disks, but instead move everything on a larger disk so it's easier to maintain and to reduce the data fragmentation.
