### ISSUE TITLE
CPU Usage shown incorrectly 0.00% - No self healing triggered

### ISSUE THREAD

**Issue by mohitpali** [linkedin/cruise-control#1913]
## Problem

We did a test where we induced high CPU Usage on a broker by doing Produce only traffic. There was no consume load.

#### Actual CPU Usage metrics :

<img width="1087" alt="Screen Shot 2022-09-26 at 1 59 22 PM" src="https://user-images.githubusercontent.com/20642692/192379329-b0f28d87-6190-4e61-84a2-5d37078b1628.png">

#### What Prometheus reports :
```
 {
    "metric": {
      "instance": "b-18.XXXXX.us-east-1.amazonaws.com:11002"
    },
    "value": [
      1663883747.106,
      "0.7534427083333867"
    ]
  }
  ```
#### Additional Logs (number of sample windows is 5)

```
INFO reource : cpu, broker : 18, utilization : 0.0 (com.linkedin.kafka.cruisecontrol.model.ClusterModelStats)

INFO reource : cpu, broker : 18, load : Load[metricValues={metricId:"0", values:"{avg:0.0, max:0.0, {0:0.0, 1:0.0, 2:0.0, 3:0.0, 4:0.0}"
```

<img width="1546" alt="Screen Shot 2022-09-26 at 4 53 40 PM" src="https://user-images.githubusercontent.com/20642692/192401590-2082c8a7-0025-4c61-aa33-e835b2b85232.png">

This means that CPU Usage on the stats screen is being shown as 0% and there are no replica movements.

### Proposal

We need to change this code here - https://github.com/linkedin/cruise-control/blob/b4e44ec004e6f5e22bd1c4e203d92341ed9e1659/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ModelUtils.java#L104 to use an && instead of an || and calculate leader CPU load contribution even if there is no leader out traffic.

**Comment by mohitpali** [comment]
Sample Log metrics - 


``
TRACE Enqueued broker metric sample {entity=(brokerId=14,host=b-14.XXXXX.us-east-1.amazonaws.com),sampleTime=1664238259000,CPU_USAGE=0.580,DISK_USAGE=429076.119,LEADER_BYTES_IN=11444.388,LEADER_BYTES_OUT=0.000,PRODUCE_RATE=97670.526,FETCH_RATE=64089.248,MESSAGE_IN_RATE=674418.555,REPLICATION_BYTES_IN_RATE=0.000,REPLICATION_BYTES_OUT_RATE=0.000,BROKER_PRODUCE_REQUEST_RATE=3220.324,BROKER_CONSUMER_FETCH_REQUEST_RATE=2.048,BROKER_FOLLOWER_FETCH_REQUEST_RATE=36065.050,BROKER_REQUEST_HANDLER_POOL_IDLE_PERCENT=0.787,BROKER_REQUEST_QUEUE_SIZE=6.000,BROKER_RESPONSE_QUEUE_SIZE=0.047,BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_MAX=188.000,BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_MEAN=0.920,BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_MAX=175.000,BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_MEAN=0.028,BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_MAX=191.000,BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_MEAN=0.299,BROKER_PRODUCE_TOTAL_TIME_MS_MAX=7253.000,BROKER_PRODUCE_TOTAL_TIME_MS_MEAN=53.990,BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_MAX=1443.000,BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_MEAN=500.145,BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_MAX=3826.000,BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_MEAN=137.867,BROKER_PRODUCE_LOCAL_TIME_MS_MAX=654.000,BROKER_PRODUCE_LOCAL_TIME_MS_MEAN=4.838,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MAX=85.000,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MEAN=0.039,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MAX=1407.000,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MEAN=2.420,BROKER_LOG_FLUSH_RATE=0.000,BROKER_LOG_FLUSH_TIME_MS_MAX=478.796,BROKER_LOG_FLUSH_TIME_MS_MEAN=28.040,BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_50TH=0.000,BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_999TH=7.628,BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_50TH=0.000,BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_999TH=7.913,BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_50TH=0.000,BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_999TH=7.981,BROKER_PRODUCE_TOTAL_TIME_MS_50TH=1.333,BROKER_PRODUCE_TOTAL_TIME_MS_999TH=12.942,BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_50TH=501.000,BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_999TH=512.884,BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_50TH=0.000,BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_999TH=195.525,BROKER_PRODUCE_LOCAL_TIME_MS_50TH=1.000,BROKER_PRODUCE_LOCAL_TIME_MS_999TH=11.502,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_50TH=0.000,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_999TH=2.000,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_50TH=0.000,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_999TH=2.990,BROKER_LOG_FLUSH_TIME_MS_50TH=8.135,BROKER_LOG_FLUSH_TIME_MS_999TH=94.769} 
``


The interesting part is that the metrics point to ZERO replication bytes out - 
```
LEADER_BYTES_OUT=0.000,
PRODUCE_RATE=97670.526,
FETCH_RATE=64089.248,
MESSAGE_IN_RATE=674418.555,
REPLICATION_BYTES_IN_RATE=0.000,
REPLICATION_BYTES_OUT_RATE=0.000
```

**Comment by CCisGG** [comment]
Verified for CruiseControlMetricsReporterSampler, the Topic_BYTES_OUT also maps to kafka bytesOutPerSec.

https://github.com/linkedin/cruise-control/blob/b7257504d65c308476b59412153c1c26fb6a6eaa/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/MetricsUtils.java#L189

Given that, the changes in your PR is reasonable and should fix the issue. Thanks @mohitpali !
