### ISSUE TITLE
[RackAwareGoal] Insufficient number of racks 

### ISSUE THREAD

**Issue by edwdev** [linkedin/cruise-control#1916]
Hi!

We have a a 12 broker cluster with 3 racks (3 x AZ's in AWS). These are correctly set in the broker config. CC is running on an external EC2.

However, when trying to create a proposal, I'm getting:

`[RackAwareGoal] Insufficient number of racks to distribute each replica (Current: 1, Needed: 12). Add at least 11 racks with brokers.`

Can this be a bug, that CC, isn't picking up the racks correctly ?

**Comment by marcelloromani** [comment]
What was the solution here?
