### ISSUE TITLE
Metric AnomalyDetector.UNDER_PROVISIONED not accurate with BrokerSetAwareGoal

### ISSUE THREAD

**Issue by mohitpali** [linkedin/cruise-control#1918]
### Problem

``BrokerSetAwareGoal`` restricts movements within the boundary of a broker set. This means that if a resource Capacity Goal e.g. ``DiskCapacityGoal`` is violated for brokers within a broker set in a manner where there is no disk capacity on the brokers in a broker set but there is capacity available in another broker set.

Lets say the disk capacity threshold is 70%
```
BS1 = B1(75% disk used) + B2(75% disk used)
BS2 = B3(10% disk used) + B4(10% disk used)
```

B1 and B2 both have ``DiskCapacityGoal`` violated. ``GoalViolationDetector`` will detect ``DiskCapacityGoal`` as violated. However, to ``GoalViolationDetector``, the ``DiskCapacityGoal`` is a **fixable** violation. Since for ``DiskCapacityGoal``, the capacity is available on other Brokers within the cluster.

However, for ``GoalOptimizer``, the optimization will fail since the ``BrokerSetAwareGoal`` along with ``DiskCapacityGoal`` will not be able to generate a proposal. This Optimizer behavior is correct and expected.

Since the ``ProvisionStatus`` metrics is published from ``GoalViolationDetector``, the ``UNDER_PROVISIONED`` status is not reported by AnomalyDetector sensor.

<img width="1306" alt="Screen Shot 2022-10-04 at 2 42 10 PM" src="https://user-images.githubusercontent.com/20642692/193936199-ce8c3820-2a74-4f51-8101-d3a333bc5a7f.png">
<img width="1325" alt="Screen Shot 2022-10-04 at 2 43 03 PM" src="https://user-images.githubusercontent.com/20642692/193936204-6f657e88-cfc2-45d6-98cd-afcacb5684ac.png">

```
INFO Failed to generate proposals for execution (UUID: eccbe114-5be4-48b0-9a82-2961354a04f0 reason: Self healing for GOAL_VIOLATION: {Unfixable goal violations: {}, Fixable goal violations: {DiskCapacityGoal}, Exclude brokers recently (removed: true demoted: true), Provision: UNDECIDED}). (com.linkedin.kafka.cruisecontrol.executor.Executor)

com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [DiskCapacityGoal] Utilization (782404.13) of broker 7 violated capacity limit (614400.00) for resource disk. Add at least 1 broker for disk. || Tips: [1] There are 5 topics excluded from replica move. Potential mitigation: Remove selected topics from exclusion using excluded_topics parameter. Then, re-run your original request. Add at least 1 broker for disk. (operationLogger)

WARN Encountered optimization failure when trying to fix the anomaly {Unfixable goal violations: {}, Fixable goal violations: {DiskCapacityGoal}, Exclude brokers recently (removed: true demoted: true), Provision: UNDECIDED}. (com.linkedin.kafka.cruisecontrol.detector.AnomalyDetectorManager)

```

## Why is it relevant ?

The UNDER_PROVISIONED metrics is crucial to understand if a BrokerSet is out of capacity and requires broker addition/provisioning in the BrokerSet. (Since the movements can not happen outside the BrokerSet with BrokerSetAwareGoal.)

## Proposal

We should publish the provision status metrics from Goal Optimizer as well. I would like to add the ProvisionStatus metrics to be published from GoalOptimizer class as well under the existing sensor dimension - ``GoalOptimizer``.

These will be additional metrics and will not impact the existing ProvisionStatus metrics under ``AnomalyDetector`` sensor.

Please let me know what do you think ! @efeg @CCisGG 

Thanks, Mohit

**Comment by CCisGG** [comment]
> However, for GoalOptimizer, the optimization will fail since the BrokerSetAwareGoal along with DiskCapacityGoal will not be able to generate a proposal. This Optimizer behavior is correct and expected.

If it is not able to generate a proposal, how can "DiskCapacityGoal violation" be fixable?

**Comment by CCisGG** [comment]
> We should publish the provision status metrics from Goal Optimizer as well. I would like to add the ProvisionStatus metrics to be published from GoalOptimizer class as well under the existing sensor dimension - GoalOptimizer.

I think it's reasonable proposal, if we can make sure that the 2 metrics emitted from different places always have the same value. I'll take a look at your PR.

**Comment by mohitpali** [comment]
>If it is not able to generate a proposal, how can "DiskCapacityGoal violation" be fixable?

DiskCapacityGoalViolation by itself is fixable since the GoalViolationDetector checks Goal violation individually Goal by Goal and does not take any other Goal into account - 

https://github.com/linkedin/cruise-control/blob/b4e44ec004e6f5e22bd1c4e203d92341ed9e1659/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java#L314

GoalOptimizer loops in goalsByPriority and builds a proposal that is satisfiable by all other goals and Optimizes them -

https://github.com/linkedin/cruise-control/blob/1d0f1b0a5d1033807bee8552e71c08337f4c2d8d/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java#L451-L452

**Comment by mohitpali** [comment]
> I think it's reasonable proposal, if we can make sure that the 2 metrics emitted from different places always have the same value. I'll take a look at your PR.

The Proposal here is to publish metrics from GoalOptimizer since the ones from GoalViolationDetector do not tell us if we should add new brokers to broker set. The values from GoalViolationDetector won't be the same. In fact I feel it is better to deprecate these metrics from GoalViolationDetector and use GoalOptimizer instead.

Keeping backwards compatibility and fact that users may be replying on existing AnomalyDetector sensors for Provision Status, I wouldn't remove the existing GoalViolationDetector metrics.

**Comment by CCisGG** [comment]
> > If it is not able to generate a proposal, how can "DiskCapacityGoal violation" be fixable?
> 
> DiskCapacityGoalViolation by itself is fixable since the GoalViolationDetector checks Goal violation individually Goal by Goal and does not take any other Goal into account -
> 
> https://github.com/linkedin/cruise-control/blob/b4e44ec004e6f5e22bd1c4e203d92341ed9e1659/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/detector/GoalViolationDetector.java#L314
> 
> GoalOptimizer loops in goalsByPriority and builds a proposal that is satisfiable by all other goals and Optimizes them -
> 
> https://github.com/linkedin/cruise-control/blob/1d0f1b0a5d1033807bee8552e71c08337f4c2d8d/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/GoalOptimizer.java#L451-L452

Thanks for the explanation! I wasn't aware of that. That's probably something to think about in the future, as it looks a bit weird when cc says it's fixable but actually not able to fix it. Not related to this issue though.

**Comment by CCisGG** [comment]
> > I think it's reasonable proposal, if we can make sure that the 2 metrics emitted from different places always have the same value. I'll take a look at your PR.
> 
> The Proposal here is to publish metrics from GoalOptimizer since the ones from GoalViolationDetector do not tell us if we should add new brokers to broker set. The values from GoalViolationDetector won't be the same. In fact I feel it is better to deprecate these metrics from GoalViolationDetector and use GoalOptimizer instead.
> 
> Keeping backwards compatibility and fact that users may be replying on existing AnomalyDetector sensors for Provision Status, I wouldn't remove the existing GoalViolationDetector metrics.

Got it. It makes sense to me, but I'd also like to hear inputs from my team. @wyuka and @efeg , could you take a look at this issue are share your thoughts?

**Comment by efeg** [comment]
Thanks for reporting the issue Mohit. (1) Not reporting the satisfiability / fixability of the combined self-healing goals for goal violation self-healing and (2) lack of provisioner integration for adding resources for that case are indeed some gaps in the provisioner logic of CC. Here's one approach we can brainstorm about:

There is a way in the code to distinguish the caller of the goal optimizer -- i.e. identify whether the optimization is triggered by goal violation detector for self-healing or not (see `OptimizationOptions#_isTriggeredByGoalViolation`).
In case the optimization is triggered for self-healing a goal anomaly AND the self healing goals are configured the same as goal violation detection goals, then 
* we can emit a metric to indicate the "fixability" of the combined self-healing goals and 
* (if provisioner is enabled) pass the relevant provision recommendation to the provisioner along with signals to indicate that this is due to a "combined goal violation" and maybe the list of optimized goals in `RightsizeOptions` (not sure if it is the best place to pass this info). That being said, this approach still fails to provide sufficient information to provisioner to make the best decision regarding how many brokers to add to which "broker set" in your example case. To achieve that, we would need "brokerset-aware capacity goals" that pass the broker set information as part the `ProvisionRecommendation`.

**Comment by mohitpali** [comment]
Thanks for your response Efe. 
* At the moment, I want to just get notified if the GoalOptimizer fails to optimize. Based on that I can build an integration to add brokers outside of CruiseControl. So as a first step I want to get the signal right. I can think about Provisioner integration as another step. Would changing my current PR to emit a single metric called ``fixability`` or ``optimizability`` makes sense ? If there is any OptimizationFailureException in goal.optimize() caught by GoalOptimizer than we publish ``fixability``/``optimizability`` as 0 or else 1. How does this sound ?

* I do not fully understand how identifying the caller of the self healing goals being the same as goal violation detection goals would make a difference.

* What is the difference between GoalOptimizer and GoalViolationDetector and why does GoalViolationDetector optimizes Goals individually ?

**Comment by mohitpali** [comment]
Adding our discussion summary here -

* Make changes to the PR and emit a metric called``combined-goals-are-unfixable``
* Update the value of the metric only if the goal list is a super-set of the self-healing goals. (The GoalOptimizer can be called by manual rebalance and we want to include )
* Whenever an Execution is finished, it should reset this metrics.
