### ISSUE TITLE
How to change log level from INFO to WARN?

### ISSUE THREAD

**Issue by johnswarbrick-napier** [linkedin/cruise-control#1938]
The default INFO level logging in cruise control is very verbose.

Is there a method for changed the log level to WARN?

I checked through the charts and code but couldn't find any option.

Thanks :)

**Comment by mohitpali** [comment]
You should be able to adjust the logging levels here - https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/config/log4j.properties

**Comment by CCisGG** [comment]
Closed as @mohitpali has asnwered the question. Thank you @mohitpali !
