### ISSUE TITLE
Dynamically Disabling Cruise Control

### ISSUE THREAD

**Issue by diljeetsingh-nr** [linkedin/cruise-control#1947]
Hi, 

Currently using MSK to host our Kafka clusters. There is often scheduled maintenance that occurs(patching, rebooting, etc.). We do have the schedule in advance. Is there any way to dynamically shut off cruise control balancing or healing operations during these times?

Best,
Diljeet

**Comment by drozd0** [comment]
@diljeetsingh-nr sorry for being off-topic, we faced an issue with AMP(AWS Prometheus) integration. Did u use an on-demand or cloud Prometheus setup? https://github.com/linkedin/cruise-control/issues/1946

**Comment by mohitpali** [comment]
You could disable self healing during maintenance by calling this API mentioned on the [wiki](https://github.com/linkedin/cruise-control/wiki/REST-APIs) -

```
POST /kafkacruisecontrol/admin?disable_self_healing_for=[anomaly_type]
```

In addition to that if you want to stop a currently running execution, you could run -

```
POST /kafkacruisecontrol/stop_proposal_execution
```

**Comment by mohitpali** [comment]
Can this be closed please ?

**Comment by CCisGG** [comment]
Closed. Thank you @mohitpali ! Please feel free to tag me next time.
