### ISSUE TITLE
Does cruise control works with Apache kafka 3.3.1

### ISSUE THREAD

**Issue by vinaykumar1997** [linkedin/cruise-control#1954]
Getting 0 metrics collected from 0 brokers when kafka is upgraded from 2.8.1 to 3.3.1

Can someone help here.

**Comment by mrandreyeff** [comment]
Same here.
Metrics seems to be arriving (topic is populated).
Also cruise-control was operational with Kafka 3.3.1 till the CC service was restarted.
After that fails to get any `Monitored Windows`

**Comment by slelinger** [comment]
which metrics reporter version are you using? for me upgrading `2.5.94` -> `2.5.121` solved this problem

**Comment by slelinger** [comment]
Running with kafka 3.4.x - no issues, just make sure to deploy latest reporter

**Comment by manishchet** [comment]
> Running with kafka 3.4.x - no issues, just make sure to deploy latest reporter

hi can you mention what you did i am doing for kafka 3.4 but getting 0 metrics

**Comment by slelinger** [comment]
> > Running with kafka 3.4.x - no issues, just make sure to deploy latest reporter
> 
> hi can you mention what you did i am doing for kafka 3.4 but getting 0 metrics

nothing special really. which reporter version are you running on the brokers? any error logs? do you have `__CruiseControlMetrics` topic present? How about: 
```
__KafkaCruiseControlModelTrainingSamples
__KafkaCruiseControlPartitionMetricSamples
```
