### ISSUE TITLE
Number of replicas is calculated incorrect

### ISSUE THREAD

**Issue by drozd0** [linkedin/cruise-control#1956]
Hello, we are going to use CC in our production env. Kafka MSK 3.2.0 is in use.

When I open the CC UI, I see an incorrect number of replicas for my cluster: 
![Screenshot 2023-01-11 at 11 13 00](https://user-images.githubusercontent.com/2510277/211755148-51e36ed3-8e09-48fa-9ec2-fcb725c4ec2b.png)
AKHQ shows other details:
![Screenshot 2023-01-11 at 11 21 38](https://user-images.githubusercontent.com/2510277/211755246-dc27b32b-0812-44f6-9394-2c43193145c0.png)

I also can tell that we are using replication factor 3 for most of our topics. So, each broker should have very close number of partitions, e.g. 
|    |  broker1  |  broker2  |  broker3  |
|:-:|:---------:|:-------------:|:------:|
|topicA| L |  R | R |
|topicB| R | L | R |
|topicC| R | R | L |
|topicD| L | R | R |

According to the table above: 
broker1 has 2 **L**eader partitions and 2 **R**eplicas
broker2 has 1 **L**eader partitions and 3 **R**eplicas
broker3 has 1 **L**eader partitions and 3 **R**eplicas

The total number of **R**eplicas cannot be more than the total number of partitions on the broker! 
In our case with replication factor 3(equal to the number of brokers), I am expecting that the number of **R**eplicas equals or less than ~700 partitions but it looks like CC sums all partitions from all brokers for each broker.

What's wrong with my assumption? 
Thank you in advance!

**Comment by mohitpali** [comment]
The number looks correct to me. The number of the total replicas should be approximately 3 times since you have a RF of 3 on most of the topics.
A partition can have only 1 leader. On each of the broker lets say you have ~700 leaders. That means total partition count should be ~2100.

**Comment by drozd0** [comment]
You are correct, but in this case, CC is misleading.
Partition/replica/leader are three different entities, IMHO. 

And what's the best strategy to choose
# The maximum number of replicas that can reside on a broker at any given time.
max.replicas.per.broker=990

Does it mean the number of total partitions/ only replicas or only leaders?

Idea is to limit the max number of all partitions on the broker according to MSK limitations.

**Comment by mohitpali** [comment]
In an ideal case you should not let a partition have leader and follower replicas on the same broker. For replication factor of 3, IIUC, CC makes sure that a partition p0 has it's leader and follower replicas distributed in one AZ each (given you have 3 AZ cluster) with RackAwareGoal.
With this assumption,

Total Partition Count per Broker = Leaders on Broker + Followers on Broker.

There is no confusion about that and CC gives correct value.

On your second question, you can determine the number of partitions on a single broker by applying the configuration max.replicas.per.broker. That is same as saying max partitions per broker.
You can read MSK recommendations on the documentation. The number varies based on the type of instance.
You should also do additional maths on the Volume size and max partition size and base the max replica count based on that.

Disk Size > max replicas per broker * max expected partition size.

Leave some headroom on the disk also to help the movement replication.

Hope this helps.

**Comment by drozd0** [comment]
Yeah, it makes sense. Thank you a lot.
