### ISSUE TITLE
Support for removing / decommissioning logDirs

### ISSUE THREAD

**Issue by scholzj** [linkedin/cruise-control#1958]
It would be great if Cruise Control had support for decommissioning / removing log dirs. One could use it for example when planning to remove disks from JBOD storage or moving to a new disk type. It would work similarly to decommissioning brokers, but instead of moving all data from a given broker, it would just move the data from a given log dir to other log dirs on the same broker (or possibly to other brokers as well). 

This does not seem to be currently supported in Cruise Control. But at least in Strimzi this seems to be something users are often asking about for example when changing the storage type. Today, they can use for example the partition reassignment script from Kafka, but that is quite a painful process. I think it would be a great enhancement if Cruise Control was able to do it automatically. Thanks.

**Comment by amuraru** [comment]
https://github.com/linkedin/cruise-control/pull/1908 tackles this

**Comment by scholzj** [comment]
Thanks for pointing it out. I looked out for existing issues / PRs but I guess I was blind. 🤦 Closing as a duplicate to #1907 / #1908.
