### ISSUE TITLE
Offer to help

### ISSUE THREAD

**Issue by kennetheversole** [linkedin/cruise-control#1961]
I don't know if this is the correct place for this, but I was wondering if there is a team, slack channel or some other official location users can collaborate on future changes/road map.

**Comment by CCisGG** [comment]
Hi @kennetheversole , thanks for being willing to help!

There are several ways I can see.
1. We have an active gitter channel: https://app.gitter.im/#/room/#kafka-cruise-control_Lobby:gitter.im. Please feel free to add any proposals there or help to answer people's questions.
2. For any improvement plans, please feel free to create new issues, and tag me if the improvement is critical or high priority.

Please let me know if you have more questions!

**Comment by kennetheversole** [comment]
commented  in the glitter room
