### ISSUE TITLE
"sun.reflect.Reflection.getCallerClass is not supported" warning when running from fat JAR

### ISSUE THREAD

**Issue by piotrp** [linkedin/cruise-control#1996]
Running CC 2.5.117 using JAR generated by `buildFatJar` task logs this on startup:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```

It comes from Log4j2 and doesn't happen when using separate JAR files because Log4j2 uses Java's Multi-Release JARs. Fat JAR generation already puts required files in place, but it's missing `Multi-Release: true` in _MANIFEST.MF_.

**Comment by mhratson** [comment]
@piotrp can you please add some details on how to reproduce the issue? Thank you!

**Comment by piotrp** [comment]
Using Java 11:
1. Build fat jar using `./gradlew buildFatJar`
2. Start Cruise Control using `cruise-control-all.jar`

This happens because Gradle repacks JAR without adding `Multi-Release: true` to MANIFEST.MF, which is required by some dependencies - in this case Log4j2.

As far as I know this doesn't break anything, but fixing this brings Cruise Control closer to working on newer Java versions.

**Comment by mhratson** [comment]
@piotrp I'm not able to reproduce the issue in my envoronment:
```
$ ./gradlew buildFatJar
$./kafka-cruise-control-start.sh -jars ./cruise-control/build/libs/ ./config/cruisecontrol.properties 
```
How do I get the warning?

**Comment by CCisGG** [comment]
@mhratson I think this change won't affect our environment. If you are ok with it, I'll merge this one.
