### ISSUE TITLE
kafka broker disconnected

### ISSUE THREAD

**Issue by smart1993** [linkedin/cruise-control#20]
this is log:
![wechatimg7](https://user-images.githubusercontent.com/6806376/30005008-f5e55490-910b-11e7-9078-dfb4ae1d89c8.jpeg)
and this is my kafka server.properties:
![wechatimg8](https://user-images.githubusercontent.com/6806376/30005020-222774c0-910c-11e7-86f8-be52284871cd.jpeg)
i sure my kafka server is normal  running 
kafka version:0.10.1

**Comment by tanuj83** [comment]
Getting same error with kafka 0.10.2

**Comment by tanuj83** [comment]
I found the root cause. it was due to kafka was running on host IP not on localhost , below config helped to fix it

listeners=PLAINTEXT://0.0.0.0:9092
advertised.host.name=<FQDN hostname>

**Comment by becketqin** [comment]
@tanuj83 Glad that you found the reason. Yes, by default cruise control metrics reporter talks to the localhost. You may also config `cruise.control.metrics.reporter.bootstrap.servers` explicitly to tell the metrics reporter where to send the metrics.

**Comment by tanuj83** [comment]
@becketqin where can I configure it "cruise.control.metrics.reporter.bootstrap.servers" ? 
on kafka servers kafka.properties ?

**Comment by tanuj83** [comment]
@becketqin  it works by adding this parameter in kafka.property

**Comment by yyb345** [comment]
@tanuj83 you modified this metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
to   metric.reporters=cruise.control.metrics.reporter.bootstrap.servers ?

**Comment by tanuj83** [comment]
@yyb345  No, used below in Kafka brokers

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

**Comment by yyb345** [comment]
@tanuj83  yeah, but how to configure **cruise.control.metrics.reporter.bootstrap.servers** ?
 I still encountered this problem com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter: Failed to send cruise control metric

**Comment by tanuj83** [comment]
@yyb345  I  used in kafka.properties as below

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.reporter.bootstrap.servers = broker1:9092

**Comment by yyb345** [comment]
what broker1 means ? Should I replace broker1 with my own broker ?

**Comment by tanuj83** [comment]
@yyb345  Yes
