### ISSUE TITLE
admin page

### ISSUE THREAD

**Issue by lawrencewu** [linkedin/cruise-control#203]
Is there an amdin page for this tool?
otherwise supply with an installation doc or user guide?

**Comment by jmarkan** [comment]
@lawrencewu AFAIK, admin page is not offered (yet) for CruiseControl. As for your question on installation doc, its actually already there in this repo. Please find it here - https://github.com/linkedin/cruise-control/blob/master/README.md

**Comment by nareshv** [comment]
@lawrencewu we have made the admin ui opensource

https://github.com/linkedin/cruise-control-ui
