### ISSUE TITLE
Best practices to deploy Cruise-Control

### ISSUE THREAD

**Issue by nsagnett** [linkedin/cruise-control#2049]
Hello,

I have a simple question about Cruise-Control deployment.

I just wonder if it's possible to have multiple instances of webserver for the same Kafka cluster administration or only one is the recommendation.
I ask that about executor seems to be duplicated with each server and if I have 2 instances, it is possible to have different proposals depending on the requested webserver instance

Thanks,

**Comment by mhratson** [comment]
> multiple instances of webserver 

by webserver you mean CruiseControl instance? I don't think it's supported yet
