### ISSUE TITLE
Cruise control rebalance hangs when setting static broker configurations along with `default.replication.throttle`

### ISSUE THREAD

**Issue by rosakng** [linkedin/cruise-control#2078]
Today the way Cruise Control removes broker throttle rate configurations during a rebalance is to [delete](https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L342) the current configurations for leader and follower replication throttled rate, then expect those configurations to be `null` after removing them and before continuing on with the rebalance. Though this is true in the case of removing dynamic broker configurations, however, if there is a static broker configuration set for `leader.replication.throttled.rate` or `follower.replication.throttled.rate`, the configurations will never equal in the [check](https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L376), leaving the rebalance to hang and exhaust all of its retries without continuing. 

The state of cruise control then appears to have paused in either moving more data or fully completing the process.
Cruise control should be able to run rebalances even if a static configuration is set for `leader.replication.throttled.rate` or `follower.replication.throttled.rate` along with [`default.replication.throttle`](https://github.com/linkedin/cruise-control/wiki/Configurations).

**Comment by rosakng** [comment]
A proposed solution when clearing throttles is to remove the throttle rate configuration if the current throttle rate is of a dynamic broker config source [type](https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/admin/ConfigEntry.ConfigSource.html#DYNAMIC_BROKER_CONFIG), such that only dynamic broker configurations are being removed. In order to support static configurations being returned after a previous dynamic configuration is removed in [waitForConfigs](https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_5/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L370) is to set the expected configuration value to the current static configuration value, only if the current configuration is set static-ly. 

👋 @CCisGG , would you happen to know if this is a known issue or something I can contribute for a fix?

**Comment by rosakng** [comment]
HI @CCisGG  Thanks for your reply! 
My concern with setting `default.replication.throttle` to 0 is that based off of the config specifications
 for [follower](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#follower-replication-throttled-rate) and [leader](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#leader-replication-throttled-rate) throttled rates, the upper bound on inbound/outbound replication traffic would be 0 bytes/second, causing there to be no partition movements. 

I tried testing this out and saw that no movements were being made: 
<img width="1366" alt="image" src="https://github.com/linkedin/cruise-control/assets/39936353/a69453a2-b1ae-4837-9300-a0544df1000c">

In addition, CC would not use the `default.replication.throttle` config if an existing static/dynamic broker configuration is already in place because of the [setIfUnset](https://github.com/linkedin/cruise-control/blob/2cdc79db1840d9e2951eeb43a33f236be03e8689/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L186) logic.

I propose that if a user asks CC to rebalance using `default.replication.throttle` config, the value should overwrite any static/dynamic broker config that may already exist on the Kafka side. What do you think?

**Comment by CCisGG** [comment]
> My concern with setting default.replication.throttle to 0 is that based off of the config specifications
for [follower](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#follower-replication-throttled-rate) and [leader](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#leader-replication-throttled-rate) throttled rates, the upper bound on inbound/outbound replication traffic would be 0 bytes/second, causing there to be no partition movements.

@rosakng Just realize it, and you are absolutely right. I think override the config makes more senses. Do we need to remove the override after the rebalance? I'm not super sure about it but might be something to consider. Please feel free to work on that and I'll review it as needed.

**Comment by rosakng** [comment]
@CCisGG Yup, it seems to make sense to remove the override after the rebalance just like how the throttled rates are [removed](https://github.com/linkedin/cruise-control/blob/2cdc79db1840d9e2951eeb43a33f236be03e8689/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/executor/ReplicationThrottleHelper.java#L342) when it is cleared. Will have a PR up soon!
