### ISSUE TITLE
Configurable Prometheus path

### ISSUE THREAD

**Issue by tobbbles** [linkedin/cruise-control#2081]
Hi team. Currently the prometheus query path is [hardcoded](https://github.com/linkedin/cruise-control/blob/535ea07e8847990cc02dde1f1be99b387dbeaf5b/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusAdapter.java#L36). This makes it difficult to utilize tools such as [Mimir](https://grafana.com/docs/mimir/latest/references/http-api/#path-prefixes) as this introduces `/prometheus` prefix to all API paths, and I imagine it's possible that other users are running their Prometheus server(s) behind a proxy with varying paths.

I'd propose a way to make this configurable, with the current value (`/api/v1/query_range`) as a default.

**Comment by mhratson** [comment]
please review #2120 as the solution
