### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by yangmuye-c** [linkedin/cruise-control#2119]
The information about the abnormal cause of the failure to send messages can be printed out here to facilitate troubleshooting
![image](https://github.com/linkedin/cruise-control/assets/123084338/45e463b2-049e-4382-878b-f18ac32f3335)

**Comment by CCisGG** [comment]
Hey thanks for pointing this out. Please feel free to make a PR to address it!

**Comment by kabs31** [comment]
hey @1299618103 is this issue open, if it is can you elaborate on what needs to be done?

**Comment by 1299618103** [comment]
> hey @1299618103 is this issue open, if it is can you elaborate on what needs to be done?

Ok. I'm trying to submit a PR

**Comment by 1299618103** [comment]
> hey @1299618103 is this issue open, if it is can you elaborate on what needs to be done?

Need to send a Kafka message, if there is an exception, the exception information is printed, the current only printed a message body, it is not good to locate the cause of the fault
