### ISSUE TITLE
Is there a final jar available with all dependency jars in jfrog

### ISSUE THREAD

**Issue by sappusaketh** [linkedin/cruise-control#2151]
I have downloaded cruise control , core and metrics jar from [jfrog](https://linkedin.jfrog.io/ui/repos/tree/General/cruise-control) now I m trying to start cruise control with `./kafka-cruise-control-start.sh config/cruisecontrol.properties`
but getting error 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.<clinit>(KafkaCruiseControlMain.java:18)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```
I think its because dependency jars are missing in class path anyway to download jars from jfrog and start cruise control?

**Comment by marcelloromani** [comment]
What worked in my experience is performing the build before attempting to start CC with the shell script.

**Comment by sappusaketh** [comment]
ya currently doing that but trying to see if I can reduce my build time by downloading already built jar

**Comment by marcelloromani** [comment]
I don't think build time is the issue here. How many times do you need to build CC's jars? Once per version. If you need to re-build CC every time you deploy then you have an issue in your pipeline.
Just build CC, store the resulting jars somewhere and consume them.

**Comment by sappusaketh** [comment]
>How many times do you need to build CC's jars? Once per version
Its once per version but My docker file do have other components like CC UI and nginx and if I have to change anything in dockerfile I m building the jars

**Comment by marcelloromani** [comment]
We solved the issue by having one repository build and publishing the jars.
Another repo uses those jars and adds CC UI and other minor bits that we need in our specific use case.
In other words, separate building CC and building other stuff.

**Comment by mhratson** [comment]
> Other option I considered is building CC in to its own docker image and reference it in my docker file which has other components but that will add additional things to manage in my cicd so planning to see if there is a way I can reduce build times during docker build using existing jars published to jfrog

Maybe multistage docker build or build caches can help?
In any case not a CC issue.
