### ISSUE TITLE
KafkaConsumer is not safe for multi-threaded access

### ISSUE THREAD

**Issue by Dylan-DIB** [linkedin/cruise-control#2176]
Good morning,

I am working on a project and have found some issues while attempting to utilize cruise control for rebalancing purposes. Upon trying to use the tool, I ran into the error in the screenshot. I have also attached screenshots of the YAML configurations for review! Please let me know if you need more information. I would appreciate any support you can provide. 

-- SCREENSHOT OF ERROR --

![image](https://github.com/user-attachments/assets/bf13e589-4f47-42ce-9587-18a135468886)

---YAML FILE---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[100-199]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: kafkanodepool1
spec:
  replicas: 2
  roles:
  - broker
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 512Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/broker-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[200-299]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: kafkanodepool2
spec:
  replicas: 2
  roles:
  - broker
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 512Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-2
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/broker-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[300-399]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: kafkanodepool3
spec:
  replicas: 2
  roles:
  - broker
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 512Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-3
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/broker-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[10-19]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: controllernodepool1
spec:
  replicas: 1
  roles:
  - controller
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 32Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/controller-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[20-29]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: controllernodepool2
spec:
  replicas: 1
  roles:
  - controller
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 32Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-2
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/controller-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    strimzi.io/next-node-ids: '[30-39]'
  labels:
    strimzi.io/cluster: kafkacl3
  name: controllernodepool3
spec:
  replicas: 1
  roles:
  - controller
  storage:
    type: jbod
    volumes:
    - class: premium2-disk-sc-256-min
      deleteClaim: true
      id: 0
      size: 32Gi
      type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eastus-3
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/controller-role
                operator: In
                values:
                - 'true'
            topologyKey: kubernetes.io/hostname
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
      tolerations:
      - effect: NoSchedule
        key: KafkaOnly
        operator: Equal
        value: 'true'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    prometheus.io/port: '9404'
    prometheus.io/scrape: 'true'
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: kafkacl3
spec:
  clusterCa:
    generateCertificateAuthority: false
  cruiseControl:
    config:
      max.replicas.per.broker: 30000
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: metrics-config.yml
          name: cruise-control-metrics
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/port: '9404'
            prometheus.io/scrape: 'true'
        tolerations:
        - effect: NoSchedule
          key: CoreAppOnly
          operator: Equal
          value: 'true'
  entityOperator:
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/port: '9404'
            prometheus.io/scrape: 'true'
        tolerations:
        - effect: NoSchedule
          key: CoreAppOnly
          operator: Equal
          value: 'true'
      topicOperatorContainer:
        env:
        - name: STRIMZI_MAX_QUEUE_SIZE
          value: '6144'
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: false
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: tls
      port: 9093
      tls: true
      type: internal
    - configuration:
        bootstrap:
          alternativeNames:
          - kafkacl3-kafka-externaltls-bootstrap.akscl3.portaldev.exampledomain.com
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.13
        brokers:
        - advertisedHost: kafkacl3-kafkanodepool1-externaltls-100.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.14
          broker: 100
        - advertisedHost: kafkacl3-kafkanodepool2-externaltls-200.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.15
          broker: 200
        - advertisedHost: kafkacl3-kafkanodepool3-externaltls-300.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.16
          broker: 300
        - advertisedHost: kafkacl3-kafkanodepool1-externaltls-101.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.17
          broker: 101
        - advertisedHost: kafkacl3-kafkanodepool2-externaltls-201.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.18
          broker: 201
        - advertisedHost: kafkacl3-kafkanodepool3-externaltls-301.akscl3.portaldev.exampledomain.com
          advertisedPort: 19092
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
            service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.43.94.19
          broker: 301
      name: externaltls
      port: 19092
      tls: true
      type: loadbalancer
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    rack:
      topologyKey: topology.kubernetes.io/zone
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: true
        id: 0
        size: 64Gi
        type: persistent-claim
    version: 3.7.0
  kafkaExporter:
    groupRegex: .*
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/port: '9404'
            prometheus.io/scrape: 'true'
        tolerations:
        - effect: NoSchedule
          key: CoreAppOnly
          operator: Equal
          value: 'true'
    topicRegex: .*
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      deleteClaim: true
      size: 64Gi
      type: persistent-claim
---
apiVersion: v1
data:
  kafka-metrics-config.yml: "# See https://github.com/prometheus/jmx_exporter for\
    \ more info about JMX Prometheus Exporter metrics\nlowercaseOutputName: true\n\
    rules:\n# Special cases and very specific rules\n- pattern: kafka.server<type=(.+),\
    \ name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value\n  name: kafka_server_$1_$2\n\
    \  type: GAUGE\n  labels:\n    clientId: \"$3\"\n    topic: \"$4\"\n    partition:\
    \ \"$5\"\n- pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),\
    \ brokerPort=(.+)><>Value\n  name: kafka_server_$1_$2\n  type: GAUGE\n  labels:\n\
    \    clientId: \"$3\"\n    broker: \"$4:$5\"\n- pattern: kafka.server<type=(.+),\
    \ cipher=(.+), protocol=(.+), listener=(.+), networkProcessor=(.+)><>connections\n\
    \  name: kafka_server_$1_connections_tls_info\n  type: GAUGE\n  labels:\n    cipher:\
    \ \"$2\"\n    protocol: \"$3\"\n    listener: \"$4\"\n    networkProcessor: \"\
    $5\"\n- pattern: kafka.server<type=(.+), clientSoftwareName=(.+), clientSoftwareVersion=(.+),\
    \ listener=(.+), networkProcessor=(.+)><>connections\n  name: kafka_server_$1_connections_software\n\
    \  type: GAUGE\n  labels:\n    clientSoftwareName: \"$2\"\n    clientSoftwareVersion:\
    \ \"$3\"\n    listener: \"$4\"\n    networkProcessor: \"$5\"\n- pattern: \"kafka.server<type=(.+),\
    \ listener=(.+), networkProcessor=(.+)><>(.+):\"\n  name: kafka_server_$1_$4\n\
    \  type: GAUGE\n  labels:\n    listener: \"$2\"\n    networkProcessor: \"$3\"\n\
    - pattern: kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+)\n\
    \  name: kafka_server_$1_$4\n  type: GAUGE\n  labels:\n    listener: \"$2\"\n\
    \    networkProcessor: \"$3\"\n# Some percent metrics use MeanRate attribute\n\
    # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate\n\
    - pattern: kafka.(\\w+)<type=(.+), name=(.+)Percent\\w*><>MeanRate\n  name: kafka_$1_$2_$3_percent\n\
    \  type: GAUGE\n# Generic gauges for percents\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+)Percent\\w*><>Value\n  name: kafka_$1_$2_$3_percent\n  type: GAUGE\n\
    - pattern: kafka.(\\w+)<type=(.+), name=(.+)Percent\\w*, (.+)=(.+)><>Value\n \
    \ name: kafka_$1_$2_$3_percent\n  type: GAUGE\n  labels:\n    \"$4\": \"$5\"\n\
    # Generic per-second counters with 0-2 key/value pairs\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+)PerSec\\w*, (.+)=(.+), (.+)=(.+)><>Count\n  name: kafka_$1_$2_$3_total\n\
    \  type: COUNTER\n  labels:\n    \"$4\": \"$5\"\n    \"$6\": \"$7\"\n- pattern:\
    \ kafka.(\\w+)<type=(.+), name=(.+)PerSec\\w*, (.+)=(.+)><>Count\n  name: kafka_$1_$2_$3_total\n\
    \  type: COUNTER\n  labels:\n    \"$4\": \"$5\"\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+)PerSec\\w*><>Count\n  name: kafka_$1_$2_$3_total\n  type: COUNTER\n\
    # Generic gauges with 0-2 key/value pairs\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+), (.+)=(.+), (.+)=(.+)><>Value\n  name: kafka_$1_$2_$3\n  type: GAUGE\n\
    \  labels:\n    \"$4\": \"$5\"\n    \"$6\": \"$7\"\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+), (.+)=(.+)><>Value\n  name: kafka_$1_$2_$3\n  type: GAUGE\n  labels:\n\
    \    \"$4\": \"$5\"\n- pattern: kafka.(\\w+)<type=(.+), name=(.+)><>Value\n  name:\
    \ kafka_$1_$2_$3\n  type: GAUGE\n# Emulate Prometheus 'Summary' metrics for the\
    \ exported 'Histogram's.\n# Note that these are missing the '_sum' metric!\n-\
    \ pattern: kafka.(\\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count\n \
    \ name: kafka_$1_$2_$3_count\n  type: COUNTER\n  labels:\n    \"$4\": \"$5\"\n\
    \    \"$6\": \"$7\"\n- pattern: kafka.(\\w+)<type=(.+), name=(.+), (.+)=(.*),\
    \ (.+)=(.+)><>(\\d+)thPercentile\n  name: kafka_$1_$2_$3\n  type: GAUGE\n  labels:\n\
    \    \"$4\": \"$5\"\n    \"$6\": \"$7\"\n    quantile: \"0.$8\"\n- pattern: kafka.(\\\
    w+)<type=(.+), name=(.+), (.+)=(.+)><>Count\n  name: kafka_$1_$2_$3_count\n  type:\
    \ COUNTER\n  labels:\n    \"$4\": \"$5\"\n- pattern: kafka.(\\w+)<type=(.+), name=(.+),\
    \ (.+)=(.*)><>(\\d+)thPercentile\n  name: kafka_$1_$2_$3\n  type: GAUGE\n  labels:\n\
    \    \"$4\": \"$5\"\n    quantile: \"0.$6\"\n- pattern: kafka.(\\w+)<type=(.+),\
    \ name=(.+)><>Count\n  name: kafka_$1_$2_$3_count\n  type: COUNTER\n- pattern:\
    \ kafka.(\\w+)<type=(.+), name=(.+)><>(\\d+)thPercentile\n  name: kafka_$1_$2_$3\n\
    \  type: GAUGE\n  labels:\n    quantile: \"0.$4\"\n# KRaft mode: uncomment the\
    \ following lines to export KRaft related metrics\n# KRaft overall related metrics\n\
    # distinguish between always increasing COUNTER (total and max) and variable GAUGE\
    \ (all others) metrics\n- pattern: \"kafka.server<type=raft-metrics><>(.+-total|.+-max):\"\
    \n  name: kafka_server_raftmetrics_$1\n  type: COUNTER\n- pattern: \"kafka.server<type=raft-metrics><>(.+):\"\
    \n  name: kafka_server_raftmetrics_$1\n  type: GAUGE\n# KRaft \"low level\" channels\
    \ related metrics\n# distinguish between always increasing COUNTER (total and\
    \ max) and variable GAUGE (all others) metrics\n- pattern: \"kafka.server<type=raft-channel-metrics><>(.+-total|.+-max):\"\
    \n  name: kafka_server_raftchannelmetrics_$1\n  type: COUNTER\n- pattern: \"kafka.server<type=raft-channel-metrics><>(.+):\"\
    \n  name: kafka_server_raftchannelmetrics_$1\n  type: GAUGE\n# Broker metrics\
    \ related to fetching metadata topic records in KRaft mode\n- pattern: \"kafka.server<type=broker-metadata-metrics><>(.+):\"\
    \n  name: kafka_server_brokermetadatametrics_$1\n  type: GAUGE\n"
  zookeeper-metrics-config.yml: "# See https://github.com/prometheus/jmx_exporter\
    \ for more info about JMX Prometheus Exporter metrics\nlowercaseOutputName: true\n\
    rules:\n# replicated Zookeeper\n- pattern: \"org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\\
    \\d+)><>(\\\\w+)\"\n  name: \"zookeeper_$2\"\n  type: GAUGE\n- pattern: \"org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\\
    \\d+), name1=replica.(\\\\d+)><>(\\\\w+)\"\n  name: \"zookeeper_$3\"\n  type:\
    \ GAUGE\n  labels:\n    replicaId: \"$2\"\n- pattern: \"org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\\
    \\d+), name1=replica.(\\\\d+), name2=(\\\\w+)><>(Packets\\\\w+)\"\n  name: \"\
    zookeeper_$4\"\n  type: COUNTER\n  labels:\n    replicaId: \"$2\"\n    memberType:\
    \ \"$3\"\n- pattern: \"org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\\
    \\d+), name1=replica.(\\\\d+), name2=(\\\\w+)><>(\\\\w+)\"\n  name: \"zookeeper_$4\"\
    \n  type: GAUGE\n  labels:\n    replicaId: \"$2\"\n    memberType: \"$3\"\n- pattern:\
    \ \"org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\\\d+), name1=replica.(\\\
    \\d+), name2=(\\\\w+), name3=(\\\\w+)><>(\\\\w+)\"\n  name: \"zookeeper_$4_$5\"\
    \n  type: GAUGE\n  labels:\n    replicaId: \"$2\"\n    memberType: \"$3\"\n"
kind: ConfigMap
metadata:
  labels:
    app: strimzi
  name: kafka-metrics
---
apiVersion: v1
data:
  metrics-config.yml: "# See https://github.com/prometheus/jmx_exporter for more info\
    \ about JMX Prometheus Exporter metrics\nlowercaseOutputName: true\nrules:\n-\
    \ pattern: kafka.cruisecontrol<name=(.+)><>(\\w+)\n  name: kafka_cruisecontrol_$1_$2\n\
    \  type: GAUGE"
kind: ConfigMap
metadata:
  labels:
    app: strimzi
  name: cruise-control-metrics

**Comment by mhratson** [comment]
Sorry this is a kafka consumer issue. Refer to kafka resources for help.
