### ISSUE TITLE
Error removing broker and moving replicas to single destination broker

### ISSUE THREAD

**Issue by HonestTelevision** [linkedin/cruise-control#2184]
I am trying to implement an automated graceful host replacement workflow using cruise control, the gist of it is:
1. Add broker to a kafka cluster
2. Call cruise control remove_brokers endpoint to move partitions from old broker to new broker
3. Delete old broker from cluster after it is emptied.

However, cruise control throws some very strange errors when I try to run the remove broker call. My request looks like:
> `/kafkacruisecontrol/remove_broker?brokerid=1016&&dryrun=false&&skip_hard_goal_check=true&&throttle_removed_broker=false&&destination_broker_ids=1001&&json=true`

And the error message looks like:
> `Error processing POST request '/remove_broker' due to: 'com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [ReplicaCapacityGoal] Failed to move dead broker replica Replica[isLeader=false,rack=<redacted>,broker=1016,TopicPartition=<redacted>,origBroker=1016,isOriginalOffline=true,isCurrentOffline=true] of partition <Partition>\n<Leader>Replica[isLeader=true,rack=<redacted>,broker=1018,TopicPartition=<redacted>,origBroker=1018,isOriginalOffline=false,isCurrentOffline=false]</Leader>\n<Follower>Replica[isLeader=false,rack=<redacted>,broker=1016,TopicPartition=<redacted>,origBroker=1016,isOriginalOffline=true,isCurrentOffline=true]</Follower>\n<Follower>Replica[isLeader=false,rack=<redacted>,broker=1001,TopicPartition=<redacted>,origBroker=1001,isOriginalOffline=false,isCurrentOffline=false]</Follower>\n</Partition>%n to a broker in [Broker[id=1001,rack=<redacted>,state=ALIVE,replicaCount=18,logdirs=[]], Broker[id=1002,rack=<redacted>,state=ALIVE,replicaCount=76,logdirs=[]], Broker[id=1003,rack=<redacted>,state=ALIVE,replicaCount=77,logdirs=[]], Broker[id=1018,rack=<redacted>,state=ALIVE,replicaCount=121,logdirs=[]]]. Per broker limit: 10000 for brokers: [Broker[id=1001,rack=<redacted>,state=ALIVE,replicaCount=18,logdirs=[]], Broker[id=1002,rack=<redacted>,state=ALIVE,replicaCount=76,logdirs=[]], Broker[id=1003,rack=<redacted>,state=ALIVE,replicaCount=77,logdirs=[]], Broker[id=1016,rack=<redacted>,state=DEAD,replicaCount=63,logdirs=[]], Broker[id=1018,rack=<redacted>,state=ALIVE,replicaCount=121,logdirs=[]]] Add at least 1 broker. || Tips: [1] The destination brokers are limited to [1001]. Potential mitigation: Relax the constraint on destination brokers using destination_broker_ids parameter. Then, re-run your original request. Add at least 1 broker`

The error message is strange because that broker certainly isn't dead. Also, if I just increase the number of destination brokers to 3, then the remove_broker request goes through. But that's not what I'm looking for as I'm trying to copy brokers onto specifically one broker.

I've tried playing around with different goals to resolve this. However regardless of which goals I pick, I still get an error. With RackAwareGoal or RackAwareDistributionGoal I get a rack awareness error. With PreferredLeaderElectionGoal I don't get an error returned, but then the request does absolutely nothing. Looking at the cruise-control code, this error may be stemming from a call to `AbstractGoal.maybeApplyBalancingAction`. It may also be due to a broker being incorrectly marked dead.

Can someone help me figure out what's going on here?

**Comment by mhratson** [comment]
> But that's not what I'm looking for as I'm trying to copy brokers onto specifically one broker.

CC's remove_broker would try to balance replicas across rest of the cluster, and providing only broker fails the configured goals as you've discovered since using all brokers works fine. 

It could be an interesting usecase to create a copy of a broker, but evidently that's not how it's working in your case.

**Comment by HonestTelevision** [comment]
Is there a way to call remove_broker with one destination node? Is there some goal configuration that would work? Because regardless of which goal configuration I tested, it always failed (or did nothing). 

Is moving replicas from one broker onto another single broker not possible with Cruise Control?

**Comment by HonestTelevision** [comment]
@mhratson Following up
