### ISSUE TITLE
Metric Anomaly Detector NPE

### ISSUE THREAD

**Issue by TheyDroppedMe** [linkedin/cruise-control#219]
After rebuilding off of head for the fixes in #217  , I see these in the logs a lot.

`[2018-05-07 13:38:55,817] WARN Metric Anomaly Detector encountered exception:  (com.linkedin.kafka.cruisecontrol.detector.MetricAnomalyDetector)
java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
	at java.util.Collections.unmodifiableList(Collections.java:1287)
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.ValuesAndExtrapolations.windows(ValuesAndExtrapolations.java:63)
	at com.linkedin.cruisecontrol.detector.metricanomaly.PercentileMetricAnomalyFinder.metricAnomalies(PercentileMetricAnomalyFinder.java:136)
	at com.linkedin.kafka.cruisecontrol.detector.MetricAnomalyDetector.run(MetricAnomalyDetector.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by TheyDroppedMe** [comment]
Thanks for the quick fix. Unfortunately, It seems like this version is giving these errors again:

`[2018-05-08 13:06:20,238] ERROR Metric loader received exception: (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)
java.lang.IllegalArgumentException: Cannot add sample to window index 5084195, which is larger than the current window index 5084177
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.RawMetricValues.addSample(RawMetricValues.java:79)
	at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.addSample(MetricSampleAggregator.java:162)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.addSample(KafkaPartitionMetricSampleAggregator.java:88)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.SampleStore$SampleLoader.loadSamples(SampleStore.java:65)
	at com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore$MetricLoader.run(KafkaSampleStore.java:354)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by efeg** [comment]
Hi @TheyDroppedMe, can tou share the githash you are running? We had a recent fix for this particular issue.

**Comment by TheyDroppedMe** [comment]
Built off of HEAD this morning - ef70e47

**Comment by TheyDroppedMe** [comment]
Also seeing some strange behavior with proposals: it appears that this current build never gets proposals ready.

In the log, all I see is a constant stream of anomalies, and even when trying to get a proposal for a single ready goal, it never produces one.

`[2018-05-09` 12:48:20,008] WARN Anomaly detected {
Metric Anomaly windows: [1525870800000] description: Metric value 940.254 of BROKER_LOG_FLUSH_TIME_MS_MAX for entity brokerId=1111,host=1111 in window 2018-00-09_01:00:00 is out of the normal percentile range [10.00, 90.00] (value range: [936.074, 940.254]) in history windows from 2018-00-09_12:00:00 to 2018-00-08_05:00:00
}. Self healing is disabled. (com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier)
[2018-05-09 12:48:20,030] WARN Anomaly detected {
Metric Anomaly windows: [1525870800000] description: Metric value 2.550 of BROKER_LOG_FLUSH_TIME_MS_MEAN for entity brokerId=1111,host=1111 in window 2018-00-09_01:00:00 is out of the normal percentile range [10.00, 90.00] (value range: [2.534, 2.549]) in history windows from 2018-00-09_12:00:00 to 2018-00-08_05:00:00
}. Self healing is disabled. (com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier)
[2018-05-09 12:48:20,030] WARN Anomaly detected {
Metric Anomaly windows: [1525870800000] description: Metric value 2.550 of BROKER_LOG_FLUSH_TIME_MS_MEAN for entity brokerId=1111,host=1111 in window 2018-00-09_01:00:00 is out of the normal percentile range [10.00, 90.00] (value range: [2.534, 2.549]) in history windows from 2018-00-09_12:00:00 to 2018-00-08_05:00:00
}. Self healing is disabled. (com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier)

{
    "AnalyzerState": {
        "isProposalReady": false,
        "readyGoals": [
            {
                "goal": "NetworkInboundUsageDistributionGoal"
            },
            {
                "goal": "CpuUsageDistributionGoal"
            },
            {
                "goal": "PotentialNwOutGoal"
            },
            {
                "goal": "ReplicaDistributionGoal"
            },
            {
                "goal": "DiskCapacityGoal"
            },
            {
                "goal": "NetworkInboundCapacityGoal"
            },
            {
                "goal": "LeaderBytesInDistributionGoal"
            },
            {
                "goal": "RackAwareGoal"
            },
            {
                "goal": "TopicReplicaDistributionGoal"
            },
            {
                "goal": "CpuCapacityGoal"
            },
            {
                "goal": "DiskUsageDistributionGoal"
            },
            {
                "goal": "NetworkOutboundCapacityGoal"
            },
            {
                "goal": "ReplicaCapacityGoal"
            },
            {
                "goal": "NetworkOutboundUsageDistributionGoal"
            }
        ]
    },
    "ExecutorState": {
        "state": "NO_TASK_IN_PROGRESS"
    },
    "MonitorState": {
        "monitoredWindows": {
            "1525870200000": 1.0
        },
        "monitoringCoveragePct": 100.0,
        "numFlawedPartitions": 0,
        "numMonitoredWindows": 1,
        "numTotalPartitions": 1586,
        "numValidPartitions": 1586,
        "state": "RUNNING",
        "trained": "false",
        "trainingPct": 20.0
    },
    "version": 1
}
`

This has been running for almost 2 days now - is that normal for it to take so long to generate a proposal? Two commits ago it generated a proposal in just a few minutes.

**Comment by TheyDroppedMe** [comment]
To clarify, proposals generate and work as expected up until commit c351cad. Is it possible that fixing the metric anomaly detector caused so much work it keeps the proposals from generating? I can get a thread dump if that might help

**Comment by efeg** [comment]
Metric anomaly detector and proposal generation should not be blocking each other. One reason why we might see `isProposalReady=false` would be setting `num.proposal.precompute.threads=0` in `cruisecontrol.properties`. Can you verify that this is not the case? Would you share how you were testing proposal generation before? -- i.e. via proposals endpoint or via `rebalance` / `add_broker` / `remove_broker` (with `dryrun=true`)?

Yes, a thread dump would be helpful to determine where the computation seems to be stuck.

**Comment by TheyDroppedMe** [comment]
Strange. I definitely get the expected behavior with c351cad, and the perpetual isProposalReady=false with later commits. I was testing by getting the state, and also by trying the rebalance endpoint in dry-run mode. I used 34d32dc to do a few rebalances previously, so it seems like something has changed (although who knows if it's on my end). Here's my full config:

`# This file has been generated by Chef.
# Modifications will be overwritten.

bootstrap.servers=<list of brokers>
num.metric.fetchers=1
metric.sampler.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler
metric.reporter.topic.pattern=__CruiseControlMetrics
sample.store.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore
partition.metric.sample.store.topic=__KafkaCruiseControlPartitionMetricSamples
broker.metric.sample.store.topic=__KafkaCruiseControlModelTrainingSamples
num.sample.loading.threads=8
metric.sampler.partition.assignor.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.DefaultMetricSamplerPartitionAssignor
metric.sampling.interval.ms=120000
partition.metrics.window.ms=300000
num.partition.metrics.windows=1
min.samples.per.partition.metrics.window=1
broker.metrics.window.ms=30000
num.broker.metrics.windows=20
min.samples.per.broker.metrics.window=1
capacity.config.file=/etc/cruise-control/capacity.json
default.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal
goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerEvenRackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PreferredLeaderElectionGoal
min.monitored.partition.percentage=0.95
cpu.balance.threshold=1.1
disk.balance.threshold=1.1
network.inbound.balance.threshold=1.1
network.outbound.balance.threshold=1.1
replica.count.balance.threshold=1.1
cpu.capacity.threshold=0.8
disk.capacity.threshold=0.8
network.inbound.capacity.threshold=0.8
network.outbound.capacity.threshold=0.8
cpu.low.utilization.threshold=0.0
disk.low.utilization.threshold=0.0
network.inbound.low.utilization.threshold=0.0
network.outbound.low.utilization.threshold=0.0
metric.anomaly.percentile.upper.threshold=90.0
metric.anomaly.percentile.lower.threshold=10.0
max.proposal.candidates=10
proposal.expiration.ms=60000
max.replicas.per.broker=10000
num.proposal.precompute.threads=2
topics.excluded.from.partition.movement=(kafka-monitor-topic|__consumer_offsets)
zookeeper.connect=confluent-hold-uscen-a-c001-n001:2181,confluent-hold-uscen-b-c001-n002:2181,confluent-hold-uscen-c-c001-n003:2181
num.concurrent.partition.movements.per.broker=1
execution.progress.check.interval.ms=10000
anomaly.notifier.class=com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier
metric.anomaly.finder.class=com.linkedin.kafka.cruisecontrol.detector.KafkaMetricAnomalyFinder
anomaly.detection.interval.ms=10000
anomaly.detection.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal
metric.anomaly.analyzer.metrics=BROKER_PRODUCE_LOCAL_TIME_MS_MAX,BROKER_PRODUCE_LOCAL_TIME_MS_MEAN,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MAX,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MAX,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_LOG_FLUSH_TIME_MS_MAX,BROKER_LOG_FLUSH_TIME_MS_MEAN
failed.brokers.zk.path=/CruiseControlBrokerList
self.healing.enabled=false
`

**Comment by becketqin** [comment]
@TheyDroppedMe Thanks for reporting the issue. It looks that our default config for broker.metrics.window.ms was set to 30 seconds instead of 300 seconds... We'll fix that. But it is still a little strange that the proposal generation stuck. Is it possible for you to take a thread dump?

**Comment by ravieze** [comment]
[issue.log](https://github.com/linkedin/cruise-control/files/2241276/issue.log)
Any update? i m currently running on head version of cruise control. I get the below error. Attached the full log also.

> [2018-07-30 13:22:51,263] ERROR Unexpected exception (com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector)
> java.lang.IllegalArgumentException: Index 5109854 is out of range [5109852, 5109852]
>         at com.linkedin.cruisecontrol.common.WindowIndexedArrays.validateIndex(WindowIndexedArrays.java:45)
>         at com.linkedin.cruisecontrol.monitor.sampling.aggregator.RawMetricValues.isExtrapolatedAtWindowIndex(RawMetricValues.java:174)
>         at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.getWindowState(MetricSampleAggregator.java:450)
>         at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.maybeUpdateAggregatorState(MetricSampleAggregator.java:441)
>         at com.linkedin.cruisecontrol.monitor.sampling.aggregator.MetricSampleAggregator.completeness(MetricSampleAggregator.java:277)
>         at com.linkedin.kafka.cruisecontrol.monitor.sampling.aggregator.KafkaPartitionMetricSampleAggregator.validWindows(KafkaPartitionMetricSampleAggregator.java:191)
>         at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.meetCompletenessRequirements(LoadMonitor.java:527)
>         at com.linkedin.kafka.cruisecontrol.monitor.LoadMonitor.meetCompletenessRequirements(LoadMonitor.java:539)
>         at com.linkedin.kafka.cruisecontrol.detector.GoalViolationDetector.run(GoalViolationDetector.java:108)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

btw, i changed the cruise-control.properties like in below

> # Configurations for the analyzer
> # =======================================
> 
> # The list of goals to optimize the Kafka cluster for with pre-computed proposals
> default.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal
>

**Comment by saritago** [comment]
@becketqin @efeg  I see that my broker.metrics.window.ms is set to 300 seconds and yet i continue to see warnings as below
```
Metric Anomaly windows: [1548939600000] description: Metric value 19.872 of BROKER_LOG_FLUSH_TIME_MS_MAX for brokerId=101,host=xxxxx in window 2019-01-31_01:00:00 is out of the normal range for percentile: [49.00, 51.00] (value: [2.271, 18.154] with margins (lower: 0.200, upper: 0.500)) in 20 history windows from 2019-01-31_12:00:00 to 2019-01-30_05:00:00.
}. Self healing is disabled. (com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier)
```
my properties file looks like below
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cruisecontrol-configmap-ksql
data:
  server.properties: |

    #
    # Copyright 2017 LinkedIn Corp. Licensed under the BSD 2-Clause License (the "License"). See License in the project root for license information.
    #

    # This is an example property file for Kafka Cruise Control. See KafkaCruiseControlConfig for more details.

    # Configuration for the metadata client.
    # =======================================

    # The Kafka cluster to control.
    bootstrap.servers=
    # The maximum interval in milliseconds between two metadata refreshes.
    #metadata.max.age.ms=300000

    # Client id for the Cruise Control. It is used for the metadata client.
    #clients.id=kafka-cruise-control

    # The size of TCP send buffer bytes for the metadata client.
    #send.buffer.bytes=131072

    # The size of TCP receive buffer size for the metadata client.
    #receive.buffer.bytes=131072

    # The time to wait before disconnect an idle TCP connection.
    #connections.max.idle.ms=540000

    # The time to wait before reconnect to a given host.
    #reconnect.backoff.ms=50

    # The time to wait for a response from a host after sending a request.
    #request.timeout.ms=30000


    # Configurations for the load monitor
    # =======================================

    # The number of metric fetcher thread to fetch metrics for the Kafka cluster
    num.metric.fetchers=1

    # The metric sampler class
    metric.sampler.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler
    # Configurations for CruiseControlMetricsReporterSampler
    metric.reporter.topic.pattern=__CruiseControlMetrics

    # The sample store class name
    sample.store.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore

    # The config for the Kafka sample store to save the partition metric samples.
    partition.metric.sample.store.topic=__KafkaCruiseControlPartitionMetricSamples

    # The config for the Kafka sample store to save the model training samples.
    broker.metric.sample.store.topic=__KafkaCruiseControlModelTrainingSamples

    # The config for the number of Kafka sample store consumer threads.
    num.sample.loading.threads=8

    # The partition assignor class for the metric samplers.
    metric.sampler.partition.assignor.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.DefaultMetricSamplerPartitionAssignor

    # The metric sampling interval in milliseconds
    metric.sampling.interval.ms=120000

    # The partition metrics window size in milliseconds
    partition.metrics.window.ms=300000

    # The number of partition metric windows to keep in memory
    num.partition.metrics.windows=1

    # The minimum partition metric samples required for a partition in each window
    min.samples.per.partition.metrics.window=1

    # The broker metrics window size in milliseconds
    broker.metrics.window.ms=300000

    # The number of broker metric windows to keep in memory
    num.broker.metrics.windows=20

    # The minimum broker metric samples required for a partition in each window
    min.samples.per.broker.metrics.window=1

    # The configuration for the BrokerCapacityConfigFileResolver
    capacity.config.file=/cruise-control-master/config/capacity.json

    # Configurations for the analyzer
    # =======================================

    # The list of goals to optimize the Kafka cluster for with pre-computed proposals
    default.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal

    # The list of goals that is supported.
    goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PreferredLeaderElectionGoal

    # The minimum percentage of well monitored partitions out of all the partitions
    min.monitored.partition.percentage=0.95

    # The balance threshold for CPU
    cpu.balance.threshold=1.1

    # The balance threshold for disk
    disk.balance.threshold=1.1

    # The balance threshold for network inbound utilization
    network.inbound.balance.threshold=1.1

    # The balance threshold for network outbound utilization
    network.outbound.balance.threshold=1.1

    # The balance threshold for the replica count
    replica.count.balance.threshold=1.1

    # The capacity threshold for CPU in percentage
    cpu.capacity.threshold=0.8

    # The capacity threshold for disk in percentage
    disk.capacity.threshold=0.97

    # The capacity threshold for network inbound utilization in percentage
    network.inbound.capacity.threshold=0.8

    # The capacity threshold for network outbound utilization in percentage
    network.outbound.capacity.threshold=0.8

    # The threshold to define the cluster to be in a low CPU utilization state
    cpu.low.utilization.threshold=0.0

    # The threshold to define the cluster to be in a low disk utilization state
    disk.low.utilization.threshold=0.0

    # The threshold to define the cluster to be in a low network inbound utilization state
    network.inbound.low.utilization.threshold=0.0

    # The threshold to define the cluster to be in a low disk utilization state
    network.outbound.low.utilization.threshold=0.0

    # The metric anomaly percentile upper threshold
    metric.anomaly.percentile.upper.threshold=51.0

    # The metric anomaly percentile lower threshold
    metric.anomaly.percentile.lower.threshold=49.0

    # How often should the cached proposal be expired and recalculated if necessary
    proposal.expiration.ms=60000

    # The maximum number of replicas that can reside on a broker at any given time.
    max.replicas.per.broker=10000

    # The number of threads to use for proposal candidate precomputing.
    num.proposal.precompute.threads=1

    # the topics that should be excluded from the partition movement.
    #topics.excluded.from.partition.movement

    # Configurations for the executor
    # =======================================

    # The zookeeper connect of the Kafka cluster
    zookeeper.connect=
    # The max number of partitions to move in/out on a given broker at a given time.
    num.concurrent.partition.movements.per.broker=10

    # The interval between two execution progress checks.
    execution.progress.check.interval.ms=10000


    # Configurations for anomaly detector
    # =======================================

    # The goal violation notifier class
    anomaly.notifier.class=com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier

    # The metric anomaly finder class
    metric.anomaly.finder.class=com.linkedin.kafka.cruisecontrol.detector.KafkaMetricAnomalyFinder

    # The anomaly detection interval
    anomaly.detection.interval.ms=10000

    # The goal violation to detect.
    anomaly.detection.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal

    # The interested metrics for metric anomaly analyzer.
    metric.anomaly.analyzer.metrics=BROKER_PRODUCE_LOCAL_TIME_MS_MAX,BROKER_PRODUCE_LOCAL_TIME_MS_MEAN,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MAX,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MAX,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_LOG_FLUSH_TIME_MS_MAX,BROKER_LOG_FLUSH_TIME_MS_MEAN

    # The zk path to store failed broker information.
    failed.brokers.zk.path=/CruiseControlBrokerList

    # Self-healing enabled
    self.healing.enabled=false

```

**Comment by efeg** [comment]
@saritago To suppress such `WARNs`, you may either (1) change your `metric.anomaly.finder.class` point to `com.linkedin.kafka.cruisecontrol.detector.NoopMetricAnomalyFinder`, or (2) use the metrics specified [here](https://github.com/linkedin/cruise-control/blob/master/config/cruisecontrol.properties#L192) -- i.e. replace them with the [old ones](https://github.com/linkedin/cruise-control/blob/master/config/cruisecontrol.properties#L189).

**Comment by saritago** [comment]
@efeg if i set it option 1, does it stop anomaly detection?

**Comment by efeg** [comment]
@saritago it stops "metric anomaly detection" -- has no impact on goal violation detection or broker failure detector.

**Comment by saritago** [comment]
@efeg +1, will try it and let you know the results. Thank you !

**Comment by efeg** [comment]
Closing the issue as the deadlock issue of the reported version from `May 2018` has already been fixed.
