### ISSUE TITLE
Issue Connecting Cruise Control to Kafka (v2.13-3.6.1) in KRaft Mode with SASL Authentication

### ISSUE THREAD

**Issue by rakhat1607** [linkedin/cruise-control#2198]
We are experiencing a problem connecting Cruise Control to Kafka version 2.13-3.6.1 running in KRaft mode (without ZooKeeper) using SASL authentication.
Logs Kafka:
`Sep 12 11:34:18 ip-10-249-10-248.eu-north-1.compute.internal kafka-server-start.sh[8188]: [2024-09-12 11:34:18,874] INFO [SocketServer listenerType=BROKER, nodeId=0] Failed authentication with /10.249.10.248 (channelId=10.249.10.248:9092-10.249.10.248:40306-151) (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)`
Logs CruiseControle
```
[2024-09-12 11:34:02,979] INFO [AdminClient clientId=adminclient-1] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2024-09-12 11:34:02,980] INFO [AdminClient clientId=adminclient-1] Cancelled in-flight METADATA request with correlation id 9 due to node -1 being disconnected (elapsed time since creation: 302ms, elapsed time since send: 302ms, request timeout: 177368ms) (org.apache.kafka.clients.NetworkClient)
```
configs cruisecontrol.properties :
```
# The zookeeper connect of the Kafka cluster
#zookeeper.connect=localhost:2181/

# If true, appropriate zookeeper Client { .. } entry required in jaas file located at $base_dir/config/cruise_control_jaas.conf
zookeeper.security.enabled=true

kafka.broker.failure.detection.enable=true
```
configs cruise_control_jaas.conf:
```
KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="username"
    password="password";
};
```
If additional data is needed, I am ready to send it

**Comment by mbrother2** [comment]
Hello @rakhat1607 ,

You can try with these configs in `cruisecontrol.properties` file:
```
# The zookeeper connect of the Kafka cluster
#zookeeper.connect=localhost:2181/

# If true, appropriate zookeeper Client { .. } entry required in jaas file located at $base_dir/config/cruise_control_jaas.conf
#zookeeper.security.enabled=true
kafka.broker.failure.detection.enable=true
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \ username="xxxxx" \ password="xxxxx";
```

`security.protocol` and `sasl.mechanism` depends on your kafka cluster configuration

**Comment by rakhat1607** [comment]
Thank you, your advice was really helpful!
