### ISSUE TITLE
add LeaderReplicas to the Json Datastructure of ClusterStats in `ClusterModel.java`

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#223]
Normal formatted string version of cluster stats has `LeaderReplicas` added to it. Put the same value in Json datastructure as well.

**Comment by kidkun** [comment]
Naresh, 
can you put a concrete example here?since from the code I do see that the JSON response returns leader_replica for each partition.

this is JSON return for each partition.
      recordMap.put(TOPIC, partitionInfo.topic());
      recordMap.put(PARTITION, Integer.toString(partitionInfo.partition()));
      recordMap.put(LEADER, Integer.toString(partitionInfo.leader() == null ? -1 : partitionInfo.leader().id()));
      recordMap.put(REPLICAS, replicas.toString());
      recordMap.put(IN_SYNC, inSyncReplicas.toString());
      recordMap.put(OUT_OF_SYNC, outOfSyncReplicas.toString());

which has the same field as normal formatted string version.

      out.write(String.format("%" + topicNameLength + "s%10s%10s%40s%40s%30s%n",
                              partitionInfo.topic(),
                              partitionInfo.partition(),
                              partitionInfo.leader() == null ? -1 : partitionInfo.leader().id(),
                              replicas,
                              inSyncReplicas,
                              outOfSyncReplicas)
                      .getBytes(StandardCharsets.UTF_8));

**Comment by nareshv** [comment]
Code at https://github.com/linkedin/cruise-control/blob/4f83a21b5634b1037f26664516ca9cc4104e8827/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java#L923 has returned as one of the last params `broker.leaderReplicas().size()` whereas code at https://github.com/linkedin/cruise-control/blob/4f83a21b5634b1037f26664516ca9cc4104e8827/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/model/ClusterModel.java#L887 does not have this member in JSON
