### ISSUE TITLE
connection refused error

### ISSUE THREAD

**Issue by AmnonBZ** [linkedin/cruise-control#226]
Hi,
I started the cruise control server, it seems to be started, and still im getting "connection refused" when trying to reach the server

* firewalld and selinux both disabled
* ps aux output and the cruise-control-start script output attached below

thanks :)
![ps output](https://user-images.githubusercontent.com/22905418/39959705-3d41ab4a-561e-11e8-9a4c-ebbbe5f0166b.png)
![start output](https://user-images.githubusercontent.com/22905418/39959706-3d8e0daa-561e-11e8-971a-f671a35d1591.png)

**Comment by efeg** [comment]
Can you provide more information about your setup -- i.e. where is cruise control deployed and where are you trying to reach it from? Is `connection refused` received between you and cruise control or between kafka and cruise control?
Can you `telnet` between those machines?

**Comment by efeg** [comment]
Closing the issue as (1) the previous reply should facilitate in resolving the issue, and (2) I believe this is a network-level issue rather than CC-specific problem.
