### ISSUE TITLE
Using both `json=true` + `verbose=true` in GET to `/proposals` excludes movement summary in JSON output

### ISSUE THREAD

**Issue by ynasser** [linkedin/cruise-control#230]
Hi, I've noticed that when I make GET requests to the `/proposals` with both `json` and `verbose` enabled:

`curl --get  "http://localhost:9090/kafkacruisecontrol/proposals?json=true&verbose=true"`

... it doesn't include the summary of the proposed replica movements that is included in the output when I only include `verbose=true` in the url, e.g. the output that includes stuff like this:

`{some.topic-name, oldLeader: 2034, [2034, 2031, 2025] -> [2031, 2034, 2025]}`

Is this the intended behaviour?

Thank you.

**Comment by efeg** [comment]
Thanks for reporting this issue.
Ideally, there should be a standard response when `json=true` and `json=false` -- i.e. this is not intentional.

**Comment by nareshv** [comment]
verbose handler code isn't moved to JSON everywhere in the CC. It needs some work.
