### ISSUE TITLE
Kafka endpoint not functional for cruise.control.metrics.reporter.bootstrap.servers

### ISSUE THREAD

**Issue by fmunteanu** [linkedin/cruise-control#235]
I would like to understand how `cruise.control.metrics.reporter.bootstrap.servers` setting works. Using logic, if the variable is not defined, default `localhost` is used, providing the topic metadata of existing broker.

However, based on detailed tests, if I have 6 brokers, I need to define ALL brokers into setting, comma separated. Excluding only one broker from list, or using explicitly localhost, or using a Kafka endpoint will result on broker metrics not being sent.

We would like to use an endpoint, something like:
```
cruise.control.metrics.reporter.bootstrap.servers=kafka.domain.com:port
```
This will allow us to avoid `server.properties` edits and service restarts, when a broker goes down. I would like to know how you guys deal with this scenario, while maintaining 1500 brokers. There is no way you add 1500 domain names into `server.properties`. 😄 

Related to Kafka bootstraping, the client needs to find one broker and that broker will tell the client about all other brokers that exist and what partitions they host. The above tests proved CC does not work the same way and it needs to know all Kafka brokers, not just one? Also, does the client need to keep polling and see if the cluster has changed? At what frequency? The default process of fetching metadata once until it receives an error indicating that the metadata is out of date should work.

**Comment by fmunteanu** [comment]
@efeg @jmarkan for visibility.

**Comment by jmarkan** [comment]
@efeg we were able to fix this by setting ‘cruise.control.metrics.reporter.bootstrap.servers=0.0.0.0:<kafka port>‘ on every Kafka broker. 

Earlier we tried setting it as ‘localhost:<Kafka port>’ and the actual IP address of the broker as well, and in none of those scenarios, the broker was able to send it’s metrics to CC topic. Do you know if it is expected to have 0.0.0.0 be successful in sending the metrics and other 2 options don’t?

**Comment by efeg** [comment]
Sorry for the late response!
`cruise.control.metrics.reporter.bootstrap.servers` config corresponds to the `bootstrap.servers` config of the underlying metrics reporter producer. You definitely should not need to list all Kafka brokers here -- you may find the relevant documentation here: https://kafka.apache.org/documentation/#producerconfigs.

Regarding why `localhost` does not work, but `0.0.0.0` works for you seems to be a network configuration issue on your end (see [stackoverflow](https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost)).
