### ISSUE TITLE
Add a "Used by these organizations" section

### ISSUE THREAD

**Issue by ynasser** [linkedin/cruise-control#246]
Many open-source projects have a section on their overview page/Github README that lists some organizations/companies that are using the tool. This helps those evaluating the tool trust it more, and also gives the project more good publicity.

I work at a well-known payments company and we're in the process of adopting Cruise Control, and it would really help us feel more trusting in Cruise Control if there was such a section in your README.

Thanks for considering it!

**Comment by efeg** [comment]
Hi @ynasser,

Sure, I have been intending to compile an initial list.

Would you be interested in having your company name on our "used by these organizations" page? 
If so, please send me an email using my contact information on [my Github profile](https://github.com/efeg) or respond to this ticket.

@alexandrfox @jmarkan @jlisam @AmnonBZ @TheyDroppedMe @lawrencewu @lifehacking @brettrann @otisg @pdinavahi @jojohappy @edvorkin

**Comment by efeg** [comment]
Closing this ticket as many companies (i.e. from and out-of Silicon Valley) use Cruise Control in production, but are not eager to share this information publicly.
