### ISSUE TITLE
scope the session cookie to the request path (action)

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#250]
This allow multiple requests to be submitted by the browser and not lose track of the active sessions.

Currently CC automatically converts the request to async mode and then sends a cookie called JSESSIONID to track this async request. Meanwhile if the browser sends another request, the browser will overwrite the previously issued cookie (session-id) and is no way of retrieving this.

In order to standardize the understanding of sessions, we should set the cookie path for JSESSIONID cookie to be that of the request (`/kafkacruisecontrol/state`, `/kafkacruisecontorl/load`, etc) instead of `/`

Its also worth adding a new parameter called `session.cookie.prefix` that is helpful for users who implement reverseproxy of CC instances. This value will be by default set to `/kafkacruisecontrol`

**Comment by efeg** [comment]
Closing this issue as the [UUID-based task management](https://github.com/linkedin/cruise-control/wiki/REST-APIs#a-note-on-using-uuidcookies) and [CCUI](https://github.com/linkedin/cruise-control-ui/) has enabled users to track their active and completed requests.
