### ISSUE TITLE
`/load` endpoint returns two sets of columns of mostly duplicated data

### ISSUE THREAD

**Issue by ynasser** [linkedin/cruise-control#273]
See the attached screenshot. When submitting queries to the `/load` endpoint, but there is no noticeable difference between them other than that the lower one includes the `Broker` column.

This duplication goes away when you set the JSON param to true: `/load?json=true`.

![screen shot 2018-07-02 at 8 57 42 am](https://user-images.githubusercontent.com/4513790/42174355-e6000de6-7dd6-11e8-8ce1-6a10c10a065d.png)

**Comment by kidkun** [comment]
The first table is status per host and the second table is status per broker. In your case the there is only one Kafka broker on each host , so the metrics in two tables look the same. In case there are multiple Kafka brokers(broker process) on the same host(physical/virtual machine), the metrics per host will be sum of metrics of all these brokers.

in JSON response, there are 
{
"brokers":
"hosts":
}
which correspond to the above two tables.

**Comment by ynasser** [comment]
Thanks for that clarification @kidkun. Feel free to close this issue. I think adding a clarifying note about this output in [these docs](https://github.com/linkedin/cruise-control/wiki/REST-APIs#get-the-cluster-load) could be useful for other new users with this kind of setup.

**Comment by kidkun** [comment]
updated [REST API](https://github.com/linkedin/cruise-control/wiki/REST-APIs#get-the-cluster-load) wiki page to add this information. Thanks for reporting the issue.
