### ISSUE TITLE
having issue using confluent latest kafka image with cruise control

### ISSUE THREAD

**Issue by shlomihassan** [linkedin/cruise-control#276]
Hi 

i am trying to enable cruise control on confluent kafka images without success
I copied cruise-control-metrics-reporter-0.1.0.jar and configure the metric collector like the manuall said 
and from some reason its not creating the topic.
am i missing somthing?
copied the jar to here /usr/share/java/kafka/
and add this line in the server config
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

i also tried to create the topic manually 
i see only confluent reporter is writing to it topic

**Comment by efeg** [comment]
hi @shlomihassan did you follow the steps in [Quickstart](https://github.com/linkedin/cruise-control#quick-start)? Could you share the exceptions you see in the logs?

**Comment by efeg** [comment]
Closing the issue due to inactivity. Please feel free to reopen if the issue is not resolved.

**Comment by mfouze** [comment]
Hello, 
I'm facing the same problem. 
Is someone know how to fix  ?
