### ISSUE TITLE
Inconsistency in anomaly.detection.goals documentation 

### ISSUE THREAD

**Issue by chowell5** [linkedin/cruise-control#277]
Config file at config/cruisecontrol.properties says

```anomaly.detection.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal```

Wiki page at https://github.com/linkedin/cruise-control/wiki/Configurations says

```anomaly.detection.goals```

```com.linkedin.kafka.cruisecontrol.analyzer.RackAwareCapacityGoal, com.linkedin.kafka.cruisecontrol.analyzer.PotentialNwOutGoal, com.linkedin.kafka.cruisecontrol.analyzer.ResourceDistributionGoal, com.linkedin.kafka.cruisecontrol.analyzer.LeaderBytesInDistributionGoals, com.linkedin.kafka.cruisecontrol.analyzer.TopicReplicaDistributionGoal, com.linkedin.kafka.cruisecontrol.analyzer.ReplicaDistributionGoal```

Are they supposed to be `analyser.goals` or just `analyser`?

**Comment by kidkun** [comment]
It is `analyser.goals`. 
I updated the typo on [Configuration page](https://github.com/linkedin/cruise-control/wiki/Configurations)
Thanks for reporting this.
