### ISSUE TITLE
Enabled IS_ZK_SECURITY_ENABLED = true

### ISSUE THREAD

**Issue by saritago** [linkedin/cruise-control#292]
We have zookeeper security enabled on our kafka clusters are unable to connect to those clusters from cruisecontrol. We have a couple of clusters where zk security is not enabled and we are able to connect there without any issues. 
In Executor.java i could see that IS_ZK_SECURITY_ENABLED  is set to false. Will cruisecontrol be able to connect if i just change it to true? or Is there a configuration readily available right now that i can use to enable zk security?

**Comment by efeg** [comment]
That is a good question! The current version of the Cruise Control does not provide a config to enable ZK Security, and sets (hard coded) the `IS_ZK_SECURITY_ENABLED` to `false` everywhere -- e.g. in `Executor` and `BrokerFailureDetector`. I don't see any reason why it shouldn't work if we change it to true -- but it needs to be tested. We would be happy to review/merge the patch if you could create a PR with the relevant changes.

**Comment by saritago** [comment]
Sure, will test in your environment and get back with the results..

**Comment by saritago** [comment]
Figured out different way to access kafka nodes that have zk security enabled without making change to your code. Thank you. Am closing this issue.

**Comment by lepolac** [comment]
@saritago could you expand on how you achieved this ?

**Comment by saritago** [comment]
Sorry for delayed response. Will share the details shortly

**Comment by saritago** [comment]
Hi,
You have zk security setup in your kafka right ?
