### ISSUE TITLE
HTTP session based async cruise-control actions causes operational problems and lack of visibility on active async actions

### ISSUE THREAD

**Issue by abhishekmendhekar** [linkedin/cruise-control#293]
Cruise Control maintains active sessions for the async task that are running. Users can use the session to get the status of the action. The number of active sessions is also used to limit the number of parallel operations that can be executed on Cruise Control

This issue tracks the effort to come up with a solution to introduce a TaskManager concept in conjunction with existing SessionManager concept to help better use and operate Cruise Control.

**Comment by abhishekmendhekar** [comment]
PR #304

**Comment by abhishekmendhekar** [comment]
Pending: update Wiki on how to use user-task-id

**Comment by efeg** [comment]
Please see: https://github.com/linkedin/cruise-control/wiki/REST-APIs
