### ISSUE TITLE
MonitorState NULL?

### ISSUE THREAD

**Issue by yyb345** [linkedin/cruise-control#30]
**When I start cruise control, following log info appears constantly:**

[2017-09-13 16:43:54,618] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:44:24,618] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:44:54,619] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:45:24,619] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:45:54,620] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:46:24,620] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
[2017-09-13 16:46:54,621] INFO Skipping best proposal precomputing because load monitor does not have enough snapshots. (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)

**Here is my browser's result , url address is localhost:8094/kafkacruisecontrol/state** 
{MonitorState: {state: RUNNING(0.000% trained), NumValidWindows: (0/0) (NaN%), NumValidPartitions: 0/4129 (0.000%), flawedPartitions: 0}, ExecutorState: {state: NO_TASK_IN_PROGRESS}, AnalyzerState: {isProposalReady: false, ReadyGaols: []}}

**I can't get any useful information about my  kafka  state, what's wrong ?**

**Comment by becketqin** [comment]
@yyb345 Cruise Control needs to monitor the cluster for some time in order to understand the workload when it starts for the first time. In the quick start, the time is configured to 5 minutes for each snapshot interval. So you need to wait for at least 5 min to get the information.

**Comment by bandishankar** [comment]
I waited more than 5 minute , still got same logs .

**Comment by becketqin** [comment]
@bandishankar I replied to you in #29

**Comment by yyb345** [comment]
@becketqin  However, I waited more than 10 minutes, still got same logs

**Comment by yyb345** [comment]
@becketqin  I have modified kafka's configuration to metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter, It still doesn't work.

**Comment by yyb345** [comment]
Kafka broker's log is following
WARN  CruiseControlMetricsReporter  Failed to send cruise control metric [OPIC_METRIC,TOPIC_FETCH_REQUEST_RATE,time=1505360344722,brokerId=898,topic=xxx,value=7.999

**Comment by becketqin** [comment]
Have you enabled auto topic creation on the broker? Can you check if there is a __CruiseControlMetrics topic in the Kafka cluster?

**Comment by yyb345** [comment]
I hava created __CruiseControlMetrics topic in my kafka cluster.

**Comment by yyb345** [comment]
https://github.com/linkedin/cruise-control/issues/20 
It's similar to my problem, but where can I configure it "cruise.control.metrics.reporter.bootstrap.servers" ?
on kafka servers kafka.properties ?

**Comment by becketqin** [comment]
@yyb345 Yes, in the kafka server properties.

**Comment by yyb345** [comment]
@becketqin I still encountered this problem **com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter: Failed to send cruise control metric**

**Comment by bandishankar** [comment]
it's working for me now

**Comment by becketqin** [comment]
@yyb345 Are you still seeing the issue?

**Comment by yyb345** [comment]
@becketqin I have solved this problem, thanks !

**Comment by anjalirpawar** [comment]
@yyb345 @bandishankar @becketqin. I still encountered this problem  even after editing the  kafka server properties.

**Comment by yyb345** [comment]
@arp2728 I added following kafka server properties: metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
listener=PLAINTEXT://0.0.0.0:9092
cruise.control.metrics.reporter.bootstrap.servers=0.0.0.0:9092

**Comment by arp2728** [comment]
@yyb345 Thanks. It's working for me.

**Comment by amal786** [comment]
i am not sure how did it work for you as i have using apache kafka version 2.2.0 and i have done the same settings in server.properties but when i start my broker it does not come up.
so i had to # the entry metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

**Comment by amal786** [comment]
@arp2728 please help on this @yyb345 please check

**Comment by amal786** [comment]
@bandishankar @arp2728 @yyb345  : the error that i see when i set the reporter metric is below
[2021-07-01 21:35:46,364] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: "com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter" ClassNotFoundException exception occurred

**Comment by amal786** [comment]
@bandishankar @arp2728 @yyb345 [2021-07-01 21:33:12,936] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.UnsupportedClassVersionError: com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
