### ISSUE TITLE
possibility of having a cluster for cruisecontrol nodes

### ISSUE THREAD

**Issue by saritago** [linkedin/cruise-control#302]
I have a question in similar lines with linkedin/cruise-control#81. What if we really want to have a cluster of CC, how can they both communicate? Does client id(in cruisecontrol.properties file) serve the purpose for treating both the nodes as a part of cluster? When you say alerts are available is that externally configured or some inbuilt option is available for alerting?

**Comment by efeg** [comment]
Currently each CC instance is expected to be configured such that it manages an exclusive Kafka cluster -- i.e. one-to-one mapping of a CC instance and a Kafka cluster is expected. Hence; as of today, having a cluster of CC instances is not supported. `client.id` is used for setting the id of metadata client.
The alerts mentioned in the issue refers to external alerts for failures of CC instances -- no inbuilt option is available.
