### ISSUE TITLE
cruisecontrol.properties contains metric not documented in wiki

### ISSUE THREAD

**Issue by fvigotti** [linkedin/cruise-control#313]
I haven't checked all metrics but some are missing ..  I see that the property file is documented, so if this file is fine, I suggest to refer to implement all the documentation in that file (which is also versioned) and let the wiki reference that ,
having two sources of documentation which also doesn't match is a mistake.

- https://raw.githubusercontent.com/linkedin/cruise-control/master/config/cruisecontrol.properties
- https://github.com/linkedin/cruise-control/wiki/Configurations

example : 
```
# The number of partition metric windows to keep in memory
num.partition.metrics.windows=1
```

**Comment by kidkun** [comment]
@fvigotti  Thanks for reporting this. The config document is a little bit out of sync with latest config options. I have update that page.
