### ISSUE TITLE
Getting optimization proposal when a broker dies results in 'com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: Self healing failed to move the replica away from decommissioned brokers.'

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control#314]
I am running a 3 broker kafka cluster and CC. After some time, I kill one of the brokers and try to get optimization proposal with ReplicaDistributionGoal. However, I get an exception. 

 curl -X  GET "http://localhost:9090/kafkacruisecontrol/proposals?goals=ReplicaDistributionGoal&verbose=true&ignore_proposal_cache=true"
Error processing GET request '/proposals' due to 'com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: Self healing failed to move the replica away from decommissioned brokers.'

I even tried decommissioning the broker API but that results in the same exception.

**Comment by kidkun** [comment]
hey @awartika what is your topic's replication factor? If you topic has RF set to 3 and you kill a broker, CC cannot move the replica of the dead broker.

**Comment by awartika** [comment]
Yes the RF is set to 3. Why is it that it can't move the replica ?

**Comment by awartika** [comment]
Actually RF is 2.

**Comment by kidkun** [comment]
can you check `kafka_cluster_state` to see what is replica distribution before optimization?

**Comment by efeg** [comment]
In a cluster with `3` brokers, if a broker dies and `proposals` endpoint is called with `ReplicaDistributionGoal`, then Cruise Control attempts to move all replicas away from the dead broker, and also balance the replicas among the remaining `2` alive brokers. In this particular case, without seeing the actual partition distribution in the cluster (which can be gathered with `kafka_cluster_state?verbose=true`), it is hard to guess why the optimizer failed to find a feasible solution, and failed to move replicas away from the dead broker using this goal. That being said, I strongly suspect that there was a partition in the cluster, whose replication was `3` when this endpoint was called. Closing the issue as it cannot be investigated further without additional information.
