### ISSUE TITLE
Why is NumValidPartitions a small percentage (14%) ? Why are other partitions invalid ? 

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control#321]
Get State API shows only 14% partitions as valid even though CC is running for several days. 
Why are the other partitions considered invalid ? 

MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (0/1) (0.000%), NumValidPartitions: 70/480 (14.583%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: false, ReadyGoals: [ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, ReplicaCapacityGoal]}

**Comment by kidkun** [comment]
replicate of  issue [318](https://github.com/linkedin/cruise-control/issues/318)
