### ISSUE TITLE
kafka automate 

### ISSUE THREAD

**Issue by ThreeEarthGod** [linkedin/cruise-control#344]
Hi,Friend, I want to ask if Cruise Control can automate the expansion of kafka clusters, how to expand, and when to provide management interfaces.thanks.

**Comment by efeg** [comment]
Hi @ThreeEarthGod ,
Sure, Cruise Control (CC) can be used to automatically move load to the added brokers to balance the cluster load. 

**Prerequisite**: After you expand your Kafka cluster with new brokers, if you have a heterogeneous cluster, you should also update your `config/capacity.json` with the capacity of the new brokers and bounce your CC instance. If you have a homogeneous cluster (i.e. new brokers have the same capacity as the default broker capacity specified in `config/capacity.json`) you may skip this step.

You may achieve this either by
1. enabling `self-healing` (e.g. either `self.healing.enabled=true` to enable all anomaly detectors or `self.healing.goal.violation.enabled=true` to enable only the goal violation detector) to let Cruise Control detect the lack of load on new brokers and balance the load for you,
2. calling the `add_broker` endpoint with the broker ids of the new brokers, or 
3. calling the `rebalance` endpoint to balance the all cluster load.
