### ISSUE TITLE
Invitation to Cruise Control Talk at Streams Processing Meetup@LinkedIn (Oct 23)

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#346]
Cruise Control Community,

LinkedIn will host its quarterly Stream Processing Meetup@LinkedIn on _Oct 23_, and one of the talks will be about Cruise Control.

**How LinkedIn navigates Streams Infrastructure using Cruise Control**
_Speaker: Efe Gencer (@efeg), LinkedIn_
We’ll share our work and experiences towards alleviating the management overhead of large-scale Kafka clusters using Cruise Control at LinkedIn. The talk will consist of two parts: The first part will provide an overview of Cruise Control, including the operational challenges that it solves, its high-level architecture, and some evaluation results from real-world scenarios. The second part will go through a hands-on tutorial to demonstrate how we can manage a real Kafka cluster using Cruise Control.

I would like to invite you to attend this (free and open-to-all) meetup to learn more about Cruise Control and meet others from our open source community!
https://www.meetup.com/Stream-Processing-Meetup-LinkedIn/events/255016589/

**Comment by lindong28** [comment]
@efeg Since the issue is assigned, could you explain a bit what is the TODO for this issue? Thanks.

**Comment by efeg** [comment]
@lindong28 No action is needed! Just wanted to tag some key contributors, who will participate in this meetup :)
Due to the limit on the number of assignees, I just noticed that I was unable to tag many others, including @kidkun.

**Comment by jmarkan** [comment]
@efeg Thanks a lot for sharing this. I would like to attend remotely as I'm based in Montreal, Canada, so I assume more details of connecting to the live stream will be provided?

**Comment by efeg** [comment]
@jmarkan Yes, the details on how to connect to the live stream will be provided a couple of hours before the meetup on [the event page](https://www.meetup.com/Stream-Processing-Meetup-LinkedIn/events/255016589/). We will also share the video recordings after the meetup.

**Comment by ThreeEarthGod** [comment]
Hi, efeg:
I am in China, I want to see it too. so I need see the vedio. thanks

**Comment by jocelyndrean** [comment]
Can't wait to see the recording :)

**Comment by efeg** [comment]
Hi @jocelyndrean @ThreeEarthGod,

The [video recording of the talk](https://www.youtube.com/watch?v=jdo6F21gI8g) is available now!

**Comment by ThreeEarthGod** [comment]
Thanks a lot


原始邮件
发件人:Adem Efe Gencernotifications@github.com
收件人:linkedin/cruise-controlcruise-control@noreply.github.com
抄送:zhangsantuzhangyao@reyun.com; Mentionmention@noreply.github.com
发送时间:2018年11月6日(周二) 08:14
主题:Re: [linkedin/cruise-control] Invitation to Cruise Control Talk atStreams Processing Meetup@LinkedIn (Oct 23) (#346)


Hi @jocelyndrean @ThreeEarthGod,
The video recording of the talk is available now!
