### ISSUE TITLE
API: Add new end point to search for topics

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#361]
New end point to list available topics with KCC. Regex search would be helpful as well.

URL: `/kafkacruisecontrol/topics?expr=__*&async=false&sort=true&sortCol=topic&limit=100&offset=0`
Response: 
```
{
  "version": 1,
  "total": 3,
  "limit": 10,
  "offset": 0,
  "topics": [
   { "topic": "__CruiseControlMetrics", "partitions": 8 },
   { "topic": "__consumer_offsets", "partitions": 8 },
   { "topic": " __KafkaCruiseControlPartitionMetricSamples", "partitions": 32}
  ]
}
```

Parameters

* *expr*  (_String_): Regular Expression
* *async* ( _true/false_): If _true_ never spawn a async request for this
* *sort* (_true/false)_: If _true_ sort the results by default on *topic*
* *sortCol* (_String_): Column on which sorting to be performed
* *limit* (_Integer_): Return only these number of results
* *offset* (_Integer_): Send the results from this entry onwards

**Comment by efeg** [comment]
The super set of the requested information is already available in `kafka_cluster_state` endpoint with `verbose=true` (the result is always sorted by default). The issue https://github.com/linkedin/cruise-control/issues/697 will add support for filtering the response based on the given `topic` parameter that takes a regex. I feel that if further formatting is needed, we can add this to the `kafka_cluster_state` endpoint.
