### ISSUE TITLE
user_tasks api returns doubly encoded data

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#365]
`/user_tasks?json=true` returns a response with the following fields

```
{
"version": 1,
"Message": "Json encoded List of Tasks"
}
```

This requires double decoding of the data (one for the original response and another for the `Message`).

Please change it to send the list of tasks something like

```
{
"version": 1,
"tasks": [
  {
    "Status": "Completed",
    "ClientIdentity": "127.0.0.1",
    "RequestURL": "GET /kafkacruisecontrol/proposals?json=true",
    "UserTaskId": "1bbba31e-bc06-42cb-ad6f-115ccd4575a7",
    "StartMs": "1539229595109"
  },
  { ... }
]
}
```

**Comment by efeg** [comment]
This has been fixed and merged in https://github.com/linkedin/cruise-control/pull/358.
