### ISSUE TITLE
API: Add new end point to do per topic/partition movements

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#379]
Add a new end point using which we can do movement of topics in a selected fashion

Possible Parameters

- `Topic`: Regular Expresion
- `Partitions` : Range Expression
- `Destination Brokers`: List of Broker Ids
- `Goals`: List of Goals that should not be violated as part of this movement
- `Skip Hard Goals` : Skip hard goals as part of this movement
- `dryrun`: Boolean
- `Excluded Brokers` : Don't move these matched topics/partitions to these brokers

**Comment by efeg** [comment]
Cruise Control already supports 1) excluding or including topics using `excluded_topics` parameter of `rebalance` request, which takes a regex as input, 2) specifying destination brokers (i.e. naturally also the excluded brokers) using `destination_broker_ids` parameter, and 3) specifying goals and skipping hard goals are also possible using the `goals` and `skip_hard_goal_check`.
