### ISSUE TITLE
API: Return the CC version in response

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#381]
Return the version of the CC thats running either in the Header or as part of the Body.

If we are using HTTP Headers, we can follow this https://tools.ietf.org/html/rfc7231#section-7.4.2

**Comment by alexwang08** [comment]
Kafka has a way to determine version and commitId information which we can use in CC. In Kafka, gradle has a task to create file called "kafka-version.properties", which contains version (an property of Gradle object called Project) and commitId (can be determined from .git). This file is read by AppInfoParser.java in Kafka to load version and commitId properties.

**Comment by efeg** [comment]
Support was added in PR https://github.com/linkedin/cruise-control/pull/439.
