### ISSUE TITLE
Failed to start cruise control with parameter -daemon

### ISSUE THREAD

**Issue by sharepusher** [linkedin/cruise-control#40]
[cruise-control]$ ./kafka-cruise-control-start.sh 
USAGE: ./kafka-cruise-control-start.sh [-daemon] [-name servicename] [-loggc] [-jars jar_path] config_path [port]
[cruise-control]$ ./kafka-cruise-control-start.sh -daemon config/cruisecontrol.properties 
Enabling Java debug options: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
./kafka-cruise-control-start.sh: line 182: : No such file or directory
[cruise-control]$

**Comment by becketqin** [comment]
This should have been resolved by #43
