### ISSUE TITLE
Ensure that metric anomaly finder considers the relative traffic changes in the cluster

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#432]
If there is a sudden overall drop or increase in the traffic of a fraction of cluster (5% of the cluster) within a given period of time, this is a valid metric anomaly. However, if the whole cluster shows an increased or decreased traffic, then this may as well be due to some traffic shift away from or into the cluster, which is acceptable.

The default metric anomaly finder should handle this case.

**Comment by kidkun** [comment]
This is addressed in pr #985
