### ISSUE TITLE
Race condition in Kafka sample store topic configuration updating makes topic partition replication factor inconsistent

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#437]
For Cruise Control using KafkaSampleStore as metric sample storage, during the boot up process there is a sanity check of metric sample store topic's replication factor and partition count. If any violation found, KafkaSampleStore will try to update the `broker/topic` Znode to update the config. However, if both replication factor and partition count requirement are violated, there is a race condition to update these two configurations at the same time and may result in the the different partitions of sample store topic having different replication factor.

**Comment by efeg** [comment]
@kidkun I think we can close this after the cherry-pick to `migrate_to_kafka_2_0`.
