### ISSUE TITLE
Make the broker metric sample creation backwards compatible

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#440]
Currently if the Cruise Control metrics reporter is using an old serialization version, then the receiver will have the `WARN` messages such as `Skip generating broker metric sample for broker 123 because the following metrics are missing [BROKER_PRODUCE_TOTAL_TIME_MS_999TH, BROKER_PRODUCE_TOTAL_TIME_MS_50TH, BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_50TH, BROKER_FOLLOWER_FETCH_REQUEST_QUEUE_TIME_MS_999TH, BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_999TH, BROKER_PRODUCE_LOCAL_TIME_MS_50TH, BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_50TH, BROKER_LOG_FLUSH_TIME_MS_999TH, BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_50TH, BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_999TH, BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_999TH, BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_999TH, BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_999TH, BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_50TH, BROKER_FOLLOWER_FETCH_TOTAL_TIME_MS_50TH, BROKER_PRODUCE_LOCAL_TIME_MS_999TH, BROKER_LOG_FLUSH_TIME_MS_50TH, BROKER_CONSUMER_FETCH_TOTAL_TIME_MS_999TH, BROKER_CONSUMER_FETCH_REQUEST_QUEUE_TIME_MS_50TH, BROKER_PRODUCE_REQUEST_QUEUE_TIME_MS_50TH]`.

We can resolve this issue by making broker metric sample creation backwards compatible.

**Comment by craynic** [comment]
What does `old serialization version` mean? Now I have CC and metrics-reporter both in 0.1.21, but I still get this warning.

**Comment by efeg** [comment]
@craynic Would you double check that you followed all steps specified on the [Quick Start - Step-1](https://github.com/linkedin/cruise-control#quick-start) to create the new `cruise-control-metrics-reporter` jar, then copied it to the correct path?

**Comment by efeg** [comment]
@craynic Ah yes this is definitely a bug due to a known issue. Let me create a ticket for it.
