### ISSUE TITLE
Cruise control not generating metrics for clusters where "log.message.format.version" is set to 0.9.0.1

### ISSUE THREAD

**Issue by saritago** [linkedin/cruise-control#455]
Hi,

Observed that cc metrics is not getting generated  on the cluster where "log.message.format.version" is set to 0.9.0.1. There are other clusters where I get expected results which has this value set to 1.0-IV0. Does this make a difference?

Is there a mandate version for log.message.format.version for CC to work?
We are on kafka version 2.11-1.1.1

**Comment by efeg** [comment]
Hi @saritago 
Yes, Cruise Control requires `message.format.version` `0.10.0` or above -- please see the documented requirement here: https://github.com/linkedin/cruise-control#environment-requirements.

-- The issue should be resolved if you upgrade the `message.format.version`.

**Comment by saritago** [comment]
Thanks, I thought it was requirement for migrate_to_kafka_2_0 branch only.
