### ISSUE TITLE
Implement better errorhandling within CruiseControlMetricsReporter 

### ISSUE THREAD

**Issue by pdinavahi** [linkedin/cruise-control#46]
We are looking to use CruiseControl for our next cluster expansion. We actively started working on getting the CruiseControl setup in our development environment. 

1.) CruiseControl is expecting manual broker.id assignments and failing to startup when it is set to -1.

2.) We missed creating the __CruiseControlMetrics topic before starting the brokers with reporter enabled. Reviewing current CC issues helped as Issue #21 and debug logging made us realize what might be happening. Improved documentation probably will have helped us understand the Topic should be created prior to enabling the metrics reported on the broker. I have created the topic now, but, would also help if documentation can clarify what topic config such as retention period, number of partitions  should be used. 

3.) Better errorhandling would ensure missing topic , it may be better for the reporter to check that the topic exists and log an error. Currently it keeps logging excessively that topic is missing.

**Comment by becketqin** [comment]
@pdinavahi Thanks for the interest in Cruise Control and the suggestions. Pleas see the reply below:

1) I guess you meant the metrics reporter. You are right, we are reading the information from the configuration. It may be a little tricky to get the broker id after the broker has started. We absolutely should document this. We can add the sanity check in the cruise control metrics reporter and throw exception when broker id is negative.

2) We should probably just create the topic in the metrics reporter automatically. I'll submit a patch.

3) If we do 2) this would not be an issue.

**Comment by BDeus** [comment]
Did you submit a patch? the reporter still not create __CruiseControlMetrics topic.

**Comment by efeg** [comment]
The support for creating `__CruiseControlMetrics` has been added in https://github.com/linkedin/cruise-control/pull/510.
