### ISSUE TITLE
Wiki link on github page gone

### ISSUE THREAD

**Issue by Thoymas** [linkedin/cruise-control#463]
Hey.

The wiki link for this repo seems gone and clicking on links in the README that links to wiki pages one gets redirected back to the README.
Have you removed the wiki or am I doing something stupid?

Best Regards
Thomas

**Comment by efeg** [comment]
@Thoymas there seems to be a misconfiguration of CC Wiki privacy -- we are working on resolving the issue. thanks for reporting!

**Comment by efeg** [comment]
Wiki visibility issue has been fixed -- sorry for the unavailability.

**Comment by Thoymas** [comment]
@efeg Thanks for the quick fix.
