### ISSUE TITLE
Inconsistent disk utilization

### ISSUE THREAD

**Issue by craynic** [linkedin/cruise-control#466]
I'm getting error:

    ERROR Proposal precomputation encountered error (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
    java.lang.IllegalArgumentException: Inconsistent load distribution. Broker utilization for disk is different from the total replica utilization in the broker with id: 1. Sum of the replica utilization: 20869.701074123383, broker utilization: 12601.337890625
    at com.linkedin.kafka.cruisecontrol.model.ClusterModel.sanityCheck(ClusterModel.java:905)
    at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:453)
    at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:381)
    at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer$ProposalCandidateComputer.run(GoalOptimizer.java:689)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

actual disk usage (whole partition is for kafka):
/dev/vdb1      515930548 162880772 326818996  34% /data1

kafka 0.11 
cc 0.1.22

**Comment by craynic** [comment]
I guess there are problems in broker dist utilization, because it is changing largely.

**Comment by craynic** [comment]
Here are the logs: https://gist.github.com/craynic/413076880f3ce6bdfae50383f0b971f8
0.1.22 is the only version that has been deployed on this cluster. No config has been changed.

**Comment by efeg** [comment]
Here are some questions that might help us dig into issue: 
- What does the `load` endpoint return?
- Are there any other exceptions in the (1) Cruise Control log or (2) broker logs regarding metrics reporter?
- Did you try restarting the CC instance?

**Comment by craynic** [comment]
- Return for `/load` seems good. `MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 1421/1421 (100.000%), flawedPartitions: 0}`
- No other exception has been seen in cc logs.
- I've restarted once. Nothing changed.

**Comment by craynic** [comment]
I'm looking into the metrics collected by CC. I cannot find anything like BROKER_DISK_UTIL. How do the metrics for broker disk utilization get collected? Are they calculated by partition metrics?

**Comment by craynic** [comment]
I've got some partition size metrics that have negative values. Are they by design?

 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=user-center_portal_portal-user-center-2,value=-1214305203.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=primary-selection_worker_primary-selection-0,value=-1833463292.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=trade-server_portal_portal-trade-server-0,value=-232325565.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=attention-server_worker_attention-server-0,value=-593661951.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=regulation_worker_regulation-0,value=-1724006321.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=oppo_worker_inquiry-tailing-trigger-0,value=-1467365035.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=treasure-server_worker_treasure-server-0,value=-139013431.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)
 [PARTITION_METRIC,PARTITION_SIZE,time=1545895177513,brokerId=2,partition=discovery_worker_discovery-0,value=-1323299248.000] (com.linkedin.kafka.cruisecontrol.metricsreporter.metric.MetricSerde)

**Comment by craynic** [comment]
I collected all the partition sizes. All of them are in range (-2*31, 2*31). I doubt there is an overflow problem.

**Comment by kidkun** [comment]
The `PARTITION_SIZE` metric is from yammer metric `Size` and it is reported from leader replica about the disk usage of the partition, with that said it should not be negative. 

I agree that is looks like an overflow issue but I am not sure where the overflow happens. 
Inside Cruise Control, it is stored as s `PartitionMetric` and the value is stored as a `Double`.
inside Yammer, the gauge value is stored as a `Long`.
in the yammer metric to CC metric converting [code](https://github.com/linkedin/cruise-control/blob/322a323e24895e435fe7fc1b1f8eed807771a915/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/YammerMetricProcessor.java#L148), we cast to `Number` to `Double`.

I actually write a simple test to test the serdes functionality with value larger than 2^31 and do not spot any issue.

Can you open Jconsole and check what is the original value reported by yammer metrics for above erroneous CC metric?

**Comment by craynic** [comment]
@kidkun 
I've seen some topic metrics in domain `kafka.server`, but I cannot find any partition metric. Where are they?

**Comment by kidkun** [comment]
it should be under `Domain: kafka.log` and looks like 

`kafka.cluster:type=Partition,name=InSyncReplicasCount,topic=__consumer_offsets,partition=11 | com.yammer.metrics.reporting.JmxReporter$Gauge | Information on the management interface of the MBean`
-- | -- | --

kafka.log:type=Log,name=LogEndOffset,topic=__consumer_offsets,partition=11 | com.yammer.metrics.reporting.JmxReporter$Gauge | Information on the management interface of the MBean
-- | -- | --

**Comment by craynic** [comment]
I've got some `Size`s from jmx and they are negative, though they do not completely match the numbers in CC.
But the offsets seem right.
Sample:

> $>bean kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = -1768686377;
> 
> $>bean kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = 64313075;
> 
> $>bean kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = 65777822;

Now it seems not a problem with CC.

**Comment by craynic** [comment]
I've got some `Size`s from jmx and they are negative, though they do not completely match the numbers in CC.
But the offsets seem right.
Sample:

> $>bean kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=Size,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = -1768686377;
> 
> $>bean kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=LogStartOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = 64313075;
> 
> $>bean kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> #bean is set to kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log
> $>get Value
> #mbean = kafka.log:name=LogEndOffset,partition=0,topic=oppo.worker.marketing-inquiry-retrieve-action,type=Log:
> Value = 65777822;

Now it seems not a problem with CC. Thank you for your help.

**Comment by efeg** [comment]
Closing the issue as it seems to be a Kafka issue.
