### ISSUE TITLE
My ExecutorState always in {state: NO_TASK_IN_PROGRESS} even after the goal violation

### ISSUE THREAD

**Issue by shanrd7** [linkedin/cruise-control#469]
MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (1/1) (100.000%), NumValidPartitions: 275/275 (100.000%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: false, readyGoals: [NetworkInboundUsageDistributionGoal, CpuUsageDistributionGoal, PotentialNwOutGoal, NetworkInboundCapacityGoal, LeaderBytesInDistributionGoal, DiskCapacityGoal, ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, NetworkOutboundCapacityGoal, CpuCapacityGoal, DiskUsageDistributionGoal, NetworkOutboundUsageDistributionGoal, ReplicaCapacityGoal]}
AnomalyDetectorState: {selfHealingEnabled:[GOAL_VIOLATION, METRIC_ANOMALY, BROKER_FAILURE], selfHealingDisabled:[], recentGoalViolations:[{violatedGoals=[NetworkInboundCapacityGoal, DiskCapacityGoal, RackAwareGoal, NetworkOutboundCapacityGoal, CpuCapacityGoal, ReplicaCapacityGoal], detectionDate=2019-01-02_18:12:14 UTC}], recentBrokerFailures:[{detectionDate=2019-01-02_18:11:54 UTC, failedBrokersByTimeMs={1=1546452714604}}], recentMetricAnomalies:[]}

Monitored Windows [Window End_Time=Data_Completeness]:
{1546455600000=100.000%}

Goal Readiness:
                                     RackAwareGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                                PotentialNwOutGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), Ready
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                          CpuUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), Ready
                     LeaderBytesInDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), Ready

**Comment by shanrd7** [comment]
Seeing below error on Kafka CC logs

[2019-01-02 19:57:01,694] ERROR Proposal precomputation encountered error (com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer)
com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: Insufficient number of racks to distribute each replica

**Comment by kidkun** [comment]
the exception means you do not have enough rack to distribute replicas. 
`RackAwareGoal` is trying to place replicas of a partition to brokers on different racks and it is a hard goal. if this goal cannot be satisfied, the proposal will be failed to generate. 

if you want to not use this goal, you can update the config `default.goals` and remove `com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal` from there.

**Comment by shanrd7** [comment]
Have broker racks has below 
broker.rack=1
broker.rack=2
broker.rack=3
I still see the error.

Removed com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal from default.goal
I see partition movement
INFO 92/92 (100.00%) partition movements completed. 165/165 (100.00%) MB have been moved. (com.linkedin.kafka.cruisecontrol.executor.Executor)
INFO Partition movements finished. (com.linkedin.kafka.cruisecontrol.executor.Executor)

Still see under replicated partitions on my 3 broker 2 replicated topics after one broker goes down

**Comment by shanrd7** [comment]
With Rackawareness no partition movement also see topics.excluded.from.partition.movement as null value
	num.concurrent.leader.movements = 1000
	num.concurrent.partition.movements.per.broker = 10
	topics.excluded.from.partition.movement =
[2019-01-04 12:21:21,238] WARN The configuration 'num.concurrent.partition.movements.per.broker' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)

Without Rackawareness there is partition movement
num.concurrent.leader.movements = 1000
	num.concurrent.partition.movements.per.broker = 10
[2019-01-03 12:00:45,185] WARN The configuration 'num.concurrent.partition.movements.per.broker' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig)
Starting 110 partition movements.
INFO 110/110 (100.00%) partition movements completed. 7/7 (100.00%) MB

**Comment by kidkun** [comment]
`num.concurrent.partition.movements.per.broker` is a servlet config so the warning make sense. 
From the log looks like after removing `RackawarenessGoal` CC is able to make progress.
