### ISSUE TITLE
Cruise Control doesnt self heal when the goals are violated

### ISSUE THREAD

**Issue by srinivas-d-12** [linkedin/cruise-control#49]
I have a 3 broker cluster and I see the goals are violated. Broker1 has 116 partitions, Broker2 has 116 partitions and Broker 3 has 0 partitions but Kafka Cruise Controller doesnt redistribute the load. 
I have set self.heal.enabled =true.

**Comment by becketqin** [comment]
Can you check the `anomaly.notifier.class` config? By default it is `NoopNotifier`. You can set it to `com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier`.

**Comment by srinivas-d-12** [comment]
hey thanks a ton .. but this is what I have. Have the configuration parameter names changed. i.e from anomoly.notifier to goal.violation. Also  anomoly detection goals has only Rackaware ? should this be all the 6 goals ? 
<img width="949" alt="screen shot 2017-10-10 at 7 46 53 pm" src="https://user-images.githubusercontent.com/5590124/31420005-d1077d6a-adf3-11e7-8740-e674e904b810.png">

**Comment by becketqin** [comment]
@srinivas-d-12 The configuration name should actually be `anomaly.notifier.class`. The property file needs to be fixed. You can add more goals if you want to.

**Comment by srinivas-d-12** [comment]
@becketqin thanks a ton. I was able to add goals and the self healing started working but still I see the partitions skewed and most of the goals are still under violation.
<img width="1651" alt="screen shot 2017-10-11 at 10 35 03 am" src="https://user-images.githubusercontent.com/5590124/31457113-a4e1f6f2-ae70-11e7-859b-9ad68a113f63.png">
As u can see at the bottom Broker3 doesnt have any partitions. Do you know why the load is not getting distributed ?

**Comment by becketqin** [comment]
There is a bug in the expected utilization. #50 is supposed to fix that. Broker 3 has NaN so all the goals will skip that broker.

**Comment by srinivas-d-12** [comment]
gotcha thanks

**Comment by becketqin** [comment]
@srinivas-d-12 The issue should have been solved. Can you check?

**Comment by srinivas-d-12** [comment]
cool will verify. Thanks

**Comment by becketqin** [comment]
@srinivas-d-12 Have you verified? Can we close the issue?

**Comment by srinivas-d-12** [comment]
Hey sorry was on vacation for the last week .Will verify by today. Sorry for the inconvenience
