### ISSUE TITLE
Programmatically tell whether cruise-control has returned a async request

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#493]
-- thanks @mgrubent for the feature request.

Currently, human operators ask cruise-control for information about Kafka clusters (usually via `curl`), then view the response to see if cruise-control has returned a valid response.

Humans know that a response like the following means that cruise-control is still computing its response.

```
Get broker stats:
(     2 ms) - (100.0%) PENDING: Operation enqueued, waiting to be executed.
(     0 ms) - (100.0%) WAITING_FOR_CLUSTER_MODEL: The job requires a cluster model and it is waiting to get the cluster model lock.
[...]
```

And humans know that a response like the following means that cruise-control has returned its final response

```
                           HOST            DISK(MB)/_(%)_         CPU(%)       LEADER_NW_IN(KB/s)     FOLLOWER_NW_IN(KB/s)        NW_OUT(KB/s)       PNW_OUT(KB/s)    LEADERS/REPLICAS
[...]
```

However, unless users use the `json=true` in their request and check for the expected field in the response, it is non-trivial to say that the response is `final`. Headers do not currently provide this information -- but it might be useful to have a flag to indicate this "finality".

**Comment by nareshv** [comment]
HTTP-202 header can be used for such responses. In [UI](https://github.com/linkedin/cruise-control-ui) we have written code to parse the responses (text/plain, json) and arrive at the right response type. But, having this feature helps the communication between clients & cc.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by emilyki** [comment]
# Async Response Design Doc

## Abstract

Design doc that presents a feature to indicate asynchronous response from Cruise Control.

## Motivation

Currently, it is impossible to tell programmatically whether cruise-control is computing the response or not. Example response of such a state can only be recognized, as it looks like the following:

    Get broker stats:
    (     2 ms) - (100.0%) PENDING: Operation enqueued, waiting to be executed.
    (     0 ms) - (100.0%) WAITING_FOR_CLUSTER_MODEL: The job requires a cluster model and it is waiting to get the cluster model lock.

This leads to difficulty in automating clients that require listening and reacting to the cruise-control's response. Moreover, there has been an increase in demand for this feature recently - [cruise-control/pull/783#discussion_r295982202](https://github.com/linkedin/cruise-control/pull/783#discussion_r295982202).

## Goals

- Cruise-control should support a way to indicate that a response is asynchronous. In other words, there needs to be a way to declare an intermediate state while it is computing a final response with the cluster model.
    - It must be noted that the intermediary response is written only if the future has not been canceled (and doesn't care if the response is already cached or not).

## Design

Currently, async calls in cruise-control are designed like the following:

Return Code | Description
--- | ---
200 (ok) | indicates that the request has returned successfully
error codes like 4xx, 5xx | indicates failure while processing the request

As per the suggestion of contributor @nareshv, the design of this feature will utilize HTTP response code 202 as an indicator of an intermediary/async response.

OperationRunnable is a class that abstracts the generation of all async responses in cruise-control. We will modify this class to respond to the client with an intermediary response before waiting for the future to be completed. The runnable writes a JSON response in the method run(), once the program verifies that the future has not been canceled.

Link to the method run in OperationRunnable that handles general async calls: [kafka/cruisecontrol/async/OperationRunnable.java#L37](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/async/OperationRunnable.java#L37)

1. Create a private helper method writeIntermediateResponse() in OperationRunnable
2. Import ResponseUtils and implement the helper method to send a HTTP-202 response

With the modifications above, the async calls in cruise-control will include the intermediary response like the following:

Return Code | Description
--- | ---
200 (ok) | indicates that the request has returned successfully
202 (accepted) | indicates that the request has been received successfully, and cruise-control is processing the request"
error codes like 4xx, 5xx | indicates failure while processing the request

Here are some example use case diagrams with the implementation of the feature:
1. When a client makes a request to Cruise Control:
![](https://lh3.googleusercontent.com/XY3vHjIx9QNy5izhnNRbgaWe57eiwOn8Hlqa1wVKh3QFpy_Ye7drxEqISmA1waCUB2a4BEdK9HVpjwKuyatV237BU0Yw5fHReyc0XZWzsFB8paameGUfe5RTeQ8N_4krpm5BO_m-WEL39CJLGsOytanv1WedX_rmlFy6UiL4lq4fvDn2YHc3HkZeNth2v4CyAScJ2LNYecvRHrMQlxJNtOIl0wfaU8k1LXyJqCNy6D4uI8KfY6B3q8doLFl2Ww2bZPQRcoUWrvUXXLKrYcHRoWsG05nJ-iB74zCdHUtIPOr5QkdmbM0RV5QRrG22_0mTTKn7mEO8K_7JJ-ON1Z1AKHUe3WBI3wDGad0XQNpIjjrWPpm97iIzmKBMKvRBK8utdx1x5kltuIVOFI03DAd3SZop0dKVNAQrgVQWNN9AZjSn0vbEUUsyW6RbxVUpX5JZzVWZhZp4jXt4Z1YVPTT9xFcAXp2ekUifzm_wRFULFjmcbNcZXnG7xfjAtHYgupudc7Bo-TINiE05N7hSHNDvqvDQgs3Fzzix2zBBUL_N_cwC6tMypECvZ_eVtguIJLCt_LE7gKVJwYlyOLJA6d3dc1T2iLeCPycW1b9OjdM=w2810-h1314)
2. When a client makes a request to Cruise Control, then ask for status of the request
![](https://lh6.googleusercontent.com/Chg4me7C9DjrX-i7kYUtOb0ZEzYcTocFn8OVSCzFXlcSvUkkxvbitbw38ioHCIB8lBCRA3L9PWtdQKA5BGy9=w2810-h1314)

cc @efeg @kidkun

**Comment by emilyki** [comment]
Update on the design doc:
The original design doc suggests that changes should be made to the `OperationRunnable#run()`. However, after a more careful inspection of code, I'd like to propose a change to the `CruiseControlResponse`, `AbstractCruiseControlResponse` and `AbstractAsyncRequest` to implement `writeInProgressResponse` method instead. Thanks!

cc @efeg @kidkun
