### ISSUE TITLE
CC status shows Loading with numValidPartitions and numValidWindows 0.

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control#497]
curl -X GET "http://localhost:9090/kafkacruisecontrol/state?verbose=true"
MonitorState: {state: LOADING(0.000% trained), LoadingProgress: NaN%, NumValidWindows: (0/0): (NaN%), NumValidPartitions: 0/510 (0.000%), FlawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: false, readyGoals: []}
AnomalyDetectorState: {selfHealingEnabled:[], selfHealingDisabled:[GOAL_VIOLATION, METRIC_ANOMALY, BROKER_FAILURE], recentGoalViolations:[], recentBrokerFailures:[], recentMetricAnomalies:[]}

Monitored Windows [Window End_Time=Data_Completeness]:
{}

Goal Readiness:
                                     RackAwareGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                               ReplicaCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                                  DiskCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), NotReady
                        NetworkInboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), NotReady
                       NetworkOutboundCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), NotReady
                                   CpuCapacityGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), NotReady
                           ReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                                PotentialNwOutGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), NotReady
                         DiskUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=true), NotReady
               NetworkInboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), NotReady
              NetworkOutboundUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), NotReady
                          CpuUsageDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), NotReady
                      TopicReplicaDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.000, includedAllTopics=true), NotReady
                     LeaderBytesInDistributionGoal, (requiredNumWindows=1, minMonitoredPartitionPercentage=0.995, includedAllTopics=false), NotReady

I am also seeing following errors in the log:

kafkacruisecontrol.log.2019-01-22-10:[2019-01-22 10:47:02,664] ERROR Skip updating topic __KafkaCruiseControlPartitionMetricSamples configuration due to failure:Unable to increase topic __KafkaCruiseControlPartitionMetricSamples replica factor to 2 since there are only 1 racks in the cluster.. (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)
kafkacruisecontrol.log.2019-01-22-10:[2019-01-22 10:47:02,818] ERROR Skip updating topic __KafkaCruiseControlModelTrainingSamples configuration due to failure:Unable to increase topic __KafkaCruiseControlModelTrainingSamples replica factor to 2 since there are only 1 racks in the cluster.. (com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore)

Both the topics have replication factor of 2.

**Comment by awartika** [comment]
I removed RackAwareGoal from the goals and I still get the same error.

Here are the goals in the config:

default.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal

goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerEvenRackAwareGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PreferredLeaderElectionGoal

anomaly.detection.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal

**Comment by alexwang08** [comment]
The problem is replication factor (set by sample.store.topic.replication.factor in config/cruisecontrol.properties) is set to 2 by default. Since you only have 1 rack, CC will [throw exception](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java#L263) during bootstrap when it sees rack number is not satisfied. You should change the replication factor config to 1 in your config.

**Comment by awartika** [comment]
If I turn off RackAwareGoals I shouldn't see this right ?

**Comment by efeg** [comment]
This [patch](https://github.com/linkedin/cruise-control/pull/508) added support to skip sample store topic Rack Awareness check -- using the config `skip.sample.store.topic.rack.awareness.check=true`.
