### ISSUE TITLE
Add the max allowed imputations.

### ISSUE THREAD

**Issue by becketqin** [linkedin/cruise-control#5]

**Comment by efeg** [comment]
`MAX_ALLOWED_EXTRAPOLATIONS_PER_BROKER_CONFIG`, `MAX_ALLOWED_EXTRAPOLATIONS_PER_PARTITION_CONFIG`, and `MAX_ALLOWED_EXTRAPOLATIONS_PER_ENTITY_CONFIG` have been added to the codebase a while ago -- closing the ticket.
