### ISSUE TITLE
java.lang.NullPointerException flooded in Cruise Control log during transient connection loss to Kafka cluster.

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#511]
If there is transient connection loss between Cruise Control and Kafka cluster(due to network hiccup, Kafka cluster restarting etc.), CC metric fetching task may happens to run and will keep retrying, result in a flood of Exception log.

> 2019/01/28 23:43:29.502 WARN [NetworkClient] [MetricFetcher-0] [kafka-cruise-control] []  Broker may not be available.
2019/01/28 23:43:29.684 ERROR [MetricFetcher] [MetricFetcher-0] [kafka-cruise-control] [] Received exception.
java.lang.NullPointerException: null
2019/01/28 23:43:29.684 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Finished sampling in 184 ms.
2019/01/28 23:43:29.684 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Kicking off partition metric sampling for time range [1548718709558, 1548719009684], duration 300126 ms using 1 fetchers with timeout 299727 ms.
2019/01/28 23:43:29.694 ERROR [MetricFetcher] [MetricFetcher-0] [kafka-cruise-control] [] Received exception.
java.lang.NullPointerException: null
2019/01/28 23:43:29.694 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Finished sampling in 4 ms.
2019/01/28 23:43:29.694 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Kicking off partition metric sampling for time range [1548718709558, 1548719009694], duration 300136 ms using 1 fetchers with timeout 299717 ms.
2019/01/28 23:43:29.706 ERROR [MetricFetcher] [MetricFetcher-0] [kafka-cruise-control] [] Received exception.
java.lang.NullPointerException: null
2019/01/28 23:43:29.707 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Finished sampling in 6 ms.
2019/01/28 23:43:29.707 INFO [MetricFetcherManager] [SamplingScheduler-0] [kafka-cruise-control] [] Kicking off partition metric sampling for time range [1548718709558, 1548719009707], duration 300149 ms using 1 fetchers with timeout 299704 ms.
2019/01/28 23:43:29.716 ERROR [MetricFetcher] [MetricFetcher-0] [kafka-cruise-control] [] Received exception.

**Comment by efeg** [comment]
The issue has been fixed https://github.com/linkedin/cruise-control/pull/709.
