### ISSUE TITLE
Feature Request: schematize JSON responses

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#517]
### Issue
When asking `cruise-control` for a JSON response, it is not clear what structure that response will have, except by examining the classes in `cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response`.

This makes it difficult to programmatically know how to parse the received response, requiring a human to follow the `response` class code paths and their conditional parameter branches, to recreate a structure whose permutations the `cruise-control` servlet arguably already knows about.

Further, as `cruise-control` continues to mature and add features, the shape of the JSON response will grow, and a statically-defined response parser will miss the new fields.
### Proposal
`cruise-control` should define JSON schemas for the responses it can return from the different (endpoint, parameter) combinations.

`cruise-control` could then optionally pass the schema's identifier in the header of its response, as a low-overhead way of signaling the shape of the response.  
Returning a schema in this way could be opt-in, by including a parameter such as `json_schema_in_header=true` along with the `json=true` parameter.

Additionally, clients could use this proposed mapping of (endpoint, parameter) -> schema to know the expected schema ahead of time.
If `cruise-control` included the schema identifier in its header to the client, then the clients would affirmatively know whether `cruise-control` has updated its response schema for that (endpoint, parameter) tuple.  
Even if the schema identifier were not included, a client would be able to validate the received response against the expected schema and arrive at the same conclusion.

**Comment by ian952** [comment]
I will be working on this issue!

**Comment by efeg** [comment]
Closing this issue as it has been addressed in https://github.com/linkedin/cruise-control/pull/960.
