### ISSUE TITLE
Configuration cluster.configs.file must be provided

### ISSUE THREAD

**Issue by panda87** [linkedin/cruise-control#542]
Hi

Im using version 2.0.31 and gets this err when starting the service.
I can see in the logs that all my cruisecontrol.properties settings were applied, what missed?

Thanks

```
[           main] INFO  uisecontrol.KafkaCruiseControl  - COMMIT INFO: 2.0.31---f4f07cb7abebe37f42b92239d427bb70010c790d
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Configuration cluster.configs.file must be provided
```

**Comment by efeg** [comment]
Hi @panda87 this file contains the cluster-level configurations (i.e. the default configs that apply to all topics unless a topic-level config was defined) that `KafkaTopicConfigProvider` uses. It is configured using:
```
cluster.configs.file=config/clusterConfigs.json
```
The only use for it today is for the `min.insync.replicas` config, which is used in the response of the `kafka_cluster_state` endpoint to identify URPs that are also under minISR -- i.e. partitions that consumers can get data, but producers cannot produce to.
Please see [config/clusterConfigs.json](https://github.com/linkedin/cruise-control/blob/migrate_to_kafka_2_0/config/clusterConfigs.json) for example configs that you can use.
