### ISSUE TITLE
Add 2-step verification for POST requests

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#567]
`POST` requests enable users to perform various admin operations in a Kafka cluster. However, if a user mistypes a command, it is possible to start an unintended execution (e.g. remove `broker-X` rather than `broker-Y`).

2-step verification aims to help users double check the command they (or others) intend to run by letting them confirm the request explicitly or cancel it.

**Comment by alexwang08** [comment]
Would enforcing dryrun help in this case?

**Comment by efeg** [comment]
The key idea here is to add requests to a shared purgatory before the processing, and start actual processing after an explicit confirmation -- e.g. upon another user approves the request. Enforcing the dry run would always process requests. They are both good for preventing unintentional executions, but not interchangeable.

**Comment by nareshv** [comment]
I think this can be better handled via the interface (CCFE or CLI) thats interacting with CC.

- CCFE, can prompt the user "are you sure you want to do ..." via a confirmation dialog, etc
- CLI, can show the summary of "i am going to remove broker Z .. are you sure ?.. type "YES I AM SURE" .. " etc

But, it can be annoying sometimes. So, its worth keeping the user experience also in mind and can design this flag on the actual interface rather than on the CC itself.

If we really want to implement this in CC, then another safe mode like ('no-op' request like 'dry-run') can be built within CC?

**Comment by efeg** [comment]
I believe `CCFE` and `CLI` are good for self-confirmation purposes, but for peer-confirmation -- e.g. ask another operator to approve/execute your request -- it'd be better to have this functionality at CC itself.

-- Regardless, 2-step verification should be configurable (`two.step.verification=[true/false]`) -- and probably be disabled by default, so the interested users can enable it explicitly to have this functionality.

**Comment by alexwang08** [comment]
To have peer confirmation process, will CC need a way to differentiate 2 agents (e.g. requester and approver), by way of user id or IP address?

**Comment by efeg** [comment]
@alexwang08 not initially -- user-ids and IP addresses can easily be changed to act like a different agent. Proper agent differentiation requires authorization and authentication.

**Comment by nareshv** [comment]
Since we are going towards user identification, can we add support for Authentication/Authorization as well ? https://github.com/linkedin/cruise-control/issues/116

This requires some more discussion as CCFE should be able to SSO and get things done according to the policies set on CC.

**Comment by efeg** [comment]
This patch is independent from authorization/authentication; hence, sso discussion is not relevant here.

We can discuss sso at its corresponding issue.

**Comment by nareshv** [comment]
Can a link to docs be added here which mentions how the behavior of the HTTP requests changes with/without this feature ?

**Comment by efeg** [comment]
@nareshv Will definitely need to do that. Created an issue to track it: https://github.com/linkedin/cruise-control/issues/602
