### ISSUE TITLE
unable to start kafka-cruise-control-start

### ISSUE THREAD

**Issue by elhalouiMed** [linkedin/cruise-control#57]
hello
when i try to run the following command
./kafka-cruise-control-start.sh [-jars PATH_TO_YOUR_JAR_1,PATH_TO_YOUR_JAR_2] config/cruisecontrol.properties [port]

I dont know wich Jars files i need to put in the command line !
PATH_TO_YOUR_JAR_1,PATH_TO_YOUR_JAR_2 : what represent this jars ? and where i can find them ?

**Comment by becketqin** [comment]
The jars are optional (they are in the brackets, so is port) and only needed if you have your own implementation of some pluggables.
