### ISSUE TITLE
kafka cluster state api: ERROR Failed to populate broker logDir state

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#597]
@ananthdurai has reported this in CCFE, after investigation found that this needs some investigation on CC side.

More details are in : https://github.com/linkedin/cruise-control-ui/issues/14

**Comment by ananthdurai** [comment]
Follow up; I'm able to replicate the issue when we terminate a broker. So the exception is thrown when we lost a broker and the UI not handling the failure as well.
