### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by wenwen1708** [linkedin/cruise-control#6]
15:06:33.980 [ERROR] [system.err] /home/winson/cruise-control/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/CruiseControlMetricsReporter.java:182: error: local variable ccm is accessed from within inner class; needs to be declared final
15:06:33.981 [ERROR] [system.err]           LOG.debug("Failed to send cruise control metric {}", ccm);
15:06:33.981 [ERROR] [system.err]                                                                ^
15:06:33.989 [ERROR] [system.err] /home/winson/cruise-control/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/BrokerMetric.java:56: error: cannot find symbol
15:06:33.989 [ERROR] [system.err]                                                 Long.BYTES /* time */ + Integer.BYTES /* broker id */ +
15:06:33.989 [ERROR] [system.err]                                                     ^
15:06:33.990 [ERROR] [system.err]   symbol:   variable BYTES
15:06:33.990 [ERROR] [system.err]   location: class Long
15:06:33.990 [ERROR] [system.err] /home/winson/cruise-control/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/BrokerMetric.java:56: error: cannot find symbol
15:06:33.990 [ERROR] [system.err]                                                 Long.BYTES /* time */ + Integer.BYTES /* broker id */ +
15:06:33.990 [ERROR] [system.err]                                                                                ^
15:06:33.991 [ERROR] [system.err]   symbol:   variable BYTES
15:06:33.991 [ERROR] [system.err]   location: class Integer
15:06:33.994 [ERROR] [system.err] /home/winson/cruise-control/cruise-control-metrics-reporter/src/main/java/com/linkedin/kafka/cruisecontrol/metricsreporter/metric/BrokerMetric.java:57: error: cannot find symbol
15:06:33.994 [ERROR] [system.err]       

___________________________________________________________________________________________________________

please help me ！

**Comment by wenwen1708** [comment]
fucking dog !  used java 1.8 OK !

**Comment by becketqin** [comment]
Yeah... Java 1.8is required.
