### ISSUE TITLE
"migrate_to_kafka_2_0" branch: Problem running in webserver

### ISSUE THREAD

**Issue by zandegran** [linkedin/cruise-control#601]
We are running cruise control inside a webserver and doing this
`String[] uriTokens = request.getRequestURI().toUpperCase().split("/");
String path = uriTokens[uriTokens.length-1];`
 instead of this 
`String path = request.getRequestURI().toUpperCase().replace(REQUEST_URI, "");`
in 
`com.linkedin.kafka.cruisecontrol.servlet.parameters.ParameterUtils.endPoint`
would enable us to run multiple cruisecontrol servers in different paths.
We had to make that change ourselves and running for now.
This is in "migrate_to_kafka_2_0" branch.

Could you please change it?

**Comment by BrianGallew** [comment]
You shouldn't need a code change to do this.  I'm currently running 5 servers, with 4-20 cruisecontrol instances on it, with nginx serving them up.  I have Chef iterating through all the available Kafka clusters for each server, and creating a config.csv that covers them all, as well as systemd unit files (well, cruisecontrol@.service and crusiecontrol.target) and an app.conf for nginx.  Works a treat.  I just use different prefix paths in nginx and config.csv and it's all happy for viewing through cruise-control-ui.  The config.csv ends up looking something like:
region,kafka-1,/cc/kafka-1/
region,kafka-2,/cc/kafka-2/
...

**Comment by zandegran** [comment]
@BrianGallew Thanks for the infor. Sorry, this is in the "Migrate to 2.0.0" branch (now added to the question), where com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServletUtils.REQUEST_URI is hardcoded. So it's not use like /cc/kafka-1/, /cc/kafka-2/

**Comment by efeg** [comment]
Closing the old issue. Feel free to reopen if you have further questions.
