### ISSUE TITLE
Kafka 2.0+ compatibility

### ISSUE THREAD

**Issue by simPod** [linkedin/cruise-control#607]
![image](https://user-images.githubusercontent.com/327717/54878308-20102500-4e2b-11e9-8f0c-4209e68587e6.png)

Hi, from readme I'm not really sure whether to use master or migrate_to_kafka_2 branch. Can you clarify pls? Thanks!

**Comment by efeg** [comment]
Hi @simPod

Just updated the [documentation](https://github.com/linkedin/cruise-control#environment-requirements) -- thanks for reporting the issue and please let us know if there are any other concerns that we can help with!
