### ISSUE TITLE
Need to clarify where to run Cruise Control server

### ISSUE THREAD

**Issue by functicons** [linkedin/cruise-control#621]
It is unclear in the "Quick Start" section of the README that, whether I need to run Cruise Control server on every Kafka node or not. My guess is that, step 1 and 2 (copying jar and update Kafka config) are required for every Kafka node; but step 3 and 4 (running Cruise server) only need to be done on one node which might be or might not be a Kafka node, as long as it can connect to Kafka and ZooKeeper.

**Comment by nareshv** [comment]
One CC manages one kafka Cluster. You should deploy CC on a host which is different from kafka broker(s) and make sure it has access to the zookeeper & the brokers.

**Comment by Sugaroverdose** [comment]
@nareshv if i understand it right, @functicons does knows that but "Quick Start" does not says it clearly, so this issue is a suggestion to clarify where to install Cruise Control in Quick Start wiki page

**Comment by functicons** [comment]
@Sugaroverdose yes, that is what I mean.
