### ISSUE TITLE
make sure all exception responses send non HTTP 200-OK status codes

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#627]
Sometimes CC sends 200OK in the response headers and throws exceptions in the logs by sending a empty response to caller.

Client doesn't have any knowledge about what happened in this case without really logging into the server and going through the logs.

Example: https://github.com/linkedin/cruise-control-ui/issues/14#issuecomment-473542478

**Comment by efeg** [comment]
this was addressed in the latest version of the code.
