### ISSUE TITLE
User Task Status attribute to decide whether to make follow-up calls for recently submitted request.

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#631]
For Rest API requests, CC sends the following data currently

1. `User-Task-Id` in the response header and a NormalResponse body
2. `User-Task-Id` in the response header and AsyncResponse body
3. No `User-Task-Id` in the response header and NormalResponse body

In order for clients to keep polling for the status of the recently submitted request we are relying on the `User-Task-Id`. To make this robust, we need to parse the body and see if the response body contains Async payload.

To make it easier for clients to decide whether to make a follow-up call for the request thats just made (without parsing the body), we can add another attribute `User-Task-Status: (Active|Completed| ...)`. Using this additional attribute, clients can make a call whether to send the request to CC with this `User-Task-Id` header or not.

Two approaches for adding this new attribute:
1. Append this to the `User-Task-Id` header value. Ex: `User-Task-Id: aaa-bbb-ccc; Active`
2. Add a new header `User-Task-Status` header as part of responses from CC.

**Comment by efeg** [comment]
As of https://github.com/linkedin/cruise-control/pull/876 (i.e. since version `2.0.61` and `0.1.64`), CC uses `SC_ACCEPTED` (i.e. `202`) code in the header to indicate user tasks that are in progress, `SC_OK` (i.e. `200`) for successfully completed tasks, and other relevant error codes for client/server failures.
