### ISSUE TITLE
Auto partition rebalance after broker failure doesn't work?

### ISSUE THREAD

**Issue by functicons** [linkedin/cruise-control#642]
I have followed the README, made CC up and running with self.healing.enabled=true for my Kafka cluster, I wanted to test it automatically rebalance partitions after broker failures. So I created several topics, each with multiple partitions, and produced some sample data, then I took down one of the nodes, hoping that CC will automatically rebalance partitions and fix under-replicated replicas (by auto partition reassignment I guess), but that didn't happen after >1 hour.

What I can tell from the <host>:9090/kafkacruisecontrol/state page is that, the broker failure was detected, but no action was taken, under-replicated replicas are still there.

MonitorState: {state: RUNNING(10.800% trained), NumValidWindows: (0/1) (0.000%), NumValidPartitions: 74/124 (59.677%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: true, readyGoals: [ReplicaDistributionGoal, RackAwareGoal, TopicReplicaDistributionGoal, ReplicaCapacityGoal]}
AnomalyDetectorState: {selfHealingEnabled:[METRIC_ANOMALY, GOAL_VIOLATION, BROKER_FAILURE], selfHealingDisabled:[], recentGoalViolations:[{anomalyId=GOAL_VIOLATION-344-8173-ba8a1711cd9b, detectionDate=2019-04-06_00:09:13 UTC, fixableViolatedGoals=[RackAwareGoal, ReplicaCapacityGoal], unfixableViolatedGoals=[], status=COMPLETENESS_NOT_READY, statusUpdateDate=2019-04-06_00:09:13 UTC}], recentBrokerFailures:[{failedBrokersByTimeMs={10002=1554509350831}, anomalyId=BROKER_FAILURE-f20-92a8-856e4dcba5be, detectionDate=2019-04-06_00:09:13 UTC, status=CHECK_WITH_DELAY, statusUpdateDate=2019-04-06_00:09:13 UTC}, {failedBrokersByTimeMs={10002=1554509350831}, anomalyId=BROKER_FAILURE-e11-8063-e16be227b3be, detectionDate=2019-04-06_00:09:10 UTC, status=CHECK_WITH_DELAY, statusUpdateDate=2019-04-06_00:09:10 UTC}], recentMetricAnomalies:[]}

Anything else I need to do to trigger the behavior? In general, I think we need a guideline to verify CC is working for a Kafka cluster (in basic/simple scenarios).

**Comment by kidkun** [comment]
Hey @functicons 
Normally broker failure self-healing happens in follow manner
broker-failure_detected -> 
wait for period time (set by `broker.failure.alert.threshold.ms`), if broker is still down,  send the alert  -> wait another period time (set by `broker.failure.self.healing.threshold.ms`), if the broker is down, trigger the fix

I see in your `State` endpoint that 
`recentBrokerFailures:[{failedBrokersByTimeMs={10002=1554509350831}, anomalyId=BROKER_FAILURE-f20-92a8-856e4dcba5be, detectionDate=2019-04-06_00:09:13 UTC, status=CHECK_WITH_DELAY, statusUpdateDate=2019-04-06_00:09:13 UTC}, {failedBrokersByTimeMs={10002=1554509350831}, anomalyId=BROKER_FAILURE-e11-8063-e16be227b3be, detectionDate=2019-04-06_00:09:10 UTC, status=CHECK_WITH_DELAY, statusUpdateDate=2019-04-06_00:09:10 UTC}`
looks like the grace period set by above two config has not expired so Cruise Control does not trigger the self-healing.

**Comment by functicons** [comment]
Thanks @kidkun, but I do waited long enough for the grace period to expire.

I asked Adem Efe Gencer, here is what he said:

>  COMPLETENESS_NOT_READY means that Cruise Control (CC) was unable to collect sufficient samples from Kafka to generate a cluster model on which it will operate to perform the rebalance. This could be due to either of the two (1) you have just started CC, so it hasn't had time to collect samples, yet (give up to 1 hour) (2) there is a problem in collecting samples from Kafka. Can you verify that you configured metrics reporter correctly on Kafka-side? Did you follow the quick-start tutorial on CC Github page to setup metrics reporter? Does your metrics reporter topic get any data from Kafka?

**Comment by functicons** [comment]
I was told this is a known issue for low traffic cluster. It worked when I first generate some traffic, let CC get some samples, then shutdown a broker.
