### ISSUE TITLE
cruise-control should provide an OpenAPI specification

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#649]
# Background
`cruise-control` currently uses servlets to define its available endpoints, parameters, and interaction mechanisms (e.g. header manipulation, POST/GET).
# Issue
While this server-side implementation is correct, its implementation does not allow for `cruise-control` client implementations except by human-inspection of the various endpoint and parameter classes.  

This in turn means that `cruise-control` client implementations are highly-manual, subject to implementation bugs, and do not update whenever the `cruise-control` server resources are extended.
# Proposal
`cruise-control` should adopt the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification) to fully define its REST interface.

By adopting this widely-used specification, `cruise-control`'s [server and client APIs would derive from a single source of truth](https://swagger.io/tools/swagger-codegen/), meaning that extensions to the REST interface could more-quickly propagate to both server- and client-side code.

Additionally, by adopting OpenAPI, `cruise-control` would make it significantly easier for users to [compile their own client APIs in a wide variety of popular languages](https://github.com/swagger-api/swagger-codegen#template-creator), including Java, Python, Go, PHP, JavaScript, Bash, Swift, etc.

**Comment by efeg** [comment]
Closing the issue as it has been addressed in PRs linked to this ticket.
