### ISSUE TITLE
The goal for a proposal says fixed when it is not

### ISSUE THREAD

**Issue by srinivas-d-12** [linkedin/cruise-control#65]
There are 2 issues 
1. The goal shows that the status (FIXED) but the replica's are not moved.  I have enabled self healing
2. When a post request is issued - /kafkacruisecontrol/rebalance?goals=ReplicaDistributionGoal&dryrun=true. The goal shows as VIOLATED. This is very confusing for the user
Kindly take a look at the image present attached

<img width="1600" alt="screen shot 2017-10-23 at 11 06 19 am" src="https://user-images.githubusercontent.com/5590124/31905689-ddce48ea-b7e3-11e7-9e81-fce15e17c834.png">

**Comment by becketqin** [comment]
@srinivas-d-12 We fixed that in #52 . Previously the /proposals and /rebalance /add_brokers /remove_brokers does not give consistent format.
