### ISSUE TITLE
Add expiry value to JSESSIONID cookie for Tasks

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#661]
We have hit a bug in our production environment when both UserTaskId & Sessions are used.

on CCFE:

1. User makes a request to executor substate (Task-1-UUID)
2. User performs a rebalance on cluster
3. User fetches the executor substate again (Task-3-UUID)

After 3rd step, user is always getting the response from the first request, this is because the cookie from the first request never got expired and the browser keeps sending it back.

User experience: user is not able to see the new rebalance progress

Solution: User has to manually delete the cookie from Task-1 and then things became normal.

**Comment by kidkun** [comment]
Currently there is a [config](https://github.com/linkedin/cruise-control/blob/3347721c3490e77add16faa918f34813f4619233/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java#L689)  fpr session expiry,  default value is set to 1 min.

**Comment by efeg** [comment]
As indicated in @kidkun's response, users can avoid this by setting a low session expiry time or using UUID-basd task management.
