### ISSUE TITLE
Configurations wiki page has a number of configuration values incorrectly marked N in the required column.

### ISSUE THREAD

**Issue by BrianGallew** [linkedin/cruise-control#672]
If I set just the required values, CruiseControl will fail to run until the following ones are *also* set.

goals
default.goals
partition.metrics.window.ms
broker.metrics.window.ms
num.broker.metrics.windows
num.partition.metrics.windows

Debugging this issue was a never-ending series of "delete a line from the config, see when it breaks".

**Comment by efeg** [comment]
@BrianGallew Thanks for bringing this up, and sorry for the confusion! I updated the required configs in the [Wiki](https://github.com/linkedin/cruise-control/wiki/Configurations).
