### ISSUE TITLE
Features not yet supported in Kafka 2.1+

### ISSUE THREAD

**Issue by nat-stripe** [linkedin/cruise-control#689]
In the README, there is an interesting line:
> Support for Apache Kafka 2.1+ is in progress.

Are some things known to not yet work or be untested with Kafka 2.1+? And are there particular areas where contributions would be appreciated?

**Comment by aravindvs** [comment]
+1 - will be good to know what might not yet work on 2.1+?

**Comment by prune998** [comment]
And what about Kafka 2.3 ?

**Comment by stanislavkozlovski** [comment]
It would be great to understand how far in progress we are and whether contributors can help.

I want to bump it to 2.3 and eventually to 2.4 so I can contribute changes that make use of the new reassignment API in Kafka (KIP-455).

I actually have a PR that bumps it to 2.3 - https://github.com/linkedin/cruise-control/pull/924
Are there any known blockers that may prevent us from merging that PR?

**Comment by austinnichols101** [comment]
I think this is addressed by #990 / #991
