### ISSUE TITLE
CC Metrics Reporter can't send metrics if same NodeId change IP

### ISSUE THREAD

**Issue by BDeus** [linkedin/cruise-control#698]
Hi,
i have a strange issue that i can't explain.
In some use case, i need to replace a broker and keep the old brokerID to the new node.
So the IP of new broker change to a new one but the broker remain the same.
All of my KafkaProducer Application doesn't care and switch to new node when it has leader ready.
But CC Metrics reporter can't send metrics to new brokers because it keep an old BrokerId/IP association and failed to send metrics.
I need to reboot all my nodes to clean this association and get a cruise control available again.

That the error i got on Kafka Broker
`[2019-05-10 10:00:30,738] WARN Failed to send 10 metrics for time 1557475110712 (com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter)
[2019-05-10 10:00:41,902] WARN [Producer clientId=CruiseControlMetricsReporter] Connection to node 1006 (/10.24.9.62:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)`

**Comment by efeg** [comment]
@BDeus Does this issue still happen? Which version of Kafka server and client are you using? Finally, would you share the configuration for `cruise.control.metrics.reporter.bootstrap.servers` for metrics reporter -- e.g. is it using DNS discovery?

**Comment by efeg** [comment]
Closing the issue. Please reopen if you still see the problem.
