### ISSUE TITLE
Feature request: cruise-control should be able to provide capacity of a broker via /load endpoint

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#699]
Currently, cruise control provides brokers' utilization of resource(`CPU`/`DISK`/`NW_IN`/`NW_OUT`) via the `/load` endpoint, it is good to make CC report the capacity of these resource so the user get a view of how heavy the broker is loaded.

A straightforward way is to add more columns in response(`DISK_CAPACITY`, `CPU_CAPACITY`, `NW_IN_CAPACITY`, `NW_OUT_CAPACITY`), but doing so have two drawbacks.
1. it is not back-compatible, which may not be an issue in plaintext format, but it will break anything built upon CC(e.g CCFE) which depends on the JSON format.
2. calculate utilization is a resource-heavy calculation(and take long time for large cluster), if user only want to get capacity info, it would be waste of both computing resource and user's time

A better approach is to add a new parameter, like `capacity`, to `load` endpoint, by default it is set to `false` and CC return the same thing as of today; if this is set to `true`, CC can only return broker capacity information.

**Comment by jingyli** [comment]
@kidkun Hi Kun, I can take a look into this issue and pick it up, thanks!

**Comment by jingyli** [comment]
@kidkun Hi Kun, I am in the middle of implementing this issue and would like to ask for a clarification on the code structure. 

Should we create a new class dedicated to only fetch the capacity related stats for each broker? Or should we extend the existing `BrokerStats` class to support this functionality?

**Comment by kidkun** [comment]
@jingyli  Sorry for delay in response, I think we can just updates `BrokerStats`, otherwise it needs larger scope of refactor of servlet code(if one endpoint can potentially return response of different class type).

**Comment by efeg** [comment]
Closing the issue as it has been addressed in https://github.com/linkedin/cruise-control/pull/868.
