### ISSUE TITLE
different `min.monitored.partition.percentage` in state report than configuration file

### ISSUE THREAD

**Issue by henhiskan** [linkedin/cruise-control#738]
I have `min.monitored.partition.percentage=0.90` in configuration file, but
when I read state report (Goal Readiness section), I can see all the goals with
`minMonitoredPartitionPercentage=0.995`

I discovered this while testing CC, removing a broker (without self healing), then 
restart CC with self healing activated and some partitions went to invalid. That produced:
`NumValidPartitions: 1501/1588 (94.521%),` invalidating the window and generating the log message `"Cannot get proposal because model completeness is not met."`
So no proposal was generated. 

I changed `minMonitoredPartitionPercentage` from the default 0.95 to 0.90, restarted CC
, but that rate seems to be the same 0.95, and CC keep refusing to generate a proposal.

Finally I just manually remove those topics, and NumValidPartitions increase to 100% and CC built the proposal. 

I hope my description makes any sense, BTW I'm using CC 2.0.46
Thanks.-

**Comment by henhiskan** [comment]
I found out there is another configuration variable  `min.valid.partition.ratio` in https://github.com/linkedin/cruise-control/blob/049818ebfc769550d41d78d3ff6d064733092f11/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java#L231

Setting that variable in the configuration file did change the `minMonitoredPartitionPercentage` reported in the state report.

So, I will guess that the documentation is not updated since just above that code it says:
`<code>min.monitored.partition.percentage</code>`

**Comment by efeg** [comment]
@henhiskan Thanks for reporting the issue, and sorry for the late response!
This indeed is a typo in the configuration name and documentation. Created https://github.com/linkedin/cruise-control/pull/781 to address the issue.
