### ISSUE TITLE
Add an option to blacklist topics from cruise control.

### ISSUE THREAD

**Issue by UnsignedLong** [linkedin/cruise-control#75]
Hi,

we're using https://github.com/andreas-schroeder/kafka-health-check which creates several kafka topics. One broker health topic with one partition assigned to the broker and a "replication-check" topic with one replica per broker.
The problem is - when using the rack-aware goal, cruise control catches an exception because there are more replicas than racks.
Because of this it would be great to be able to blacklist whole topics from cruise control. Blacklisting the topic from partition movement is not sufficient here because the rack-aware goal still throws exceptions.

**Comment by becketqin** [comment]
Thanks for reporting the issue. Yes, the current code does not treat the blacklisted topic separately when doing verification. Will fix it.

**Comment by efeg** [comment]
https://github.com/linkedin/cruise-control/pull/79 should solve this issue.
