### ISSUE TITLE
Add options to __KafkaCruiseControl* topic creation

### ISSUE THREAD

**Issue by UnsignedLong** [linkedin/cruise-control#76]
We're using log compaction by default. To make cruise control work we have to set the cleanup.policy to "delete".
It would be great if we can specify this (and maybe other topic configs) inside cruise control so they're set by default on topic creation.

**Comment by becketqin** [comment]
Good point. Are you interested in submitting a patch?

**Comment by UnsignedLong** [comment]
tl;dr: no
I'm not a java developer at all :[
