### ISSUE TITLE
training model progress stuck at 20%

### ISSUE THREAD

**Issue by linehrr** [linkedin/cruise-control#761]
we have fairly big cluster of kafka about 26 nodes and pretty heavy traffic pattern. 
all brokers are configured with metric reporter and are reporting metrics.
however, the training model progress just stuck at 20% forever. see screenshot below:
![Screen Shot 2019-06-11 at 4 21 52 PM](https://user-images.githubusercontent.com/1124115/59303946-52c8fd00-8c65-11e9-9d0d-4bd9b185352e.png)

does anyone know what the reason would be? we can't seem to find any related info from the document.

**Comment by efeg** [comment]
`Training` is a WIP -- i.e. it is currently not used by Cruise Control. You can safely ignore its value.
