### ISSUE TITLE
[Question] Is this the same repo that is used at Linkedin in production?

### ISSUE THREAD

**Issue by gowthamgutha** [linkedin/cruise-control#774]
Is this repo an **exact mirror** or the **original source** of Cruise control used at production or is there any change in the production version?

**Comment by efeg** [comment]
Hi @gowthamgutha 

Except for several custom pluggable components, such as internal implementations of `BrokerCapacityConfigResolver` and `AnomalyNotifier`, this repository provides the same code we use in production at LinkedIn.

-- i.e. yes, this repository is the upstream of the LinkedIn Cruise Control.
