### ISSUE TITLE
Support for secured zookeeper clients

### ISSUE THREAD

**Issue by rahuldhev** [linkedin/cruise-control#775]
Sometimes we need to connect to a secured zookeeper, and I've seen that CC does not support it yet.
I played around a bit and was able to make a few changes to connect to a secured zookeeper.
Are there any plans to do the same in the future? 
Would be happy to contribute if not, and I'm open to suggestions!

**Comment by efeg** [comment]
Hi @rahuldhev ,
This discussion came up before at issue https://github.com/linkedin/cruise-control/issues/292. I think support for making this configurable would be quite straightforward, and we would be happy to accept your contribution if you could create a PR on this.

**Comment by rahuldhev** [comment]
#787

**Comment by rahuldhev** [comment]
Referencing PR #787

**Comment by rahuldhev** [comment]
Thank you @efeg for reviewing the PR.
