### ISSUE TITLE
Ability to notify Channels on Microsoft Teams

### ISSUE THREAD

**Issue by MattPumphrey** [linkedin/cruise-control#776]
Hello, I see that there is the ability to notify via slack.  While that is a great feature.  It would be pretty amazing if we could trigger a notification via other common messaging platforms.  Currently we use Microsoft Teams.  Where we communicate with our Developers who are using the kafka platform.

**Comment by heisenbug3** [comment]
Hi! Is this something that is seen as adding a value, if so I'd interested to learn more and potentially work on it.
