### ISSUE TITLE
violation and failure detection log REST end point

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#78]
Its good to have a chronological list of events which can be made available as a REST end point in CC.

Right now, we can have custom notifications via emails for

1 goal violation detection
2 broker failures, etc

If we can hit this /kafkacruisecontrol/events, we should  be able to see the most recent things that the CC was able to detect on a broker cluster.

**Comment by efeg** [comment]
Support for this was added in (1) PR https://github.com/linkedin/cruise-control/pull/376 and (2) PR https://github.com/linkedin/cruise-control/pull/304.
