### ISSUE TITLE
Make migrate_to_kafka_2_0 branch the master

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#788]
Currently 
* the `migrate_to_kafka_2_0` branch of Cruise Control is compatible with Apache Kafka `1.1+`
* `master` branch of Cruise Control is compatible with Apache Kafka `0.11` and `1.0`.

Move the 
* current `master` to `for_kafka_1_0`, then
* `migrate_to_kafka_2_0` to `master`.

**Comment by stanislavkozlovski** [comment]
Does it makes sense to also create a new branch for the latest Kafka version @efeg ?

**Comment by efeg** [comment]
Closing the issue as the latest supported Kafka version has already been made the `master`.
