### ISSUE TITLE
Rebalance operation should hold cluster model semaphore when calculating and submitting proposal

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#797]
In current implementation, rebalance does not hold [cluster model semaphore ](https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/LoadMonitor.java#L79)when [submitting the proposal](https://github.com/linkedin/cruise-control/blob/9da185672e85f3163d8e8de6fe548b7222659c62/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControl.java#L388), this could result in significant resource waste on redundant proposal calculation.

**Comment by efeg** [comment]
Closing the issue as the codebase has adopted a standardized approach for all goal-based runnables since the issue was reported.
