### ISSUE TITLE
cannot connect to Bootstrap broker

### ISSUE THREAD

**Issue by templarzq** [linkedin/cruise-control#8]
[2017-08-30 19:01:21,153] INFO Initiating client connection, connectString=172.16.22.16:2181/ sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@40e6dfe1 (org.apache.zookeeper.ZooKeeper)
[2017-08-30 19:01:21,171] INFO Opening socket connection to server 172.16.22.16/172.16.22.16:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2017-08-30 19:01:21,182] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2017-08-30 19:01:21,188] INFO Socket connection established to 172.16.22.16/172.16.22.16:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2017-08-30 19:01:21,251] INFO Session establishment complete on server 172.16.22.16/172.16.22.16:2181, sessionid = 0x35e1785afbac94c, negotiated timeout = 30000 (org.apache.zookeeper.ClientCnxn)
[2017-08-30 19:01:21,252] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2017-08-30 19:01:21,498] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:21,704] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:21,910] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:22,116] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:22,321] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:22,526] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:22,730] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)
[2017-08-30 19:01:22,934] WARN Bootstrap broker 172.16.22.16:9092 disconnected (org.apache.kafka.clients.NetworkClient)

**Comment by templarzq** [comment]
tcp6       0      0 :::9092                 :::*                    LISTEN     
tcp6       0      0 172.16.22.14:56830      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:38302      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:34130      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:36662      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:42150      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:36314      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:52150      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:57246      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:38930      172.16.22.26:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:32896      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:38928      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:34016      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:38020      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:35744      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:36244      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:60330      172.16.22.15:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:37712      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:34018      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:43074      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:34120      172.16.22.16:9092       ESTABLISHED
tcp6       0      0 172.16.22.14:48012      172.16.22.16:9092       ESTABLISHED

**Comment by templarzq** [comment]
kafka 0.10.0.0

**Comment by becketqin** [comment]
Currently Cruise Control is compatible with 0.10.1.0 and above. But 0.10.0.0 would probably still work with some dependency tweak. Can you try replace the dependency of Kafka in build.gradle with 0.10.0.0 and see if that works?

**Comment by templarzq** [comment]
seems like this version only works for scala 2.10？ there are compile errors with scala 2.11

**Comment by becketqin** [comment]
Yeah, I haven't compiled it with Scala 2.11 before, we probably should, especially given Kafka has dropped support for Scala 2.10 since 0.11.0. Do you mind opening an issue for that? Or we can just reuse this issue.

**Comment by spark8103** [comment]
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:28: error: cannot find symbol
import org.apache.kafka.clients.consumer.OffsetAndTimestamp;
                                        ^
  symbol:   class OffsetAndTimestamp
  location: package org.apache.kafka.clients.consumer
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/config/KafkaCruiseControlConfig.java:415: error: cannot find symbol
                CommonClientConfigs.BOOTSTRAP_SERVERS_DOC)
                                   ^
  symbol:   variable BOOTSTRAP_SERVERS_DOC
  location: class CommonClientConfigs
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/KafkaCruiseControlUtils.java:62: error: cannot find symbol
    putIfAbsent(props, config, SslConfigs.SSL_SECURE_RANDOM_IMPLEMENTATION_CONFIG);
                                         ^
  symbol:   variable SSL_SECURE_RANDOM_IMPLEMENTATION_CONFIG
  location: class SslConfigs
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:67: error: cannot find symbol
    Map<TopicPartition, Long> endOffsets = _metricConsumer.endOffsets(assignment);
                                                          ^
  symbol:   method endOffsets(Set<TopicPartition>)
  location: variable _metricConsumer of type Consumer<String,CruiseControlMetric>
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:68: error: cannot find symbol
    Map<TopicPartition, OffsetAndTimestamp> offsetsForTimes = _metricConsumer.offsetsForTimes(timestampToSeek);
                        ^
  symbol:   class OffsetAndTimestamp
  location: class CruiseControlMetricsReporterSampler
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:68: error: cannot find symbol
    Map<TopicPartition, OffsetAndTimestamp> offsetsForTimes = _metricConsumer.offsetsForTimes(timestampToSeek);
                                                                             ^
  symbol:   method offsetsForTimes(Map<TopicPartition,Long>)
  location: variable _metricConsumer of type Consumer<String,CruiseControlMetric>
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:76: error: cannot find symbol
    for (Map.Entry<TopicPartition, OffsetAndTimestamp> entry : offsetsForTimes.entrySet()) {
                                   ^
  symbol:   class OffsetAndTimestamp
  location: class CruiseControlMetricsReporterSampler
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:78: error: cannot find symbol
      OffsetAndTimestamp offsetAndTimestamp = entry.getValue();
      ^
  symbol:   class OffsetAndTimestamp
  location: class CruiseControlMetricsReporterSampler
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/CruiseControlMetricsReporterSampler.java:155: error: cannot find symbol
    consumerProps.setProperty(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, Integer.toString(Integer.MAX_VALUE));
                                            ^
  symbol:   variable MAX_POLL_INTERVAL_MS_CONFIG
  location: class ConsumerConfig
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java:280: error: cannot find symbol
        Map<TopicPartition, Long> beginningOffsets = _consumer.beginningOffsets(_consumer.assignment());
                                                              ^
  symbol:   method beginningOffsets(Set<TopicPartition>)
  location: variable _consumer of type KafkaConsumer<byte[],byte[]>
/root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/KafkaSampleStore.java:281: error: cannot find symbol
        Map<TopicPartition, Long> endOffsets = _consumer.endOffsets(_consumer.assignment());
                                                        ^
  symbol:   method endOffsets(Set<TopicPartition>)
  location: variable _consumer of type KafkaConsumer<byte[],byte[]>
Note: /root/cruise-control/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/analyzer/AnalyzerUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
:cruise-control:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cruise-control:compileScala'.
> javac returned nonzero exit code

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by licheng131n** [comment]
seems like this version only works for 0.10.1.0 0.10.1.1 0.10.2.0 0.10.2.1?
because  scala 2.10

**Comment by becketqin** [comment]
@licheng131n @templarzq #26 has been checked in to support Scala 2.11. Please let me know if you still see any issue.
