### ISSUE TITLE
Ability to See which partitions, topics etc are being moved in real time?

### ISSUE THREAD

**Issue by MattPumphrey** [linkedin/cruise-control#807]
So first, I am not sure if this is the right place, or if it is possible to see this via Cruise Control and Cruise Control Front End, but a thought that I had while either trying to Remove, Rebalance, or perform a POST type action would be to have a GET action that would allow for a view to be generated for what partitions, topics,  or other inter-broker movements are happening during this time.  

I dont know about other people but as an administrator of few different kafka clusters, when either adding, removing, etc.  I would like to be able to verify the movement of the partitions and topics before causing a failure.

**Comment by efeg** [comment]
Hi @MattPumphrey 
IIUC, you are asking to examine the details of one of the following:
1. All `in progress / pending / aborted / aborting / dead / completed` task executions, where each execution task involves details including "what partitions, topics, or other inter-broker movements are happening"

* Please use `substates=executor` in `state` endpoint to limit the results to executor substate
* Please use `verbose=true` to see `in progress / pending / aborted / aborting / dead / completed` task executions in real time.

2. All proposed partition / leadership movements for add/remove/demote brokers, cluster rebalance, or fix offline replicas:

* Please use `verbose=true` to get all proposals showing the requests details.
* Please use `dryrun=true` (default) to refrain from executing the proposals.

Hope it helps!

**Comment by MattPumphrey** [comment]
It does thank you very much.
