### ISSUE TITLE
add /brokers end point to quickly fetch managed brokers

### ISSUE THREAD

**Issue by nareshv** [linkedin/cruise-control#808]
This is an enhancement request which tries to add a `/brokers` end point which quickly returns the broker details `brokerId` and `hostname`.

Current we have `/kafka_cluster_state` which doesn't have the hostname. We can enhance the `/kafka_cluster_state` to return the hostname as additional attribute or add this new `/brokers` end point

Spec:
```
GET: /brokers
Response: 
{
   "400": "kafka-A.example.com",
   "401": "kafka-broker-B.example.com",
   "402": "kafka-broker-402-us.example.com"
}
```

**Comment by efeg** [comment]
`hostname` information is already available in `load` endpoint. https://github.com/linkedin/cruise-control/issues/1191 will help quickly returning the response from this endpoint -- i.e. w/o the need for generating a cluster model for retrieving utilization.
