### ISSUE TITLE
Why we set replicationThrottle to null in the fix method of Anomaly?

### ISSUE THREAD

**Issue by Wennn** [linkedin/cruise-control#842]
In my view, the value replicationThrottle works only when accepting the HTTP request, and the values passed by the fix method are all null. So why we do not use the value from config instead of null?
If I misunderstand it, please point out my mistake. 
Thx a lot.

**Comment by kidkun** [comment]
hey @Wennn , I think this is a good point! We should pick up the config default value(just like `InterBrokerPartitionMovementConcurrency` and `LeadershipMovementConcurrency`).
Are you interested in creating a PR to address it?

**Comment by Wennn** [comment]
ok, I will do it.
thx for reply:)
