### ISSUE TITLE
Post call to change replication count is throwing NullPointerException

### ISSUE THREAD

**Issue by saritago** [linkedin/cruise-control#853]
curl -X POST -c cookie "https://localhost:9090/kafkacruisecontrol/topic_configuration?topic=__test.replication&replication_factor=4&dryRun=true"
Error processing POST request '/topic_configuration' due to: 'com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.NullPointerException'

**Comment by kidkun** [comment]
Hey @saritago  
Can you post the full stack trace from the server log? And which version are you  using?Thanks.

**Comment by saritago** [comment]
Hi,

I had loaded release 2.0.57. Will share the stack trace.

**Comment by efeg** [comment]
@saritago please share the stack trace if the issue reoccurs -- closing due to no followup.
