### ISSUE TITLE
Example Configuration for low traffic test clusters

### ISSUE THREAD

**Issue by barryWarnock** [linkedin/cruise-control#854]
Hey folks. I'm working on integrating Cruise Control into our CI suite as a first step for adoption but I'm running into an issue. We're seeing:
  INFO Skipping proposal precomputing because load monitor does not have enough snapshots.
Which I believe is do to the fact that our CI cluster has next to no load, we only do a basic single message end to end test so I don't think Cruise Control is seeing the number of valid partitions it wants before it will start balancing. Has anybody run into a similar scenario and if so would they mind sharing their Load Monitor Configurations? Basically what I'm trying to do is create a 2 partition topic with all replicas on the same rack in a four broker 2 rack cluster and watch Cruise Control re-balance it.

If this is the wrong place for this question please advise as to a better place and close.

**Comment by efeg** [comment]
Hi @barryWarnock,
To start a full rebalance, Cruise Control (CC) requires generating a cluster model, which needs metrics from Kafka cluster. If the cluster has low-to-no traffic, some required metrics will not be generated. You may try generating synthetic load in the cluster, and initiate a rebalance afterwards.

Hope it helps!
