### ISSUE TITLE
Question about capacity.json

### ISSUE THREAD

**Issue by BenjaminDavison** [linkedin/cruise-control#87]
Hiya,

What do the values in capacity.json represent?

```
      "capacity": {
        "DISK": "100000",
        "CPU": "100",
        "NW_IN": "10000",
        "NW_OUT": "10000"
      }
```

I'm guessing DISK and NW_IN/OUT are in bytes, but what is CPU measured on?

Thanks,

Ben

**Comment by efeg** [comment]
Hi Ben,

Capacity unit used for disk is in MB, cpu is in percentage, network throughput is in KB.
This information was buried in `BrokerCapacityConfigResolver.java`, but as part of patch https://github.com/linkedin/cruise-control/pull/92, we will update the corresponding doc in `capacity.json` to clarify this.
Thanks for reporting!

Best,
Efe
