### ISSUE TITLE
Feature Request: cruise-control topic_configuration should allow proceed_anyway

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#874]
# Background
`cruise-control`'s `topic_configuration` endpoint allows for setting the replication factor on one or more topics, given a `topic_regex` against which topic names are matched.

When a topic matching the given `topic_regex` already has the specified `replication_factor` (say 3), `cruise-control` returns an exception to the effect that  
```
Topics [...] already have replication factor of '3'
```
# Issue
There are situations (say `topic_regex = ".*"`) when a caller to `cruise-control` might want the replication factor to proceed even though some of the matched topics are already at the given replication factor.

Currently, there is no way to tell `cruise-control` to proceed with the replication factor increase on those topics that aren't already at the specified replication factor.
# Proposal
`cruise-control`'s `topic_configuration` endpoint could accept an additional boolean, perhaps called `proceed_when_matching_topic_has_specified_rf`.

When `True`, this would signal to `cruise-control` that exceptions like `Topics [...] already have replication factor of '3'` should be ignored, while all other exceptions are still thrown.  Probably, this will also require `cruise-control` to remove the matching topics from the derived topic list, before proceeding with the replication factor change.

When `False` (the default, and current, behavior), this would signal to `cruise-control` that it should still throw exceptions like `Topics [...] already have replication factor of '3'` to the user.

**Comment by kidkun** [comment]
@mgrubent  This exception only thrown if all topics matches pattern has the target replication factor.
As long as there is one topic partition need to change RF, this exception will not be thrown.

Inside CC, what happens is like what the proposal suggests, we first find out all the topics matches regex, then do a filter to filter out the topic which has at least one partition whose RF does not match target RF, then we only consider these topics.

**Comment by mgrubent** [comment]
Ah, I was misunderstanding then, thanks for clarifying @kidkun !

The behavior that you outline is acceptable, and I think this is correct.

_Maybe_ the exception text could be clarified to state that `All topics that match the given regular expression (%s) already have replication factor of %d`, so that in the future humans encountering this exception don't misinterpret it, but that's just a suggestion and not a full issue.

**Comment by kidkun** [comment]
Thanks for the suggestion, I will make this change all together in PR #877
