### ISSUE TITLE
Feature Request: cruise-control topic_configuration should accept topic regex as POST data

### ISSUE THREAD

**Issue by mgrubent** [linkedin/cruise-control#875]
# Background
`cruise-control`'s `topic_configuration` endpoint accepts a parameter, `topic`, whose value is a regular expression that specifies which topics to operate on.

When the URI passed to `cruise-control` is too long, `cruise-control` responds with
```
<h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>
```
# Issue
For long topic regexes, it is not possible in a single session with `cruise-control`, to start a `topic_configuration` proposal execution, without somehow shrinking the topic regex.  
This is common in clusters with heterogenous replication factors among topics, where there is no short regular expression that can arbitrarily select any set of topics in the cluster.

For regexes that are constructed as a `|`-delimited list of topic names, this means either that:  
1. Clients must know the longest URI that `cruise-control` will accept ahead of time, and only construct URIs that are shorter than this, or
2. Clients must half their requests to `topic_configuration` each time they receive a `414` from `cruise-control`.

The effect of either is that a client is not able to start a single `cruise-control` `topic_configuration` proposal given a single too-long list of topics.  
This greatly inhibits the programmatic use of `cruise-control` as, rather than a single response, clients must serialize their requests and manage numerous sequential long-running tasks.

# Proposal
For the `topic_configuration` endpoint, there should be some way to select a very-large set of topics, in the course of a single `cruise-control` session.

There are a few different viable approaches for this:  
1. Allow for the topic regex to be sent in the data payload of the `topic_configuration` POST.  Any topic regex sent in this way would override any 'topic=value' parameter in the URI.  
2. Allow for some list or set of exact topic names to be sent in the data payload of the `topic_configuration` POST, if for some reason long regexes in the implementation above are disfavored.  `cruise-control` could then parse this into a `set` and do topic matching against this set.  Yes, regular expressions provide a superset of this functionality.
3. Implement a small 'filter' function on the server side of `topic_configuration`.  This would allow the user to pass logic like `filter=rf_leq2`, to select all topics whose replication factor is less than or equal to 2.  One major drawback of this approach is that if for some reason the replication factor of this set of topics needs to be increased yet again, it may be that those topics cannot be selected by the use of any replication-factor-based filter, for instance if all the topics in the cluster now have the same replication factor.  
4. Do nothing.  Require clients to implement recursion logic.  This is an option, but as noted above it places a high burden on clients seeking to perform replication factor operations programmatically.

**Comment by mgrubent** [comment]
For approach 1 above, a data structure that allows for the submission, in a single request, of the desired replication factor for more than 1 topic regular expression would be ideal.

So, if all topics matching `regex_a` should have their replication factor set to 3, and all topics matching `regex_b` should have their replication factor set to 4:  
```json
{
    "3": "regex_a",
    "4": "regex_b",
    ...
}
```

**Comment by kidkun** [comment]
Thanks for reporting the issue!
Personally prefer proposal 1. :0
