### ISSUE TITLE
'There are already 5 active user tasks, which has reached the servlet capacity.'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)

### ISSUE THREAD

**Issue by saritago** [linkedin/cruise-control#879]
I am seeing this error messages in logs, how does it impact if i increase the max.active.user.tasks value from 5 to 10 or even more?

 ERROR Error processing GET request '/load' due to: 'There are already 5 active user tasks, which has reached the servlet capacity.'. (com.linkedin.kafka.cruisecontrol.servlet.KafkaCruiseControlServlet)
java.lang.RuntimeException: There are already 5 active user tasks, which has reached the servlet capacity.

**Comment by kidkun** [comment]
It will mitigate the issue.
But fundamentally there should not be 5 pending task, it is open an indicator of some task is hang in execution. 
can you send a request to `user_tasks` endpoint to see what are `in-execution` tasks?

**Comment by saritago** [comment]
Do you mean this?

curl -X GET -H "Content-type: application/json" -H "Accept: application/json" "http://localhost:9090/kafkacruisecontrol/load?json=true"
{"version":1,"progress":[{"operation":"Get broker stats","operationProgress":[{"completionPercentage":0.0,"description":"Operation enqueued, waiting to be executed.","step":"PENDING","time-in-ms":11501}]}]}/cruise-control-master/logs

**Comment by saritago** [comment]
Also seeing 
```
 ERROR Sampling scheduler received Timeout exception when waiting for sampling to finish (com.linkedin.kafka.cruisecontrol.monitor.sampling.MetricFetcherManager)
java.util.concurrent.TimeoutException
```

**Comment by saritago** [comment]
Are these get /LOAD requests triggered internally? There were no requests from any other source and I could still see these ERRORs..

**Comment by saritago** [comment]
I could see these messages even before the cluster is in ready state. Which operation creates these load requests internally?
```
INFO Create a new UserTask b7bd4bb0-fee1-407d-9cda-3b4c40320f68 with SessionKey SessionKey{_httpSession=Session@3aaf8771{id=node0jyvws5fp48ef1hzwn8xbpeuw21,x=node0jyvws5fp48ef1hzwn8xbpeuw21.node0,req=1,res=true},_requestUrl=GET /kafkacruisecontrol/load,_queryParams={}} (com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager)
```

**Comment by kidkun** [comment]
can you try `http://localhost:9090/kafkacruisecontrol/user_tasks`, it will show a complete list of user's request(both ongoing and recently completed) with the ip address of the requester
CC itself will never trigger `load` operation, and even if it trigger something(cluster model generation for self healing), it is not counted into this `max.active.user.tasks`

**Comment by saritago** [comment]
This message disappeared after sometime.. Now when i issue a http://localhost:9090/kafkacruisecontrol/user_tasks all the requests status show "completed". I See this behaviour in a cluster that is having huge number of partitions and 3 brokers. Is huge number of partitions the reason for such messages?

**Comment by kidkun** [comment]
It could be the reason, a large number of partition could result in long time to calculate proposal(especially if all distribution goals are used), in our deployment, we have seen a proposal get generated in 30mins.

And inside Cruise Control, proposal is generated one by one, which means if you sent 5 requests which need proposal calculating, the first one will block the following four, and if now you sent 6th request, you will get above exception.

Next time you encounter this, I suggest you first check through `user_tasks` endpoint, you should see one item marked as `active`, then you can pick up the UUID and URL of that task(also shown in `user_tasks` response), send a request like

`curl -vv -X POST -H "User-Task-ID: UUID_you_get" "http://CRUISE_CONTROL_HOST:2540/kafkacruisecontrol/URL_you_get"
`

you can see the progress of that task.

**Comment by saritago** [comment]
I had seen these errors in the logs soon after bringing up a new service. I had not run and get or post call yet i could see these messages.

**Comment by kidkun** [comment]
That sounds interesting. next time you see that, first try `user_tasks` endpoint to see what is shown on panel.

**Comment by efeg** [comment]
The discussion in the thread and the [relevant wiki](https://github.com/linkedin/cruise-control/wiki/REST-APIs) should help with the usability issues.
