### ISSUE TITLE
What are the differences of Valid Partitions vs Flawed Partitions

### ISSUE THREAD

**Issue by MattPumphrey** [linkedin/cruise-control#888]
So I have been wondering this for a while. What are Valid Partitions and Flawed Partitions.  Are these based on the configuration of the topic? What is the effect that this has not only on cruise control but also on Kafka.  As currently we use Kafka for two purposes, one for data manufacturing where we compact topics, and the other is for a Message bus applications.  So just trying to understand a bit more about the status messages in the state abit more.

**Comment by kidkun** [comment]
@MattPumphrey  flawed partition is a concept only relevant with Cruise Control, it means this partition does not have enough metrics sample for one or some time windows and we need to do extrapolation(from the value collected in its previous and next time window) to get an estimate for the metric value these windows. It does not mean that the partition itself is "flawed" in kafka.

**Comment by efeg** [comment]
Closing the issue as I believe @kidkun 's response is clear.
