### ISSUE TITLE
Impact of enabling RackAwareGoal or not ?

### ISSUE THREAD

**Issue by apellegr06** [linkedin/cruise-control#889]
Hello,

I would like to know what is the impact of disabling RackAwareGoal.

Because I have a 4 nodes cluster, and topics have 4 replicas each, but I have only 2 cluster.rack definition (broker 1 and 2 in rack A, broker 3 and 4 in rack B) and with this configuration CC raised an error (Insufficient number of racks to distribute each replica (Current: 2, Needed: 4).

I can't configure 4 racks and I don't need that, I just want to be sure that at least 2 replicas are in the rack A and 2 others replica in the rack B, to still have 2 replicas available if one rack crash.

So if I disable RackAwareGoal, do I meet my needs or is it a risk to have a random distribution of replica when I use the "rebalance cluster" option ?

And is it possible to add the possibility to force the minimum number of rack ?

Thanks
Alain

**Comment by kidkun** [comment]
@apellegr06  turning off `RackAwareGoal` will just remove the guarantee that replicas of the same topic partition are distributed on different racks. 
In cruise control, each goal represent a different property you want from your cluster(e.g. capacity goals ensure that the utilization does not exceed certain threshold and distribution goals ensure the utilization across broker are close), so you can decide which property you want in your kafka cluster and just enable the corresponding goal(search for `goals` in `config/cruisecontrol.properties` and add/remove the goal from the goal list)

**Comment by apellegr06** [comment]
@kidkun thank you for the answer.

But I think for an evolution it could be interesting to add the possibility to force the minimum number of rack by configuration.
