### ISSUE TITLE
Metric Store expose/access via JMX

### ISSUE THREAD

**Issue by Arttii** [linkedin/cruise-control#915]
I was wondering if there is any way to access/expose the gathered metrics via for example JMX or an API? The usecase we are looking at is to use Cruise Control to report the primary Kafka metrics and then scrape this with for example Prometheus or another metrics solution.

Thanks

**Comment by efeg** [comment]
Cruise Control (CC) exposes its own metrics at a user-configurable JMX port, which include executor, anomaly detector, monitor, and analyzer metrics. However, such metrics do not include Kafka metrics. For such use-cases it is best to directly rely on JMX metrics of Kafka -- i.e. CC is not intended as a proxy for Kafka metrics.
