### ISSUE TITLE
Add a new (hard) goal that ensures that each alive broker has a leader replica from a configured pool of topics

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#921]
Other systems in Kafka ecosystem, such as [Kafka Monitor](https://github.com/linkedin/kafka-monitor), may need to ensure that each alive broker has at least one leader replica from a configured pool of topics. Such systems may try to achieve this via their own admin operations, which could be conflicting with Cruise Control (CC) and cause a race condition between such systems. Furthermore, excluding topics that belong to this topic pool (i.e. using CC's configuration to exclude replicas from partition movement via `topics.excluded.from.partition.movement`) may lead to an unbalanced load distribution in clusters -- i.e. in particular in small clusters, where the topics of Kafka Monitor constitute the majority.

- Proposals:

1. Centralize the management needs of such cases -- i.e. CC should add a new (pluggable) goal that provides the intended functionality.
2. (applies to the other goal violations, as well) The default (configurable) frequency of goal violation detection would potentially be increased accordingly to minimize the duration that the cluster violates this constraint.

**Comment by andrewchoi5** [comment]
1. Note the following method within Kafka Monitor open source repository. 
`void maybeReassignPartitionAndElectLeader() throws ExecutionException, InterruptedException, TimeoutException {`
2. This method is called as part of the TopicManagementRunnable’s run() and the topic management runnable (which runs periodically) is scheduled to be executed at _scheduledIntervalMs in milliseconds.
Runnable tmRunnable = new TopicManagementRunnable();
_executor.scheduleWithFixedDelay(tmRunnable, 0, _scheduleIntervalMs, TimeUnit.MILLISECONDS);
3. The default for it is set to be (default)
1000 * 60 * 10 = 600,000 milliseconds = 600 seconds = 10 minutes
in the `MultiClusterTopicManagementConfig` .
Checking the indivdual config files, I see that they are also set at 600,000 milliseconds as of now.

I recommend that you check: `src/main/java/com/linkedin/xinfra/monitor/services/MultiClusterTopicManagementService.java`
as well as `java/com/linkedin/xinfra/monitor/services/configs/MultiClusterTopicManagementServiceConfig.java`
