### ISSUE TITLE
Load endpoint should not report -0.000 CPU utilization

### ISSUE THREAD

**Issue by efeg** [linkedin/cruise-control#953]
Thanks @mgrubent for reporting this!
-- Looks like CPU column allows for negative floating 0:
```
HOST         BROKER             DISK(MB)/_(%)_         CPU(%)       LEADER_NW_IN(KB/s)     FOLLOWER_NW_IN(KB/s)        NW_OUT(KB/s)       PNW_OUT(KB/s)    LEADERS/REPLICAS
 XXX,          XXX,                    XXX/XXX,        -0.000,                    XXX,                      XXX,          XXX,          XXX,           XXX/XXX
```

**Comment by matthinograb** [comment]
I believe these stats were were already fixed, but I could be mistaken: 
https://github.com/linkedin/cruise-control/blob/c64d73c3c133dcdd705488b9f42ea5e10d34e3bf/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/response/stats/BasicStats.java#L45-L53

**Comment by efeg** [comment]
Closing the issue. Please reopen if you still see the problem.
