### ISSUE TITLE
What's the main reason to not leverage helix

### ISSUE THREAD

**Issue by newpoo** [linkedin/cruise-control#96]
I am curious if helix was considered when implementing cruise control. What's the main reason to not build cruise control on top of helix?

Thanks,
Bo

**Comment by becketqin** [comment]
@newpoo Good question. In fact, we have discussed with Helix team and we will work together to see if Helix can reuse some part of CC to enhance its balancing logic.

That said, the scope of Cruise Control and Helix are a little different. 

Helix is meant to be the distributed system controller itself, i.e. it maintains and changes the state of the system based on the system business logic.

Cruise Control aims a little differently. We are trying to answer the question of how to optimize the cluster let it run in an optimal way. CC itself does not care about the system internal state maintenance.

There are many projects, such as Kafka, having their own control logic without using Helix but still need what CC does. In that case, CC will execute the proposals by invoking corresponding admin operations on that product. For projects using Helix for control, CC will execute the optimization proposals via Helix.

If you have further questions, can you join our gitter room for further discussion?
https://gitter.im/kafka-cruise-control/Lobby
