### ISSUE TITLE
how to rebalance log.dirs=/data/kafka-data,/data1/kafka-data

### ISSUE THREAD

**Issue by huoarter** [linkedin/cruise-control#971]
My kafka cluster has six brokers. Every one broker's total disk size is balance. But one broker's log dirs is not balance  , it is balance when not setup cruise control. How  to rebalance log.dirs please? 
![image](https://user-images.githubusercontent.com/17919074/66654226-577ddc00-ec6c-11e9-986c-dbe3e4e7fdca.png)
![image](https://user-images.githubusercontent.com/17919074/66654237-5ea4ea00-ec6c-11e9-80cf-d9c4f1b9103f.png)

**Comment by kidkun** [comment]
Can you try `rebalance?rebalance_disk=true`? 
It should balance disks utilization within each broker.
If the dry run result looks good to you,  trigger the execution with `rebalance?rebalance_disk=true&dryrun=false`.

**Comment by huoarter** [comment]
My version: cruise-control-metrics-reporter-0.1.59.jar
```Error : 
[root@prd-zbkafka-001 ~]# curl 'prd-zbkafka-001:19090/kafkacruisecontrol/rebalance?dryrun=true&rebalance_disk=true' -XPOST
Unrecognized endpoint parameters in REBALANCE POST request: [rebalance_disk].
```
 Does this versiont support this function?

**Comment by kidkun** [comment]
Unfortunately it does not. 
0.1.* is for 0.11.* kafka version and JBOD is not added to kafka yet.
To have CC support for balancing between disk, please use 2.0.* version. 

every time we release, we release two version, like the 2.0 counterpart for 0.1.59 is 2.0.56(both released on Jun 15)

**Comment by huoarter** [comment]
> Unfortunately it does not.
> 0.1.* is for 0.11.* kafka version and JBOD is not added to kafka yet.
> To have CC support for balancing between disk, please use 2.0.* version.
> 
> every time we release, we release two version, like the 2.0 counterpart for 0.1.59 is 2.0.56(both released on Jun 15)

I get it, Thanks.
