### ISSUE TITLE
rebalance cluster and excluded_topics

### ISSUE THREAD

**Issue by flysen** [linkedin/cruise-control#979]
Hi,
Have added more brokers and need to rebalance the cluster. 
My question is how the regexp should look like for that api-call?
```
         https://cruise-control.company.net/kafkacruisecontrol/rebalance?dryrun=true
		&goals=RackAwareGoal
		&skip_hard_goal_check=true
		&excluded_topics=(_heartbeats|__CruiseControlMetrics)
		&json=true
```
Brgd
Fredrik

**Comment by flysen** [comment]
Some more findings turning on more debug:
Running from GUI get the regexp wrong (excluded_topics=_heartbeats**%257C**__CruiseControlMetrics)
```
Oct 25 08:34:37 cruise-control-app.company.net cruise-control[16209]: [2019-10-25 08:34:37,032] DEBUG REQUEST POST /kafkacruisecontrol/rebalance on HttpChannelOverHttp@17e809fb{r=1,c=false,c=false/false,a=DISPATCHED,uri=//localhost:8081/kafkacruisecontrol/rebalance?dryrun=true&goals=RackAwareGoal&skip_hard_goal_check=true&excluded_topics=_heartbeats%257C__CruiseControlMetrics&json=true,age=0} (org.eclipse.jetty.server.Server)
```
Running via curl works:
```
Oct 25 08:36:30 cruise-control-app.company.net cruise-control[16209]: [2019-10-25 08:36:30,043] DEBUG REQUEST POST /kafkacruisecontrol/rebalance on HttpChannelOverHttp@75afb24c{r=1,c=false,c=false/false,a=DISPATCHED,uri=//localhost:8081/kafkacruisecontrol/rebalance?dryrun=true&excluded_topics=_heartbeats|__CruiseControlMetrics&goals=RackAwareGoal&skip_hard_goal_check=true&json=true,age=0} (org.eclipse.jetty.server.Server)
```
It drills-down to `%257C` that will be translated to `%|` for the gui call which don't work

**Comment by gustmoge** [comment]
We tried to send just a %7C instead of the pipe | , and it works as well. But as stated a %257C dont.

**Comment by efeg** [comment]
@flysen @gustmoge Thanks for reporting the issue!

(CC @nareshv) Looks like a potential bug in [CCUI](https://github.com/linkedin/cruise-control-ui).
Created https://github.com/linkedin/cruise-control-ui/issues/40 and closing this issue -- please track the progress at https://github.com/linkedin/cruise-control-ui/issues/40.

In the meanwhile, [encoding the URL](https://www.urlencoder.org/) and sending it via curl should unblock you.
