### ISSUE TITLE
Make Cruise Control send alert when execution is slow.

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control#980]
It is good to have Cruise Control send out some alert if any tasks takes too long to finish(often indicate something goes wrong in cluster and `AnomalyDetector` may unable to detect at this time since metric sampling is paused when there is ongoing execution.)

Send out an alert in this case at least can notify the user and potentially take some action in time.

**Comment by efeg** [comment]
@kidkun duplicate issue? https://github.com/linkedin/cruise-control/issues/673

**Comment by kidkun** [comment]
you are right. close this one.
